using System;using System.IO;using System.Linq;using UnityEngine;using UnityEngine.UI;using UnityEditor;using UnityEditor.Events;using UnityEditor.SceneManagement;using TMPro;using EternalSteam;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public static class AuthorBaseResourceAccordion{
 static RectTransform Rect(string name,Transform parent){var r=new GameObject(name,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(parent,false);return r;}
 static void Box(RectTransform r,float x,float y,float w,float h){r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);}
 static void Stretch(RectTransform r,float l,float b,float right,float top){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=new Vector2(l,b);r.offsetMax=new Vector2(-right,-top);}
 static TMP_Text Text(string name,Transform parent,TMP_Text template,string text){var r=Rect(name,parent);var t=r.gameObject.AddComponent<TextMeshProUGUI>();t.font=template.font;t.fontSharedMaterial=template.fontSharedMaterial;t.fontSize=18;t.color=new Color(.84f,.9f,.89f);t.text=text;t.raycastTarget=false;t.enableAutoSizing=false;t.textWrappingMode=TextWrappingModes.NoWrap;return t;}
 static Button Button(string name,Transform parent,Button template,string text){var r=Rect(name,parent);var im=r.gameObject.AddComponent<Image>();im.sprite=((Image)template.targetGraphic).sprite;im.type=Image.Type.Sliced;var b=r.gameObject.AddComponent<Button>();b.targetGraphic=im;b.colors=template.colors;var t=Text("Caption",r,template.GetComponentInChildren<TMP_Text>(),text);Stretch(t.rectTransform,8,0,8,0);return b;}
 public static string Main(){if(EditorApplication.isPlaying||EditorSceneManager.GetActiveScene().isDirty)throw new Exception("Clean edit mode required");var setup=EditorSceneManager.GetSceneManagerSetup();var report=new JArray();try{foreach(var name in new[]{"StartRegionSandbox","OpenWorldSandbox"}){
 var scene=EditorSceneManager.OpenScene("Assets/EternalSteam/Scene/Tests/"+name+".unity");var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();if(h.BaseResources!=null)throw new Exception("Already authored");var a=h.gameObject.AddComponent<BaseResourceAccordion>();a.Hud=h;h.BaseResources=a;var template=h.Buttons.Single(b=>b.Id=="resource-fold").View;var font=template.GetComponentInChildren<TMP_Text>();a.Title=font;font.text="기지별 보유 자원";
 var old=h.Layout.ResourceBody;old.gameObject.SetActive(false);old.name="LegacyResourceBody";
 var body=Rect("BaseResourceList",h.Layout.ResourcePanel);body.anchorMin=new Vector2(0,1);body.anchorMax=Vector2.one;body.pivot=new Vector2(.5f,1);body.offsetMin=new Vector2(8,-272);body.offsetMax=new Vector2(-8,-36);h.Layout.ResourceBody=body;
 for(int i=0;i<h.Sections.Length;i++)if(h.Sections[i].Id=="resources")h.Sections[i].Body=body.gameObject;
 var scrollRoot=Rect("BaseScroll",body);Stretch(scrollRoot,0,36,0,0);var scroll=scrollRoot.gameObject.AddComponent<ScrollRect>();scroll.horizontal=false;scroll.vertical=true;scroll.movementType=ScrollRect.MovementType.Clamped;scroll.scrollSensitivity=24;a.Scroll=scroll;
 var viewport=Rect("Viewport",scrollRoot);Stretch(viewport,0,0,10,0);viewport.gameObject.AddComponent<Image>();viewport.gameObject.AddComponent<Mask>().showMaskGraphic=false;scroll.viewport=viewport;
 var content=Rect("Content",viewport);content.anchorMin=new Vector2(0,1);content.anchorMax=Vector2.one;content.pivot=new Vector2(.5f,1);content.sizeDelta=Vector2.zero;
 var layout=content.gameObject.AddComponent<VerticalLayoutGroup>();layout.spacing=6;layout.childControlWidth=layout.childControlHeight=true;layout.childForceExpandWidth=true;layout.childForceExpandHeight=false;content.gameObject.AddComponent<ContentSizeFitter>().verticalFit=ContentSizeFitter.FitMode.PreferredSize;scroll.content=content;
 var bar=Rect("Scrollbar",scrollRoot);bar.anchorMin=new Vector2(1,0);bar.anchorMax=Vector2.one;bar.offsetMin=new Vector2(-8,0);bar.offsetMax=Vector2.zero;bar.gameObject.AddComponent<Image>().color=new Color(.08f,.13f,.15f);var sb=bar.gameObject.AddComponent<Scrollbar>();sb.direction=Scrollbar.Direction.BottomToTop;var handle=Rect("Handle",bar);Stretch(handle,0,0,0,0);var hi=handle.gameObject.AddComponent<Image>();hi.color=new Color(.4f,.65f,.67f);sb.handleRect=handle;sb.targetGraphic=hi;scroll.verticalScrollbar=sb;
 var defs=h.Sandbox.ContentCatalog.Buildings.SelectMany(d=>d.Modules.OfType<ProductionModuleDefinition>().Select(m=>new {Id=m.OutputId,Name=d.DisplayName.Replace(" 생성기","").Replace(" · 검증용","")})).GroupBy(d=>d.Id).Select(g=>g.First()).ToArray();
 a.Rows=new BaseResourceAccordion.Row[4];for(int i=0;i<a.Rows.Length;i++){
 var root=Rect("BaseRow"+i,content);var le=root.gameObject.AddComponent<LayoutElement>();le.preferredHeight=44;var header=Button("BaseHeader",root,template,"기지");var hr=(RectTransform)header.transform;hr.anchorMin=new Vector2(0,1);hr.anchorMax=Vector2.one;hr.pivot=new Vector2(.5f,1);hr.offsetMin=new Vector2(0,-44);hr.offsetMax=Vector2.zero;UnityEventTools.AddIntPersistentListener(header.onClick,a.Toggle,i);
 var stock=Rect("Stocks",root);stock.anchorMin=new Vector2(0,1);stock.anchorMax=Vector2.one;stock.pivot=new Vector2(.5f,1);stock.offsetMin=new Vector2(0,-44-defs.Length*28-8);stock.offsetMax=new Vector2(0,-44);var lines=new BaseResourceAccordion.ResourceLine[defs.Length];
 for(int j=0;j<defs.Length;j++){var d=defs[j];var icon=Rect("Icon_"+d.Id,stock);Box(icon,0,4+j*28,20,20);var im=icon.gameObject.AddComponent<Image>();im.raycastTarget=false;im.preserveAspect=true;var reference=h.ResourceIcons.FirstOrDefault(v=>v.Id==d.Id).View;im.sprite=reference!=null?reference.GetComponent<Image>().sprite:h.Sandbox.RailwayHud.CoalProducer==null?null:h.Portraits.FirstOrDefault(v=>v.DefinitionId==h.Sandbox.RailwayHud.CoalProducer.Id).Sprite;im.enabled=im.sprite!=null;
 var label=Text("Name_"+d.Id,stock,font,d.Name);Box(label.rectTransform,24,j*28,108,28);var value=Text("Value_"+d.Id,stock,font,"0");var vr=value.rectTransform;vr.anchorMin=vr.anchorMax=vr.pivot=new Vector2(1,1);vr.anchoredPosition=new Vector2(-2,-j*28);vr.sizeDelta=new Vector2(116,28);value.alignment=TextAlignmentOptions.MidlineRight;lines[j]=new BaseResourceAccordion.ResourceLine{Id=d.Id,Value=value};}
 stock.gameObject.SetActive(false);root.gameObject.SetActive(false);a.Rows[i]=new BaseResourceAccordion.Row{Root=root.gameObject,Header=header,Name=header.GetComponentInChildren<TMP_Text>(),Body=stock.gameObject,Layout=le,Resources=lines};}
 var empty=Text("NoBases",viewport,font,"활성 기지가 없습니다.");Stretch(empty.rectTransform,8,8,8,8);empty.textWrappingMode=TextWrappingModes.Normal;a.Empty=empty;
 var previous=Button("PreviousBases",body,template,"이전");var next=Button("NextBases",body,template,"다음");var page=Text("BasePage",body,font,"0 / 0");foreach(var r in new[]{(RectTransform)previous.transform,(RectTransform)next.transform,page.rectTransform}){r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,0);r.sizeDelta=new Vector2(80,32);}((RectTransform)previous.transform).anchoredPosition=Vector2.zero;page.rectTransform.anchoredPosition=new Vector2(88,0);((RectTransform)next.transform).anchoredPosition=new Vector2(176,0);page.alignment=TextAlignmentOptions.Center;a.Previous=previous;a.Next=next;a.PageLabel=page;UnityEventTools.AddPersistentListener(previous.onClick,a.PreviousPage);UnityEventTools.AddPersistentListener(next.onClick,a.NextPage);
 h.Layout.Apply(true);EditorUtility.SetDirty(h);EditorUtility.SetDirty(h.Layout);EditorUtility.SetDirty(a);EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);report.Add(new JObject{{"scene",name},{"slots",4},{"resourceTypes",defs.Length},{"persistentCallbacks",6},{"runtimeControlsCreated",false}});
 }}finally{EditorSceneManager.RestoreSceneManagerSetup(setup);}File.WriteAllText("Docs/Measurements/2026-10-02-hud-04/author.json",report.ToString());return report.ToString();}}
