using System;using System.IO;using System.Linq;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using EternalSteam.OpenWorld;
public static class AuthorHud08Circle{
const string Root="Assets/EternalSteam/Shared/UI/ReferenceHUD/";
static Sprite Import(string path){AssetDatabase.ImportAsset(path);var t=(TextureImporter)AssetImporter.GetAtPath(path);t.textureType=TextureImporterType.Sprite;t.spriteImportMode=SpriteImportMode.Single;t.alphaIsTransparency=true;t.mipmapEnabled=false;t.filterMode=FilterMode.Bilinear;t.textureCompression=TextureImporterCompression.Uncompressed;t.SaveAndReimport();return AssetDatabase.LoadAssetAtPath<Sprite>(path);}
public static object Main(){if(Application.isPlaying||EditorSceneManager.GetActiveScene().isDirty)throw new Exception("Clean Edit required");
string maskPath=Root+"MinimapCircleMask.png";if(!File.Exists(maskPath)){const int n=512;var t=new Texture2D(n,n,TextureFormat.RGBA32,false);var pixels=new Color32[n*n];for(int y=0;y<n;y++)for(int x=0;x<n;x++){float d=Vector2.Distance(new Vector2(x+.5f,y+.5f),Vector2.one*n*.5f);pixels[y*n+x]=new Color32(255,255,255,(byte)(d<=n*.5f?255:0));}t.SetPixels32(pixels);t.Apply();File.WriteAllBytes(maskPath,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);}
var mask=Import(maskPath);var ring=Import(Root+"MinimapRing.png");var setup=EditorSceneManager.GetSceneManagerSetup();try{foreach(var name in new[]{"StartRegionSandbox","OpenWorldSandbox"}){var scene=EditorSceneManager.OpenScene("Assets/EternalSteam/Scene/Tests/"+name+".unity");var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();var l=h.Layout;if(l.CircularMap)throw new Exception("Already authored");l.CircularMap=true;l.EscapeHint=(RectTransform)h.transform.Find("EscapeHint");
l.MapPanel.GetComponent<UnityEngine.UI.Image>().enabled=false;l.MapPanel.anchorMin=l.MapPanel.anchorMax=l.MapPanel.pivot=Vector2.one;h.Buttons.Single(b=>b.Id=="minimap-fold").View.gameObject.SetActive(false);
l.MapBody.anchorMin=l.MapBody.anchorMax=l.MapBody.pivot=Vector2.one*.5f;var im=l.MapBody.gameObject.AddComponent<UnityEngine.UI.Image>();im.sprite=mask;im.raycastTarget=false;var m=l.MapBody.gameObject.AddComponent<UnityEngine.UI.Mask>();m.showMaskGraphic=false;
var bezel=new GameObject("MinimapBezel",typeof(RectTransform),typeof(UnityEngine.UI.Image));bezel.transform.SetParent(l.MapPanel,false);var rt=(RectTransform)bezel.transform;rt.anchorMin=Vector2.zero;rt.anchorMax=Vector2.one;rt.offsetMin=rt.offsetMax=Vector2.zero;var img=bezel.GetComponent<UnityEngine.UI.Image>();img.sprite=ring;img.raycastTarget=false;

l.Apply(true);EditorUtility.SetDirty(l);EditorSceneManager.MarkSceneDirty(scene);if(!EditorSceneManager.SaveScene(scene))throw new Exception("Save failed");}
foreach(var name in new[]{"StartRegionSandbox","OpenWorldSandbox"}){EditorSceneManager.OpenScene("Assets/EternalSteam/Scene/Tests/"+name+".unity");var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();if(!h.Layout.CircularMap||h.Layout.MapBody.GetComponent<UnityEngine.UI.Mask>()==null||h.Layout.MapBody.GetComponent<UnityEngine.UI.Image>().sprite==null)throw new Exception("Saved references missing");}}
finally{EditorSceneManager.RestoreSceneManagerSetup(setup);}return new{savedScenes=2,mask=maskPath,frame=Root+"MinimapRing.png",frameSize=ring.texture.width+"x"+ring.texture.height};}}
