using System;using System.IO;using System.Linq;using UnityEngine;using UnityEditor;using UnityEditor.Events;using UnityEditor.SceneManagement;using TMPro;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public static class AuthorHud06B{
static RectTransform Node(string name,Transform p){var r=new GameObject(name,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(p,false);r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.sizeDelta=new Vector2(200,40);return r;}
static void Fill(RectTransform r){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=Vector2.zero;r.offsetMax=Vector2.zero;}
static void Height(GameObject g,float h){var l=g.GetComponent<UnityEngine.UI.LayoutElement>();if(l==null)l=g.AddComponent<UnityEngine.UI.LayoutElement>();l.minHeight=l.preferredHeight=h;l.flexibleHeight=0;}
static TMP_Text Text(string name,Transform p,TMP_Text style,string caption=""){var t=Node(name,p).gameObject.AddComponent<TextMeshProUGUI>();t.font=style.font;t.fontSharedMaterial=style.fontSharedMaterial;t.fontSize=18;t.enableAutoSizing=false;t.color=style.color;t.raycastTarget=false;t.text=caption;return t;}
static void Stack(RectTransform r){var l=r.gameObject.AddComponent<UnityEngine.UI.VerticalLayoutGroup>();l.spacing=8;l.padding=new RectOffset(10,10,8,8);l.childControlWidth=l.childControlHeight=true;l.childForceExpandHeight=false;r.gameObject.AddComponent<UnityEngine.UI.ContentSizeFitter>().verticalFit=UnityEngine.UI.ContentSizeFitter.FitMode.PreferredSize;}
static UnityEngine.UI.Button Button(string caption,Transform p,string command,RailwayServicePanel s){var source=s.Overview.Actions.First(a=>a.Command=="fuel").Button;var b=UnityEngine.Object.Instantiate(source,p);b.name=command;b.onClick=new UnityEngine.UI.Button.ButtonClickedEvent();UnityEventTools.AddStringPersistentListener(b.onClick,s.Execute,command);b.GetComponentInChildren<TMP_Text>().text=caption;Height(b.gameObject,40);return b;}
public static string Main(){if(Application.isPlaying||EditorSceneManager.GetActiveScene().isDirty)throw new Exception("Clean Edit required");var setup=EditorSceneManager.GetSceneManagerSetup();var report=new JArray();try{foreach(var name in new[]{"StartRegionSandbox","OpenWorldSandbox"}){var scene=EditorSceneManager.OpenScene("Assets/EternalSteam/Scene/Tests/"+name+".unity");var v=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>().Sandbox.RailwayHud.GetComponent<RailwayOverview>();if(v==null||v.Services!=null)throw new Exception("Expected existing 06A only");var rail=v.Railway;var s=v.gameObject.AddComponent<RailwayServicePanel>();v.Services=s;s.Overview=v;s.Root=Node("CargoAndDefense",v.Root);s.Scroll=Node("ServiceScroll",s.Root);var scroll=s.Scroll.gameObject.AddComponent<UnityEngine.UI.ScrollRect>();scroll.horizontal=false;scroll.vertical=true;scroll.scrollSensitivity=30;scroll.movementType=UnityEngine.UI.ScrollRect.MovementType.Clamped;var viewport=Node("Viewport",s.Scroll);Fill(viewport);var im=viewport.gameObject.AddComponent<UnityEngine.UI.Image>();im.color=new Color(.04f,.09f,.1f,.8f);viewport.gameObject.AddComponent<UnityEngine.UI.Mask>();scroll.viewport=viewport;var content=Node("Content",viewport);content.anchorMin=new Vector2(0,1);content.anchorMax=Vector2.one;content.sizeDelta=Vector2.zero;scroll.content=content;Stack(content);s.Cargo=Node("Cargo",content);Stack(s.Cargo);s.Defense=Node("Defense",content);Stack(s.Defense);s.CargoSummary=Text("CargoSummary",s.Cargo,rail.Title);var actions=new System.Collections.Generic.List<RailwayOverview.Action>();
void Action(string cmd,string label,Transform parent){actions.Add(new RailwayOverview.Action{Command=cmd,Button=Button(label,parent,cmd,s)});}
Action("next-stop","다음 역 선택",s.Cargo);
foreach(var item in new[]{(rail.Resource,"자원 ID · 최초 적용 후 변경 불가"),(rail.Load,"적재 수량"),(rail.Unload,"하역 수량")}){var label=Text(item.Item1.name+"Label",s.Cargo,rail.Title,item.Item2);Height(label.gameObject,30);var field=item.Item1;field.transform.SetParent(s.Cargo,false);field.transform.localScale=Vector3.one;Height(field.gameObject,40);foreach(var t in field.GetComponentsInChildren<TMP_Text>(true)){t.fontSize=18;t.enableAutoSizing=false;}field.textComponent.rectTransform.offsetMin=new Vector2(6,2);field.textComponent.rectTransform.offsetMax=new Vector2(-6,-2);}
Action("configure","선택 역에 적용",s.Cargo);s.DefenseSummary=Text("DefenseSummary",s.Defense,rail.Title);
foreach(var a in new[]{("weapon-shape","방어칸 크기 변경"),("weapon-next","다음 장착 후보"),("weapon-install","장착 · 철 10"),("weapon-remove","해제 · 환급 없음"),("weapon-upgrade","강화"),("weapon-charge","축전지 충전")})Action(a.Item1,a.Item2,s.Defense);
s.Actions=actions.ToArray();s.Return=Button("운행 화면으로",s.Root,"overview",s);s.Feedback=Text("ServiceFeedback",s.Root,rail.Title);s.Feedback.overflowMode=TextOverflowModes.Ellipsis;s.Root.gameObject.SetActive(false);EditorUtility.SetDirty(v);EditorUtility.SetDirty(rail);EditorUtility.SetDirty(s);EditorSceneManager.MarkSceneDirty(scene);if(!EditorSceneManager.SaveScene(scene))throw new Exception("Save failed");report.Add(new JObject{{"scene",name},{"savedActions",s.Actions.Length},{"sameInputReferences",rail.Resource.transform.parent==s.Cargo}});}}finally{EditorSceneManager.RestoreSceneManagerSetup(setup);}File.WriteAllText("Docs/Measurements/2026-10-02-hud-06b/author.json",report.ToString());return report.ToString();}}
