using System;using System.IO;using System.Linq;using UnityEngine;using UnityEditor;using UnityEditor.Events;using UnityEditor.SceneManagement;using TMPro;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public static class AuthorHud06C{
static RectTransform Node(string name,Transform parent){var r=new GameObject(name,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(parent,false);r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.sizeDelta=new Vector2(400,40);return r;}
static void Fill(RectTransform r){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=r.offsetMax=Vector2.zero;}
static TMP_Text Label(string name,Transform p,RailwayOverview v){var t=Node(name,p).gameObject.AddComponent<TextMeshProUGUI>();t.font=v.DetailText.font;t.fontSharedMaterial=v.DetailText.fontSharedMaterial;t.fontSize=18;t.enableAutoSizing=false;t.color=v.DetailText.color;t.raycastTarget=false;t.textWrappingMode=TextWrappingModes.Normal;return t;}
static UnityEngine.UI.Button Button(string name,string caption,Transform p,RailwayEditorPanel e,string command){var b=UnityEngine.Object.Instantiate(e.Overview.Services.Return,p);b.name=name;b.gameObject.SetActive(true);b.onClick=new UnityEngine.UI.Button.ButtonClickedEvent();if(command!=null)UnityEventTools.AddStringPersistentListener(b.onClick,e.Execute,command);b.GetComponentInChildren<TMP_Text>().text=caption;return b;}
public static string Main(){if(Application.isPlaying||EditorSceneManager.GetActiveScene().isDirty)throw new Exception("Clean Edit required");var setup=EditorSceneManager.GetSceneManagerSetup();var report=new JArray();try{foreach(var name in new[]{"StartRegionSandbox","OpenWorldSandbox"}){var scene=EditorSceneManager.OpenScene("Assets/EternalSteam/Scene/Tests/"+name+".unity");var v=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>().Sandbox.RailwayHud.GetComponent<RailwayOverview>();if(v.Editor!=null)throw new Exception("Already authored");var e=v.gameObject.AddComponent<RailwayEditorPanel>();v.Editor=e;e.Overview=v;e.Root=Node("ConnectionAndRouteEditor",v.Root);e.Tabs=Node("Pages",e.Root);e.Stations=Button("Stations","역 순서",e.Tabs,e,null);e.Diagnostics=Button("Diagnostics","구간·오류",e.Tabs,e,null);UnityEventTools.AddIntPersistentListener(e.Stations.onClick,e.SelectPage,0);UnityEventTools.AddIntPersistentListener(e.Diagnostics.onClick,e.SelectPage,1);e.Scroll=Node("EditorScroll",e.Root);var scroll=e.Scroll.gameObject.AddComponent<UnityEngine.UI.ScrollRect>();scroll.horizontal=false;scroll.vertical=true;scroll.scrollSensitivity=30;scroll.movementType=UnityEngine.UI.ScrollRect.MovementType.Clamped;var viewport=Node("Viewport",e.Scroll);Fill(viewport);var im=viewport.gameObject.AddComponent<UnityEngine.UI.Image>();im.color=new Color(.04f,.09f,.1f,.85f);viewport.gameObject.AddComponent<UnityEngine.UI.Mask>();scroll.viewport=viewport;e.Content=Node("Content",viewport);e.Content.anchorMin=new Vector2(0,1);e.Content.anchorMax=Vector2.one;e.Content.sizeDelta=Vector2.zero;scroll.content=e.Content;var layout=e.Content.gameObject.AddComponent<UnityEngine.UI.VerticalLayoutGroup>();layout.spacing=8;layout.padding=new RectOffset(8,8,8,8);layout.childControlWidth=layout.childControlHeight=true;layout.childForceExpandHeight=false;e.Content.gameObject.AddComponent<UnityEngine.UI.ContentSizeFitter>().verticalFit=UnityEngine.UI.ContentSizeFitter.FitMode.PreferredSize;e.Description=Label("Description",e.Content,v);e.Feedback=Label("Feedback",e.Root,v);e.Feedback.overflowMode=TextOverflowModes.Ellipsis;e.ScrollHint=Label("ScrollHint",e.Root,v);e.ScrollHint.alignment=TextAlignmentOptions.MidlineRight;
var entries=new System.Collections.Generic.List<RailwayEditorPanel.Binding>();
void Add(string cmd,RailwayEditorPanel.Screen screens,bool footer=false,string caption=null){var src=v.Railway.Commands.First(c=>c.Command==cmd).Button;if(src==null)throw new Exception("Missing command "+cmd);var b=Button(cmd,caption??src.GetComponentInChildren<TMP_Text>().text,footer?e.Root:e.Content,e,cmd);var size=b.GetComponent<UnityEngine.UI.LayoutElement>();if(size==null)size=b.gameObject.AddComponent<UnityEngine.UI.LayoutElement>();size.minHeight=size.preferredHeight=40;entries.Add(new RailwayEditorPanel.Binding{Command=cmd,Source=src,Button=b,Screens=screens,Footer=footer});}
foreach(var cmd in new[]{"connection-from","connection-to","connection-from-port","connection-to-port"})Add(cmd,RailwayEditorPanel.Screen.Connection);
foreach(var cmd in new[]{"draft-row:0","draft-row:1","draft-row:2","draft-row:3","draft-prev","draft-next","add","next-stop","remove","up","down","first"})Add(cmd,RailwayEditorPanel.Screen.Stations);
foreach(var cmd in new[]{"issue:0","issue:1","issue:2","issue-prev","issue-next","arrival","departure","map-arrival","map-departure","map-cancel","open-loop","close-loop"})Add(cmd,RailwayEditorPanel.Screen.Diagnostics);
Add("connection-cancel",RailwayEditorPanel.Screen.Connection,true,"취소");Add("connection-preview",RailwayEditorPanel.Screen.Connection,true,"경로 확인");Add("connection-confirm",RailwayEditorPanel.Screen.Connection,true,"연결 확정");Add("cancel",RailwayEditorPanel.Screen.Stations|RailwayEditorPanel.Screen.Diagnostics|RailwayEditorPanel.Screen.Confirm,true,"취소");Add("validate",RailwayEditorPanel.Screen.Stations|RailwayEditorPanel.Screen.Diagnostics,true,"검증");Add("back-edit",RailwayEditorPanel.Screen.Confirm,true,"다시 편집");Add("commit",RailwayEditorPanel.Screen.Confirm,true,"노선 확정");Add("keep",RailwayEditorPanel.Screen.Discard,true,"계속 편집");Add("discard",RailwayEditorPanel.Screen.Discard,true,"변경 폐기");e.Bindings=entries.ToArray();e.Root.gameObject.SetActive(false);EditorUtility.SetDirty(e);EditorUtility.SetDirty(v);EditorSceneManager.MarkSceneDirty(scene);if(!EditorSceneManager.SaveScene(scene))throw new Exception("Save failed");report.Add(new JObject{{"scene",name},{"savedBindings",e.Bindings.Length},{"savedPages",2}});}}finally{EditorSceneManager.RestoreSceneManagerSetup(setup);}File.WriteAllText("Docs/Measurements/2026-10-02-hud-06c/author.json",report.ToString());return report.ToString();}}
