using System;using System.IO;using System.Linq;using UnityEngine;using UnityEngine.UI;using UnityEditor;using UnityEditor.Events;using UnityEditor.SceneManagement;using TMPro;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public static class AuthorHudGroups{
 static RectTransform Root(string n,Transform parent){var r=new GameObject(n,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(parent,false);r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=r.offsetMax=Vector2.zero;return r;}
 static void Box(RectTransform r,float x,float y,float w,float h){r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);}
 public static string Main(){if(EditorApplication.isPlaying||EditorSceneManager.GetActiveScene().isDirty)throw new Exception("Clean edit mode required");var setup=EditorSceneManager.GetSceneManagerSetup();var results=new JArray();try{foreach(var n in new[]{"StartRegionSandbox","OpenWorldSandbox"}){
 var scene=EditorSceneManager.OpenScene("Assets/EternalSteam/Scene/Tests/"+n+".unity");var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();if(h.GetComponent<HudModeGroups>()!=null)throw new Exception("Already authored");RectTransform F(string name)=>h.GetComponentsInChildren<RectTransform>(true).Single(r=>r.name==name);
 var modes=h.gameObject.AddComponent<HudModeGroups>();modes.Hud=h;h.Groups=modes;h.Input.HudGroups=modes;
 var combat=Root("CombatGroup",h.transform);var build=Root("ConstructionGroup",h.transform);modes.Combat=combat.gameObject.AddComponent<CanvasGroup>();modes.Construction=build.gameObject.AddComponent<CanvasGroup>();
 var cl=Root("CombatLeftSlide",combat);var cr=Root("CombatRightSlide",combat);var bl=Root("BuildLeftSlide",build);var br=Root("BuildRightSlide",build);var bb=Root("BuildBottomSlide",build);var bt=Root("BuildTopSlide",build);
 modes.CombatSlides=new[]{new HudModeGroups.Slide{Host=cl,Direction=Vector2.left},new HudModeGroups.Slide{Host=cr,Direction=Vector2.right}};
 modes.ConstructionSlides=new[]{new HudModeGroups.Slide{Host=bl,Direction=Vector2.left},new HudModeGroups.Slide{Host=br,Direction=Vector2.right},new HudModeGroups.Slide{Host=bb,Direction=Vector2.down},new HudModeGroups.Slide{Host=bt,Direction=Vector2.up}};
 var left=F("LeftStatus");var right=F("RightStatus");var resourceHolder=Root("BuildResources",bl);resourceHolder.anchorMin=resourceHolder.anchorMax=resourceHolder.pivot=new Vector2(0,1);resourceHolder.anchoredPosition=new Vector2(16,-84);resourceHolder.sizeDelta=new Vector2(288,0);
 h.Layout.ResourcePanel.SetParent(resourceHolder,false);var selectionHolder=Root("BuildSelection",br);selectionHolder.anchorMin=selectionHolder.anchorMax=selectionHolder.pivot=Vector2.one;selectionHolder.anchoredPosition=new Vector2(-16,-84);selectionHolder.sizeDelta=new Vector2(272,0);h.Layout.SelectionPanel.SetParent(selectionHolder,false);
 left.SetParent(cl,false);right.SetParent(cr,false);h.Layout.ConstructionBar.SetParent(bb,false);h.Sandbox.RailwayHud.transform.SetParent(bl,false);F("PowerSummary").SetParent(bt,true);F("PowerDetails").SetParent(br,false);
 // Date, phase and remaining time share the authored clock panel and its fold state.
 var time=F("TimeSummary");time.SetParent(h.Layout.ClockBody,false);Box(time,112,8,152,92);var background=time.GetComponent<Image>();if(background!=null)background.enabled=false;
 var date=F("date");Box(date,0,0,152,38);var remaining=F("remaining");Box(remaining,0,42,152,44);foreach(var t in new[]{date.GetComponent<TMP_Text>(),remaining.GetComponent<TMP_Text>()}){t.fontSize=18;t.enableAutoSizing=false;t.textWrappingMode=TextWrappingModes.Normal;}
 var dial=F("ClockDial");dial.anchorMin=dial.anchorMax=dial.pivot=new Vector2(0,1);dial.anchoredPosition=Vector2.zero;dial.sizeDelta=new Vector2(104,104);
 // Keep common utilities above sliding groups, with a persistent mouse equivalent for Tab.
 foreach(var id in new[]{"TopBar","Notifications","Developer","TestShortcuts","ProgressAndSave"})F(id).SetAsLastSibling();
 var source=h.Buttons.Single(b=>b.Id=="pause").View;var toggle=UnityEngine.Object.Instantiate(source,h.transform);toggle.name="HudGroupToggle";while(toggle.onClick.GetPersistentEventCount()>0)UnityEventTools.RemovePersistentListener(toggle.onClick,0);UnityEventTools.AddPersistentListener(toggle.onClick,modes.Toggle);var rt=(RectTransform)toggle.transform;rt.anchorMin=rt.anchorMax=rt.pivot=new Vector2(.5f,1);rt.anchoredPosition=new Vector2(0,-16);rt.sizeDelta=new Vector2(220,44);modes.ModeLabel=toggle.GetComponentInChildren<TMP_Text>();modes.ModeLabel.text="Tab · 건설 화면";modes.ModeLabel.fontSize=18;modes.ModeLabel.enableAutoSizing=false;
 modes.Construction.interactable=modes.Construction.blocksRaycasts=false;build.gameObject.SetActive(false);h.ShowDevelopmentControls=true;
 foreach(var section in h.Sections.Where(s=>s.Id is "developer" or "test-shortcuts"))section.Body.SetActive(true);
 h.Layout.Apply(true);EditorUtility.SetDirty(h);EditorUtility.SetDirty(h.Input);EditorUtility.SetDirty(modes);EditorSceneManager.MarkSceneDirty(scene);EditorSceneManager.SaveScene(scene);results.Add(new JObject{{"scene",n},{"combatDefault",true},{"authoredGroups",2},{"testControls",true},{"railwayCommands",h.Sandbox.RailwayHud.Commands.Length}});
 }}finally{EditorSceneManager.RestoreSceneManagerSetup(setup);}File.WriteAllText("Docs/Measurements/2026-10-02-hud-groups/author-01.json",results.ToString());return results.ToString();}}
