using System;using System.IO;using System.Linq;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using TMPro;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public static class AuthorHud05{
static RectTransform Node(string n,Transform parent){var r=new GameObject(n,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(parent,false);return r;}
static void Fill(RectTransform r,float l,float b,float right,float top){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=new Vector2(l,b);r.offsetMax=new Vector2(-right,-top);}
static void Top(RectTransform r,float left,float top,float w,float height){r.anchorMin=r.anchorMax=r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(left,-top);r.sizeDelta=new Vector2(w,height);}
static void Right(RectTransform r,float right,float top,float w,float height){r.anchorMin=r.anchorMax=r.pivot=Vector2.one;r.anchoredPosition=new Vector2(-right,-top);r.sizeDelta=new Vector2(w,height);}
public static string Main(){if(Application.isPlaying||EditorSceneManager.GetActiveScene().isDirty)throw new Exception("Clean Edit required");var setup=EditorSceneManager.GetSceneManagerSetup();var report=new JArray();try{foreach(var n in new[]{"StartRegionSandbox","OpenWorldSandbox"}){var scene=EditorSceneManager.OpenScene("Assets/EternalSteam/Scene/Tests/"+n+".unity");var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();var l=h.Layout;if(l.ConstructionSummary!=null)throw new Exception("Already authored");RectTransform Find(string id)=>h.GetComponentsInChildren<RectTransform>(true).Single(r=>r.name==id);var bar=l.ConstructionBar;
// Existing saved controls keep their persistent callbacks.
l.ExpandedHeight=320;Fill(l.InventoryBody,8,120,8,44);var pending=h.Texts.Single(t=>t.Id=="pending").View;var pr=pending.rectTransform;pr.anchorMin=new Vector2(0,1);pr.anchorMax=Vector2.one;pr.pivot=new Vector2(.5f,1);pr.offsetMin=new Vector2(336,-40);pr.offsetMax=new Vector2(-288,-6);pending.text="카드를 선택하면 배치를 시작합니다.";pending.overflowMode=TextOverflowModes.Ellipsis;pending.textWrappingMode=TextWrappingModes.NoWrap;
Right((RectTransform)h.Buttons.Single(b=>b.Id=="power-fold").View.transform,144,6,128,36);Right((RectTransform)h.Buttons.Single(b=>b.Id=="edit").View.transform,8,6,128,36);
var actions=Find("EditActions");actions.anchorMin=actions.anchorMax=actions.pivot=new Vector2(1,0);actions.anchoredPosition=new Vector2(-8,8);actions.sizeDelta=new Vector2(148,104);Top((RectTransform)h.Buttons.Single(b=>b.Id=="confirm").View.transform,0,0,148,48);Top((RectTransform)h.Buttons.Single(b=>b.Id=="cancel").View.transform,0,56,148,48);
var root=Node("ConstructionSummary",bar);root.anchorMin=Vector2.zero;root.anchorMax=new Vector2(1,0);root.pivot=new Vector2(.5f,0);root.offsetMin=new Vector2(8,8);root.offsetMax=new Vector2(-168,112);l.ConstructionSummary=root;var im=root.gameObject.AddComponent<UnityEngine.UI.Image>();im.sprite=bar.GetComponent<UnityEngine.UI.Image>().sprite;im.type=UnityEngine.UI.Image.Type.Sliced;im.raycastTarget=true;
var scroll=root.gameObject.AddComponent<UnityEngine.UI.ScrollRect>();scroll.horizontal=false;scroll.vertical=true;scroll.movementType=UnityEngine.UI.ScrollRect.MovementType.Clamped;scroll.scrollSensitivity=24;var viewport=Node("Viewport",root);Fill(viewport,8,6,8,6);var vi=viewport.gameObject.AddComponent<UnityEngine.UI.Image>();vi.color=Color.white;viewport.gameObject.AddComponent<UnityEngine.UI.Mask>().showMaskGraphic=false;scroll.viewport=viewport;
var content=Node("Content",viewport);content.anchorMin=new Vector2(0,1);content.anchorMax=Vector2.one;content.pivot=new Vector2(.5f,1);content.sizeDelta=Vector2.zero;scroll.content=content;var group=content.gameObject.AddComponent<UnityEngine.UI.VerticalLayoutGroup>();group.childControlWidth=true;group.childControlHeight=true;group.childForceExpandHeight=false;group.childForceExpandWidth=true;content.gameObject.AddComponent<UnityEngine.UI.ContentSizeFitter>().verticalFit=UnityEngine.UI.ContentSizeFitter.FitMode.PreferredSize;
var label=Node("construction-summary",content).gameObject.AddComponent<TextMeshProUGUI>();label.font=pending.font;label.fontSharedMaterial=pending.fontSharedMaterial;label.fontSize=18;label.color=pending.color;label.raycastTarget=false;label.textWrappingMode=TextWrappingModes.Normal;label.text="선택: 없음 · 대기 0개\n건물 카드를 선택하세요.";h.Texts=h.Texts.Concat(new[]{new CanvasWorldHud.TextBinding{Id="construction-summary",View=label}}).ToArray();l.Texts=l.Texts.Concat(new[]{(TMP_Text)label}).ToArray();l.FontSizes=l.FontSizes.Concat(new[]{18f}).ToArray();
// All three railway buildings already exist in the common catalog. Archive only duplicate construction shortcuts.
foreach(var command in h.Sandbox.RailwayHud.Commands)if(command.Command.StartsWith("build:"))command.Button.gameObject.SetActive(false);
var toolbar=Find("RailwayToolbar");toolbar.gameObject.SetActive(false);
l.FirstLoopObjective=h.Sections.FirstOrDefault(s=>s.Id=="first-loop").Body?.transform as RectTransform;
h.ShowDevelopmentControls=true;l.Apply(true);EditorUtility.SetDirty(h);EditorUtility.SetDirty(l);EditorSceneManager.MarkSceneDirty(scene);if(!EditorSceneManager.SaveScene(scene))throw new Exception("Save failed");report.Add(new JObject{{"scene",n},{"catalogCards",h.Catalog.Length},{"summarySaved",true},{"persistentConfirm",h.Buttons.Single(b=>b.Id=="confirm").View.onClick.GetPersistentEventCount()}});
}}finally{EditorSceneManager.RestoreSceneManagerSetup(setup);}File.WriteAllText("Docs/Measurements/2026-10-02-hud-05/author.json",report.ToString());return report.ToString();}}
