using System;using System.Linq;using UnityEngine;using UnityEditor;using UnityEditor.Events;using UnityEditor.SceneManagement;using TMPro;using EternalSteam.OpenWorld;
public static class AuthorHud08Dock{
static RectTransform Node(string n,Transform p){var r=new GameObject(n,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(p,false);return r;}
static void Fill(RectTransform r,float l=0,float b=0,float right=0,float top=0){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=new Vector2(l,b);r.offsetMax=new Vector2(-right,-top);}
static void Box(RectTransform r,Vector2 a,Vector2 pivot,Vector2 pos,Vector2 size){r.anchorMin=r.anchorMax=a;r.pivot=pivot;r.anchoredPosition=pos;r.sizeDelta=size;}
static void Top(RectTransform r,float x,float y,float w,float height)=>Box(r,new Vector2(0,1),new Vector2(0,1),new Vector2(x,-y),new Vector2(w,height));
public static string Main(){if(Application.isPlaying||EditorSceneManager.GetActiveScene().isDirty)throw new Exception("Clean Edit required");var setup=EditorSceneManager.GetSceneManagerSetup();try{foreach(var name in new[]{"StartRegionSandbox","OpenWorldSandbox"}){var scene=EditorSceneManager.OpenScene("Assets/EternalSteam/Scene/Tests/"+name+".unity");var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();var l=h.Layout;if(l.CompactDock!=null)throw new Exception("Already authored");var d=h.gameObject.AddComponent<CompactConstructionDock>();d.Hud=h;d.PowerSummary=h.GetComponentsInChildren<RectTransform>(true).Single(r=>r.name=="PowerSummary");l.CompactDock=d;var bar=l.ConstructionBar;Box(bar,new Vector2(.5f,0),new Vector2(.5f,0),new Vector2(0,16),new Vector2(1280,156));d.DockInput=bar.gameObject.AddComponent<CanvasGroup>();bar.gameObject.AddComponent<UnityEngine.UI.RectMask2D>();
var source=h.Buttons.Single(b=>b.Id=="power-fold").View;var font=source.GetComponentInChildren<TMP_Text>();
TMP_Text Label(string n,Transform p,int size=18){var t=UnityEngine.Object.Instantiate(font,p);t.name=n;t.text="";t.fontSize=size;t.enableAutoSizing=false;t.raycastTarget=false;t.textWrappingMode=TextWrappingModes.NoWrap;t.overflowMode=TextOverflowModes.Ellipsis;return t;}
UnityEngine.UI.Button Button(string n,Transform p,string text,string command){var b=UnityEngine.Object.Instantiate(source,p);b.name=n;b.onClick=new UnityEngine.UI.Button.ButtonClickedEvent();UnityEventTools.AddStringPersistentListener(b.onClick,d.Execute,command);b.GetComponentInChildren<TMP_Text>().text=text;return b;}
RectTransform Panel(string n){var r=Node(n,h.Groups.Construction.transform);Box(r,new Vector2(1,0),new Vector2(1,0),new Vector2(-16,180),new Vector2(560,320));var im=r.gameObject.AddComponent<UnityEngine.UI.Image>();im.sprite=bar.GetComponent<UnityEngine.UI.Image>().sprite;im.type=UnityEngine.UI.Image.Type.Sliced;return r;}
d.Header=Node("DockHeader",bar);d.HeaderInput=d.Header.gameObject.AddComponent<CanvasGroup>();d.Header.anchorMin=new Vector2(0,1);d.Header.anchorMax=Vector2.one;d.Header.pivot=new Vector2(.5f,1);d.Header.offsetMin=new Vector2(8,-44);d.Header.offsetMax=new Vector2(-8,-8);
var w=h.GetComponent<GameplayHudWorkspace>();w.ConstructionTab.transform.SetParent(d.Header,false);Top((RectTransform)w.ConstructionTab.transform,0,0,96,36);w.ConstructionTab.GetComponentInChildren<TMP_Text>().text="건설";w.RailwayTab.transform.SetParent(d.Header,false);Top((RectTransform)w.RailwayTab.transform,104,0,96,36);w.RailwayTab.GetComponentInChildren<TMP_Text>().text="철도";
l.EditHeader.SetParent(d.Header,false);Box(l.EditHeader,Vector2.one,Vector2.one,Vector2.zero,new Vector2(96,36));l.PowerHeader.SetParent(d.Header,false);Box(l.PowerHeader,Vector2.one,Vector2.one,new Vector2(-104,0),new Vector2(96,36));source.GetComponentInChildren<TMP_Text>().text="전력";
d.ResumeButton=Button("ResumePlacement",d.Header,"배치 복귀","resume");Box((RectTransform)d.ResumeButton.transform,Vector2.one,Vector2.one,Vector2.zero,new Vector2(200,36));
var browse=Node("BrowseSlide",bar);Fill(browse);d.Browse=browse.gameObject.AddComponent<CanvasGroup>();l.InventoryBody.SetParent(browse,false);Fill(l.InventoryBody,8,30,8,52);var catalog=l.InventoryBody.GetComponentInChildren<UnityEngine.UI.ScrollRect>(true);d.CatalogScroll=catalog;Fill((RectTransform)catalog.transform);Fill(catalog.viewport,0,10,0,0);l.Catalog.constraint=UnityEngine.UI.GridLayoutGroup.Constraint.FixedRowCount;l.Catalog.constraintCount=1;l.Catalog.cellSize=new Vector2(190,60);l.Catalog.spacing=new Vector2(6,0);
d.BrowseHint=Label("BrowseHint",browse,14);var bh=d.BrowseHint.rectTransform;bh.anchorMin=Vector2.zero;bh.anchorMax=new Vector2(1,0);bh.pivot=new Vector2(.5f,0);bh.offsetMin=new Vector2(8,6);bh.offsetMax=new Vector2(-8,24);
var cs=Node("CategoryScroll",d.Header);cs.anchorMin=new Vector2(0,1);cs.anchorMax=Vector2.one;cs.pivot=new Vector2(.5f,1);cs.offsetMin=new Vector2(208,-36);cs.offsetMax=new Vector2(-208,0);d.CategoryScroll=cs;var scroll=cs.gameObject.AddComponent<UnityEngine.UI.ScrollRect>();scroll.horizontal=true;scroll.vertical=false;scroll.movementType=UnityEngine.UI.ScrollRect.MovementType.Clamped;scroll.scrollSensitivity=24;var vp=Node("Viewport",cs);Fill(vp);vp.gameObject.AddComponent<UnityEngine.UI.Image>().color=Color.white;vp.gameObject.AddComponent<UnityEngine.UI.Mask>().showMaskGraphic=false;scroll.viewport=vp;l.CategoryStrip.SetParent(vp,false);Top(l.CategoryStrip,0,0,604,36);scroll.content=l.CategoryStrip;
foreach(var c in h.Catalog){var rt=(RectTransform)c.View.transform;foreach(var t in c.View.GetComponentsInChildren<TMP_Text>(true)){t.text=(c.Definition?.DisplayName??t.text.Split('\n')[0]).Split(" · ")[0];t.fontSize=18;t.enableAutoSizing=false;t.textWrappingMode=TextWrappingModes.Normal;t.overflowMode=TextOverflowModes.Ellipsis;Fill(t.rectTransform,60,4,6,4);}if(c.Icon!=null)Top(c.Icon.rectTransform,6,6,48,48);}
var placement=Node("PlacementSlide",bar);Fill(placement);d.Placement=placement.gameObject.AddComponent<CanvasGroup>();d.PlacementTitle=Label("PlacementTitle",placement);var title=d.PlacementTitle.rectTransform;title.anchorMin=new Vector2(0,1);title.anchorMax=Vector2.one;title.offsetMin=new Vector2(8,-30);title.offsetMax=new Vector2(-8,-8);
d.CostBrief=Label("CostBrief",placement,14);d.CostBrief.textWrappingMode=TextWrappingModes.Normal;var cb=d.CostBrief.rectTransform;cb.anchorMin=Vector2.zero;cb.anchorMax=new Vector2(1,0);cb.offsetMin=new Vector2(8,8);cb.offsetMax=new Vector2(-368,44);
l.EditActions.SetParent(placement,false);Box(l.EditActions,new Vector2(1,0),new Vector2(1,0),new Vector2(-8,8),new Vector2(176,36));Top((RectTransform)h.Buttons.Single(b=>b.Id=="confirm").View.transform,0,0,84,36);Top((RectTransform)h.Buttons.Single(b=>b.Id=="cancel").View.transform,92,0,84,36);
d.ListButton=Button("BrowseList",placement,"목록","list");Box((RectTransform)d.ListButton.transform,new Vector2(1,0),new Vector2(1,0),new Vector2(-192,8),new Vector2(76,36));d.CostButton=Button("CostDetails",placement,"비용","cost");Box((RectTransform)d.CostButton.transform,new Vector2(1,0),new Vector2(1,0),new Vector2(-276,8),new Vector2(76,36));
d.CostPanel=Panel("ConstructionCostDetails");var costClose=Button("CloseCostDetails",d.CostPanel,"닫기","close-cost");Box((RectTransform)costClose.transform,Vector2.one,Vector2.one,new Vector2(-8,-8),new Vector2(84,36));var costTitle=Label("CostDetailsTitle",d.CostPanel);costTitle.text="건설 비용 상세";Top(costTitle.rectTransform,12,8,380,36);l.ConstructionSummary.SetParent(d.CostPanel,false);Fill(l.ConstructionSummary,8,8,8,52);l.ConstructionSummary.GetComponent<UnityEngine.UI.Image>().enabled=false;
d.GoalPanel=Panel("ConstructionGoalDetails");var goalClose=Button("CloseGoalDetails",d.GoalPanel,"닫기","close-goal");Box((RectTransform)goalClose.transform,Vector2.one,Vector2.one,new Vector2(-8,-8),new Vector2(84,36));var goalTitle=Label("GoalDetailsTitle",d.GoalPanel);goalTitle.text="현재 목표";Top(goalTitle.rectTransform,12,8,380,36);
var goalScroll=Node("GoalScroll",d.GoalPanel);Fill(goalScroll,8,8,8,52);var gs=goalScroll.gameObject.AddComponent<UnityEngine.UI.ScrollRect>();gs.horizontal=false;gs.movementType=UnityEngine.UI.ScrollRect.MovementType.Clamped;var gv=Node("Viewport",goalScroll);Fill(gv);gv.gameObject.AddComponent<UnityEngine.UI.Image>();gv.gameObject.AddComponent<UnityEngine.UI.Mask>().showMaskGraphic=false;gs.viewport=gv;l.FirstLoopObjective.SetParent(gv,false);l.FirstLoopObjective.anchorMin=new Vector2(0,1);l.FirstLoopObjective.anchorMax=Vector2.one;l.FirstLoopObjective.pivot=new Vector2(.5f,1);l.FirstLoopObjective.anchoredPosition=Vector2.zero;l.FirstLoopObjective.sizeDelta=new Vector2(0,240);gs.content=l.FirstLoopObjective;l.FirstLoopObjective.GetComponent<UnityEngine.UI.Image>().enabled=false;
var goalHost=Node("BuildGoalSlide",h.Groups.Construction.transform);Fill(goalHost);h.Groups.ConstructionSlides=h.Groups.ConstructionSlides.Concat(new[]{new HudModeGroups.Slide{Host=goalHost,Direction=Vector2.up}}).ToArray();d.GoalStrip=Node("GoalStrip",goalHost);Box(d.GoalStrip,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-144),new Vector2(560,36));var gi=d.GoalStrip.gameObject.AddComponent<UnityEngine.UI.Image>();gi.sprite=bar.GetComponent<UnityEngine.UI.Image>().sprite;gi.type=UnityEngine.UI.Image.Type.Sliced;gi.raycastTarget=false;var gb=Button("OpenGoals",d.GoalStrip,"목표 보기","goal");Box((RectTransform)gb.transform,Vector2.one,Vector2.one,Vector2.zero,new Vector2(104,36));d.GoalBrief=Label("GoalBrief",d.GoalStrip,14);Fill(d.GoalBrief.rectTransform,8,0,112,0);
d.CostPanel.gameObject.SetActive(false);d.GoalPanel.gameObject.SetActive(false);
var owned=new[]{bar,d.CostPanel,d.GoalPanel,d.GoalStrip};var keep=l.Texts.Select((t,i)=>(t,size:l.FontSizes[i])).Where(x=>!owned.Any(root=>x.t.transform.IsChildOf(root))).ToArray();l.Texts=keep.Select(x=>x.t).ToArray();l.FontSizes=keep.Select(x=>x.size).ToArray();foreach(var root in owned)foreach(var t in root.GetComponentsInChildren<TMP_Text>(true)){t.enableAutoSizing=false;if(t!=d.CostBrief&&t!=d.BrowseHint&&t!=d.GoalBrief)t.fontSize=18;}
d.Apply(1);EditorUtility.SetDirty(h);EditorUtility.SetDirty(l);EditorUtility.SetDirty(h.Groups);EditorUtility.SetDirty(d);EditorSceneManager.MarkSceneDirty(scene);if(!EditorSceneManager.SaveScene(scene))throw new Exception("Save failed");}}finally{EditorSceneManager.RestoreSceneManagerSetup(setup);}return "Saved compact browse, placement, cost and objective controls in both scenes";}}
