using System;using System.IO;using System.Linq;using UnityEngine;using UnityEditor;using UnityEditor.Events;using UnityEditor.SceneManagement;using TMPro;using EternalSteam.OpenWorld;
public static class AuthorHud08Menu{
static void Box(RectTransform r,Vector2 anchor,Vector2 pivot,Vector2 pos,Vector2 size){r.anchorMin=r.anchorMax=anchor;r.pivot=pivot;r.anchoredPosition=pos;r.sizeDelta=size;}
static void Fill(RectTransform r){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=r.offsetMax=Vector2.zero;}
static void Bind(UnityEngine.UI.Button b,HudPauseMenu menu,string cmd){b.onClick=new UnityEngine.UI.Button.ButtonClickedEvent();UnityEventTools.AddStringPersistentListener(b.onClick,menu.Execute,cmd);}
public static string Main(){if(Application.isPlaying||EditorSceneManager.GetActiveScene().isDirty)throw new Exception("Clean Edit required");var setup=EditorSceneManager.GetSceneManagerSetup();try{foreach(var name in new[]{"StartRegionSandbox","OpenWorldSandbox"}){var scene=EditorSceneManager.OpenScene("Assets/EternalSteam/Scene/Tests/"+name+".unity");var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();foreach(var input in h.GetComponentsInChildren<TMPro.TMP_InputField>(true))input.restoreOriginalTextOnEscape=false;if(h.Sandbox.PauseMenu!=null)throw new Exception("Menu already authored");var menu=h.gameObject.AddComponent<HudPauseMenu>();menu.Hud=h;h.Sandbox.PauseMenu=menu;
var overlay=new GameObject("PauseMenuOverlay",typeof(RectTransform),typeof(UnityEngine.UI.Image),typeof(CanvasGroup));overlay.transform.SetParent(h.transform,false);Fill((RectTransform)overlay.transform);var dim=overlay.GetComponent<UnityEngine.UI.Image>();dim.color=new Color(0,0,0,.7f);dim.raycastTarget=true;menu.Overlay=overlay.GetComponent<CanvasGroup>();
var panel=h.Layout.FloatingPanels.Single(p=>p.name=="ProgressAndSave");panel.SetParent(overlay.transform,false);panel.gameObject.SetActive(true);Box(panel,Vector2.one*.5f,Vector2.one*.5f,Vector2.zero,new Vector2(580,600));panel.localScale=Vector3.one;menu.Panel=panel;menu.Content=panel.gameObject.AddComponent<CanvasGroup>();
var saved=h.Layout.FloatingPanels.Select((p,i)=>(p,size:h.Layout.FloatingSizes[i])).Where(x=>x.p!=panel).ToArray();h.Layout.FloatingPanels=saved.Select(x=>x.p).ToArray();h.Layout.FloatingSizes=saved.Select(x=>x.size).ToArray();var sections=h.Sections;int menuIndex=Array.FindIndex(sections,s=>s.Id=="menu");if(menuIndex<0)throw new Exception("Menu section missing");sections[menuIndex].Body=overlay;h.Sections=sections;
var style=h.Buttons.Single(b=>b.Id=="pause").View.GetComponentInChildren<TMP_Text>();TMP_Text Label(string name,Transform parent,string value){var t=UnityEngine.Object.Instantiate(style,parent);t.name=name;t.text=value;t.fontSize=18;t.enableAutoSizing=false;t.raycastTarget=false;t.textWrappingMode=TextWrappingModes.Normal;t.overflowMode=TextOverflowModes.Overflow;return t;}
menu.Heading=Label("PauseMenuHeading",panel,"메뉴 · 일시정지 중");Box(menu.Heading.rectTransform,new Vector2(0,1),new Vector2(0,1),new Vector2(16,-12),new Vector2(548,30));
var pause=h.Buttons.Single(b=>b.Id=="pause").View;pause.transform.SetParent(panel,false);Box((RectTransform)pause.transform,new Vector2(0,1),new Vector2(0,1),new Vector2(16,-50),new Vector2(268,40));
var close=h.Buttons.Single(b=>b.Id=="menu-close").View;Box((RectTransform)close.transform,Vector2.one,Vector2.one,new Vector2(-16,-50),new Vector2(268,40));close.GetComponentInChildren<TMP_Text>().text="돌아가기 · Esc";Bind(close,menu,"close");var scroll=panel.GetComponentInChildren<UnityEngine.UI.ScrollRect>(true);var sr=(RectTransform)scroll.transform;sr.anchorMin=Vector2.zero;sr.anchorMax=Vector2.one;sr.offsetMin=new Vector2(8,12);sr.offsetMax=new Vector2(-8,-104);
var entry=h.Buttons.Single(b=>b.Id=="menu-fold").View;entry.gameObject.SetActive(false);var hint=Label("EscapeHint",h.transform,"Esc · 메뉴");hint.alignment=TextAlignmentOptions.MidlineRight;Box(hint.rectTransform,Vector2.one,Vector2.one,new Vector2(-16,-16),new Vector2(144,36));
menu.NewGameConfirmation=h.Sections.Single(s=>s.Id=="new-game-confirmation").Body;var developerRoot=h.Sections.Single(s=>s.Id=="developer").Body;developerRoot.transform.SetParent(overlay.transform,false);developerRoot.SetActive(true);menu.Developer=h.Sections.Single(s=>s.Id=="developer-body").Body;menu.Developer.SetActive(false);
var confirm=new GameObject("LoadDiscardConfirmation",typeof(RectTransform),typeof(UnityEngine.UI.Image));confirm.transform.SetParent(overlay.transform,false);var ci=confirm.GetComponent<UnityEngine.UI.Image>();ci.sprite=panel.GetComponent<UnityEngine.UI.Image>().sprite;ci.type=UnityEngine.UI.Image.Type.Sliced;ci.color=Color.white;Box((RectTransform)confirm.transform,Vector2.one*.5f,Vector2.one*.5f,Vector2.zero,new Vector2(480,200));menu.LoadConfirmation=confirm;
var warning=Label("LoadDiscardWarning",confirm.transform,"미확정 건설·철도 작업과 저장 이후 진행을 버리고\n마지막 저장을 불러올까요?");Box(warning.rectTransform,new Vector2(0,1),new Vector2(0,1),new Vector2(16,-16),new Vector2(448,96));
foreach(var cmd in new[]{"load-confirm","load-cancel"}){var b=UnityEngine.Object.Instantiate(close,confirm.transform);b.name=cmd;Box((RectTransform)b.transform,new Vector2(0,0),Vector2.zero,new Vector2(cmd=="load-confirm"?16:248,16),new Vector2(216,44));b.GetComponentInChildren<TMP_Text>().text=cmd=="load-confirm"?"작업 폐기 후 불러오기":"돌아가기";Bind(b,menu,cmd);}confirm.SetActive(false);
foreach(var text in overlay.GetComponentsInChildren<TMP_Text>(true)){text.fontSize=18;text.enableAutoSizing=false;}
var keep=h.Layout.Texts.Select((t,i)=>(t,size:h.Layout.FontSizes[i])).Where(x=>!x.t.transform.IsChildOf(overlay.transform)).ToArray();h.Layout.Texts=keep.Select(x=>x.t).ToArray();h.Layout.FontSizes=keep.Select(x=>x.size).ToArray();overlay.SetActive(false);
EditorUtility.SetDirty(h);EditorUtility.SetDirty(h.Sandbox);EditorUtility.SetDirty(h.Layout);menu.Scroll=menu.Panel.GetComponentInChildren<UnityEngine.UI.ScrollRect>(true);menu.SaveSection=(RectTransform)h.Sections.Single(s=>s.Id=="save-controls").Body.transform;menu.ProgressSection=(RectTransform)h.Sections.Single(s=>s.Id=="map-progress").Body.transform;menu.DeveloperEntry=(RectTransform)h.Buttons.Single(b=>b.Id=="developer-fold").View.transform;EditorUtility.SetDirty(menu);EditorSceneManager.MarkSceneDirty(scene);if(!EditorSceneManager.SaveScene(scene))throw new Exception("Save failed");}}finally{EditorSceneManager.RestoreSceneManagerSetup(setup);}return "Saved Esc modal, persistent callbacks, pause/save relocation and discard prompt in both scenes";}}
