using System;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEditor;
using EternalSteam;
using EternalSteam.OpenWorld;
public static class CreateHudVisualAssets
{
 const string Dir="Assets/EternalSteam/Shared/UI/ReferenceHUD";
 static Color Gold=new Color(.76f,.57f,.28f,1),Cyan=new Color(.03f,.87f,.91f,1),Steel=new Color(.32f,.43f,.46f,1);
 static Texture2D Tex(int n){var t=new Texture2D(n,n,TextureFormat.RGBA32,false);t.SetPixels(new Color[n*n]);return t;}
 static void Rect(Texture2D t,int x,int y,int w,int h,Color c){for(int j=Math.Max(0,y);j<Math.Min(t.height,y+h);j++)for(int i=Math.Max(0,x);i<Math.Min(t.width,x+w);i++)t.SetPixel(i,j,c);}
 static void Line(Texture2D t,Vector2 a,Vector2 b,float width,Color c){for(int y=0;y<t.height;y++)for(int x=0;x<t.width;x++){var p=new Vector2(x,y);float f=Mathf.Clamp01(Vector2.Dot(p-a,b-a)/(b-a).sqrMagnitude);if(Vector2.Distance(p,a+(b-a)*f)<=width*.5f)t.SetPixel(x,y,c);}}
 static void Circle(Texture2D t,Vector2 p,float r,Color c){for(int y=0;y<t.height;y++)for(int x=0;x<t.width;x++)if(Vector2.Distance(new Vector2(x,y),p)<=r)t.SetPixel(x,y,c);}
 static void Poly(Texture2D t,Color c,params Vector2[] v){for(int y=0;y<t.height;y++)for(int x=0;x<t.width;x++){bool inside=false;for(int i=0,j=v.Length-1;i<v.Length;j=i++)if((v[i].y>y)!=(v[j].y>y)&&x<(v[j].x-v[i].x)*(y-v[i].y)/(v[j].y-v[i].y)+v[i].x)inside=!inside;if(inside)t.SetPixel(x,y,c);}}
 static Sprite Save(Texture2D t,string name,int border=0){t.Apply();string path=Dir+"/"+name+".png";File.WriteAllBytes(path,t.EncodeToPNG());UnityEngine.Object.DestroyImmediate(t);AssetDatabase.ImportAsset(path,ImportAssetOptions.ForceSynchronousImport);var i=(TextureImporter)AssetImporter.GetAtPath(path);i.textureType=TextureImporterType.Sprite;i.spriteImportMode=SpriteImportMode.Single;i.spritePixelsPerUnit=100;i.spriteBorder=new Vector4(border,border,border,border);i.alphaIsTransparency=true;i.mipmapEnabled=false;i.textureCompression=TextureImporterCompression.Uncompressed;i.filterMode=FilterMode.Bilinear;i.SaveAndReimport();return AssetDatabase.LoadAssetAtPath<Sprite>(path);}
 static void Frame(string name,Color edge,bool corner){var t=Tex(64);for(int y=2;y<62;y++)for(int x=2;x<62;x++){float shade=(float)y/64;var c=Color.Lerp(new Color(.025f,.042f,.052f,.96f),new Color(.055f,.085f,.099f,.97f),shade);t.SetPixel(x,y,c);}Rect(t,2,2,60,1,edge*.65f);Rect(t,2,61,60,1,edge);Rect(t,2,2,1,60,edge);Rect(t,61,2,1,60,edge*.7f);Rect(t,4,59,56,1,new Color(.35f,.44f,.45f,.35f));if(corner){foreach(int x in new[]{1,53})foreach(int y in new[]{1,60})Rect(t,x,y,10,2,Gold);foreach(int x in new[]{1,60})foreach(int y in new[]{1,53})Rect(t,x,y,2,10,Gold);}Save(t,name,14);}
 static void Gem(string name,Color c){var t=Tex(64);Vector2 top=new(32,56),left=new(9,43),mid=new(32,30),right=new(55,43),bottom=new(32,5);Poly(t,Color.Lerp(c,Color.white,.4f),top,left,mid,right);Poly(t,c*.7f,left,new Vector2(9,18),bottom,mid);Poly(t,c,mid,bottom,new Vector2(55,18),right);foreach(var pair in new[]{(top,left),(left,new Vector2(9,18)),(new Vector2(9,18),bottom),(bottom,new Vector2(55,18)),(new Vector2(55,18),right),(right,top),(left,mid),(mid,right),(mid,bottom)})Line(t,pair.Item1,pair.Item2,2,Color.Lerp(c,Color.white,.7f));Save(t,name);}
 static void Dial(){var t=Tex(256);var center=new Vector2(128,128);for(int y=0;y<256;y++)for(int x=0;x<256;x++){float r=Vector2.Distance(new Vector2(x,y),center);if(r>124)continue;Color c=r>121?Gold:r>116?new Color(.09f,.15f,.18f,1):r>113?Steel:y>=128?Color.Lerp(new Color(.29f,.2f,.08f),new Color(.6f,.43f,.16f),(y-128)/128f):new Color(.025f,.058f,.083f);t.SetPixel(x,y,c);}Line(t,new Vector2(16,128),new Vector2(240,128),2,Gold);for(int i=0;i<12;i++){float a=i*Mathf.PI/6;Line(t,center+new Vector2(Mathf.Cos(a),Mathf.Sin(a))*101,center+new Vector2(Mathf.Cos(a),Mathf.Sin(a))*110,2,new Color(.77f,.82f,.78f,1));}var sun=new Vector2(128,186);Circle(t,sun,12,new Color(1,.78f,.3f));for(int i=0;i<8;i++){float a=i*Mathf.PI/4;Line(t,sun+new Vector2(Mathf.Cos(a),Mathf.Sin(a))*17,sun+new Vector2(Mathf.Cos(a),Mathf.Sin(a))*22,2,Gold);}Circle(t,new Vector2(128,70),16,new Color(.68f,.79f,.85f));Circle(t,new Vector2(137,77),14,new Color(.025f,.058f,.083f));Circle(t,center,6,Color.white);Save(t,"ClockFace");}
 static void Glyph(string name){var t=Tex(64);if(name=="Energy")Poly(t,Gold,new(35,60),new(14,29),new(29,29),new(22,4),new(51,38),new(34,38));else if(name=="Shield"){Poly(t,Gold,new(32,58),new(11,47),new(13,21),new(32,5),new(51,21),new(53,47));Poly(t,new Color(.05f,.1f,.12f),new(32,50),new(32,13),new(20,25),new(18,43));}else if(name=="Tools"){Line(t,new(15,12),new(43,43),10,Steel);Circle(t,new(45,45),13,Steel);Poly(t,Color.clear,new(47,63),new(35,48),new(42,40),new(61,50));Circle(t,new(15,12),3,Color.clear);}else if(name=="Install"){Rect(t,14,8,36,5,Steel);Rect(t,20,15,24,35,Steel);Rect(t,25,20,4,25,new Color(.02f,.05f,.08f));Rect(t,36,20,4,25,new Color(.02f,.05f,.08f));Rect(t,24,50,16,7,Steel);}else{for(int x=14;x<50;x+=20)for(int y=14;y<50;y+=20)Rect(t,x,y,14,14,Steel);}Save(t,name);}
 static void Thumbnail(GameObject prefab,string name){string path=Dir+"/"+name+".png";var preview=new PreviewRenderUtility();GameObject instance=null;try{instance=UnityEngine.Object.Instantiate(prefab);preview.AddSingleGO(instance);foreach(var c in instance.GetComponentsInChildren<Collider>())c.enabled=false;var renderers=instance.GetComponentsInChildren<MeshRenderer>().Where(r=>r.enabled).ToArray();if(renderers.Length==0)throw new Exception("No renderer: "+prefab.name);var b=new Bounds();bool first=true;foreach(var r in renderers){var mf=r.GetComponent<MeshFilter>();if(mf==null||mf.sharedMesh==null)continue;var mb=mf.sharedMesh.bounds;for(int k=0;k<8;k++){var v=r.transform.TransformPoint(mb.center+Vector3.Scale(mb.extents,new Vector3((k&1)==0?-1:1,(k&2)==0?-1:1,(k&4)==0?-1:1)));if(first){b=new Bounds(v,Vector3.zero);first=false;}else b.Encapsulate(v);}}foreach(var r in instance.GetComponentsInChildren<LineRenderer>())r.enabled=false;preview.BeginPreview(new Rect(0,0,256,256),GUIStyle.none);preview.camera.orthographic=true;preview.camera.orthographicSize=Mathf.Max(b.size.x,b.size.y,b.size.z)*.78f;preview.camera.nearClipPlane=.01f;preview.camera.farClipPlane=200;preview.camera.transform.position=b.center+new Vector3(1,1.05f,-1.5f).normalized*30;preview.camera.transform.LookAt(b.center);preview.camera.ResetWorldToCameraMatrix();preview.camera.ResetProjectionMatrix();preview.camera.aspect=1;preview.camera.rect=new Rect(0,0,1,1);preview.camera.clearFlags=CameraClearFlags.SolidColor;preview.camera.backgroundColor=Color.clear;preview.lights[0].intensity=2.5f;preview.lights[0].transform.rotation=Quaternion.Euler(35,30,0);preview.lights[1].intensity=1.4f;preview.ambientColor=new Color(.5f,.55f,.6f);preview.Render(true,false);var rt=preview.EndPreview() as RenderTexture;var previous=RenderTexture.active;try{RenderTexture.active=rt;var tex=Tex(rt.width);tex.ReadPixels(new Rect(0,0,rt.width,rt.height),0,0);Save(tex,name);}finally{RenderTexture.active=previous;}}finally{preview.Cleanup();}}
 public static string Main(){if(EditorApplication.isPlaying)throw new Exception("Stop Play");Directory.CreateDirectory(Dir);Frame("Panel",Steel,true);Frame("Card",Steel,false);Frame("Selected",Cyan,false);Frame("TabActive",Gold,false);Dial();Gem("Nexus",Cyan);var names=new[]{"copper","iron","nanometal","plasma_ore","titanium","tungsten","uranium"};var colors=new[]{new Color(.75f,.35f,.17f),new Color(.58f,.68f,.75f),new Color(.32f,.65f,.8f),new Color(.51f,.28f,.94f),new Color(.66f,.73f,.7f),new Color(.27f,.33f,.34f),new Color(.55f,.77f,.12f)};for(int i=0;i<names.Length;i++)Gem(names[i],colors[i]);foreach(string n in new[]{"Energy","Shield","Tools","Install","All"})Glyph(n);int count=0;foreach(var path in AssetDatabase.FindAssets("t:Prefab",new[]{"Assets/EternalSteam/Content/Buildings"}).Select(AssetDatabase.GUIDToAssetPath)){var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(path);Thumbnail(prefab,"Building_"+Path.GetFileNameWithoutExtension(path));count++;}AssetDatabase.SaveAssets();return "Saved frame, clock, resource sprites and "+count+" prefab thumbnails";}
}
