using System;using System.Linq;using System.Collections;using System.IO;using UnityEngine;using UnityEngine.EventSystems;using UnityEngine.InputSystem;using UnityEngine.InputSystem.LowLevel;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public sealed class Hud08ENativeObserver:MonoBehaviour{
const string Root="Docs/Measurements/2026-10-03-hud-08e/";JArray events=new JArray();Keyboard k;
IEnumerator Start(){yield return new WaitForSecondsRealtime(.5f);var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();var r=h.Sandbox.RailwayHud.Resource;if(!r.gameObject.activeInHierarchy)throw new Exception("Native field must be visible");EventSystem.current.SetSelectedGameObject(r.gameObject);r.ActivateInputField();UnityEditor.EditorWindow.GetWindow(typeof(UnityEditor.EditorWindow).Assembly.GetType("UnityEditor.GameView")).Focus();yield return null;File.WriteAllText(Root+"native-ready.txt",r.isFocused?"READY":"NO FOCUS");}
void OnEnable(){k=Keyboard.current;k.onIMECompositionChange+=Composition;k.onTextInput+=Text;}void OnDisable(){if(k!=null){k.onIMECompositionChange-=Composition;k.onTextInput-=Text;}}void Composition(IMECompositionString s){events.Add(new JObject{{"kind","composition"},{"value",s.ToString()}});Flush();}void Text(char c){events.Add(new JObject{{"kind","text"},{"value",c.ToString()}});Flush();}void Flush(){File.WriteAllText(Root+"native-events.json",events.ToString());}
}
public static class ObserveHud08ENative{
public static string Setup(){if(!Application.isPlaying)throw new Exception("Play required");var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();h.Input.Cancel();var v=h.Sandbox.RailwayHud.GetComponent<RailwayOverview>();h.Groups.Select(true);v.Execute("open");v.Apply();v.Rows[0].onClick.Invoke();v.Execute("cargo");v.Railway.Resource.SetTextWithoutNotify("");EventSystem.current.SetSelectedGameObject(v.Railway.Resource.gameObject);v.Railway.Resource.ActivateInputField();new GameObject("Native IME observer",typeof(Hud08ENativeObserver)).hideFlags=HideFlags.HideAndDontSave;UnityEditor.EditorWindow.GetWindow(typeof(UnityEditor.EditorWindow).Assembly.GetType("UnityEditor.GameView")).Focus();return "Native resource input focused";}
public static object State(){var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();var r=h.Sandbox.RailwayHud.Resource;var data=new JObject{{"text",r.text},{"focused",r.isFocused},{"composing",h.Sandbox.PauseMenu.Composing},{"menuOpen",h.Sandbox.PauseMenu.IsOpen},{"construction",h.Groups.ConstructionSelected}};File.WriteAllText("Docs/Measurements/2026-10-03-hud-08e/native-state.json",data.ToString());return data.ToString();}
public static string Cleanup(){var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();h.Sandbox.PauseMenu.SetOpen(false);var r=h.Sandbox.RailwayHud.Resource;r.SetTextWithoutNotify("iron");r.DeactivateInputField();EventSystem.current.SetSelectedGameObject(null);foreach(var p in UnityEngine.Object.FindObjectsByType<GameObject>(FindObjectsSortMode.None).Where(p=>p.name=="Native IME observer"))UnityEngine.Object.Destroy(p);return "Native input restored";}}
