using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditorInternal;using UnityEditor.SceneManagement;using Unity.Profiling;using Newtonsoft.Json.Linq;using EternalSteam.OpenWorld;
public static class ProfileGamePerformance {
 public const string Root="Docs/Measurements/2026-10-03-performance/";
 public static string Setup(){if(Application.isPlaying||EditorSceneManager.GetActiveScene().isDirty)throw new Exception("Clean Edit required");Directory.CreateDirectory(Root);File.WriteAllText(Root+"editor-original.json",new JObject{{"scene",EditorSceneManager.GetActiveScene().path},{"runInBackground",Application.runInBackground},{"profilerEnabled",ProfilerDriver.enabled}}.ToString());Environment.SetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT",Path.GetFullPath(Root+"isolated-save"));Application.runInBackground=true;return "ready";}
 public static string Capture(string label,bool construction=false,bool editorProfile=false){if(!Application.isPlaying)throw new Exception("Play required");var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();h.Groups.Select(construction);if(h.Sandbox.Persistence!=null)h.Sandbox.Persistence.Automatic=false;var p=new GameObject("PerformanceMeasurement").AddComponent<GamePerformanceProbe>();p.Label=label;p.EditorProfile=editorProfile;return "Capturing 240 frames after 120 frame warmup";}
 public static string Restore(){if(Application.isPlaying)throw new Exception("Stop Play first");Environment.SetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT",null);var old=JObject.Parse(File.ReadAllText(Root+"editor-original.json"));Application.runInBackground=(bool)old["runInBackground"];ProfilerDriver.enabled=(bool)old["profilerEnabled"];return "Restored measurement settings";}
}
public sealed class GamePerformanceProbe:MonoBehaviour {
 public string Label;public bool EditorProfile;IEnumerator Start(){ProfilerDriver.enabled=true;ProfilerDriver.profileEditor=EditorProfile;for(int i=0;i<120;i++)yield return null;var frames=new List<double>();var alloc=new List<long>();var batches=new List<long>();using(var gc=ProfilerRecorder.StartNew(ProfilerCategory.Memory,"GC Allocated In Frame"))using(var draw=ProfilerRecorder.StartNew(ProfilerCategory.Render,"Draw Calls Count")){for(int i=0;i<240;i++){yield return null;frames.Add(Time.unscaledDeltaTime*1000.0);alloc.Add(gc.LastValue);batches.Add(draw.LastValue);}}
 var sums=new Dictionary<string,double>();var maxima=new Dictionary<string,double>();int last=ProfilerDriver.lastFrameIndex,first=Math.Max(ProfilerDriver.firstFrameIndex,last-199),valid=0;for(int f=first;f<=last;f++){using(var data=ProfilerDriver.GetRawFrameDataView(f,0)){if(!data.valid)continue;valid++;for(int n=0;n<data.sampleCount;n++){string name=data.GetSampleName(n);double ms=data.GetSampleTimeMs(n);if(!sums.ContainsKey(name)){sums[name]=0;maxima[name]=0;}sums[name]+=ms;maxima[name]=Math.Max(maxima[name],ms);}}}
 var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();var report=new JObject{{"label",Label},{"scene",EditorSceneManager.GetActiveScene().name},{"unity",Application.unityVersion},{"device",SystemInfo.deviceModel},{"gpu",SystemInfo.graphicsDeviceName},{"width",Screen.width},{"height",Screen.height},{"construction",h.Groups.ConstructionSelected},{"enemies",h.Sandbox.Enemies.Alive},{"defeated",h.Sandbox.Content.Defeated},{"simulationPaused",h.Sandbox.SimulationPaused},{"frameCount",frames.Count},{"profileFrames",valid},{"frameMs",Stats(frames)},{"gcBytes",Stats(alloc.Select(v=>(double)v))},{"drawCalls",Stats(batches.Select(v=>(double)v))},{"samples",new JArray(sums.OrderByDescending(p=>p.Value).Take(100).Select(p=>new JObject{{"name",p.Key},{"inclusiveMeanMs",p.Value/Math.Max(1,valid)},{"maxSampleMs",maxima[p.Key]}}))}};File.WriteAllText(ProfileGamePerformance.Root+Label+".json",report.ToString());ProfilerDriver.enabled=false;Destroy(gameObject);}
 static JObject Stats(IEnumerable<double> source){var a=source.OrderBy(x=>x).ToArray();return new JObject{{"mean",a.Average()},{"median",a[a.Length/2]},{"p95",a[(int)(a.Length*.95)]},{"max",a.Last()}};}
}
