public sealed class ResponsiveMatrixProbe:MonoBehaviour{
 System.Collections.IEnumerator Start(){var r=VerifyResponsiveMatrix.Run();while(true){bool next;try{next=r.MoveNext();}catch(Exception e){File.WriteAllText("Docs/Measurements/2026-10-02-train-hud-integration/responsive-matrix-status.txt","FAIL "+e);break;}if(!next)break;yield return r.Current;}Destroy(gameObject);}
}
public static class VerifyResponsiveMatrix{
 const string Root="Docs/Measurements/2026-10-02-train-hud-integration/";
 public static string Main(){File.WriteAllText(Root+"responsive-matrix-status.txt","RUNNING");var go=new GameObject("Responsive product verification");go.hideFlags=HideFlags.HideAndDontSave;go.AddComponent<ResponsiveMatrixProbe>();return "Queued seven actual GameView resolutions";}
 static void Resolution(int width,int height){var asm=typeof(EditorWindow).Assembly;var t=asm.GetType("UnityEditor.GameViewSizes");var singleton=typeof(ScriptableSingleton<>).MakeGenericType(t);var sizes=singleton.GetProperty("instance").GetValue(null);var group=t.GetMethod("GetGroup").Invoke(sizes,new object[]{0});var gt=group.GetType();int count=(int)gt.GetMethod("GetTotalCount").Invoke(group,null),index=-1;for(int i=0;i<count;i++){var size=gt.GetMethod("GetGameViewSize").Invoke(group,new object[]{i});var st=size.GetType();if((int)st.GetProperty("width").GetValue(size)==width&&(int)st.GetProperty("height").GetValue(size)==height){index=i;break;}}if(index<0){var st=asm.GetType("UnityEditor.GameViewSize");var kind=asm.GetType("UnityEditor.GameViewSizeType");var size=Activator.CreateInstance(st,new object[]{Enum.ToObject(kind,1),width,height,"HUD "+width+"x"+height});gt.GetMethod("AddCustomSize").Invoke(group,new[]{size});index=count;}var vt=asm.GetType("UnityEditor.GameView");var view=EditorWindow.GetWindow(vt);vt.GetProperty("selectedSizeIndex",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.Public|System.Reflection.BindingFlags.NonPublic).SetValue(view,index);view.Focus();view.Repaint();}
 static void Capture(string name){var t=typeof(EditorWindow).Assembly.GetType("UnityEditor.GameView");var view=Resources.FindObjectsOfTypeAll(t).Single();var rt=(RenderTexture)t.GetField("m_RenderTexture",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).GetValue(view);var old=RenderTexture.active;var pixels=new Texture2D(rt.width,rt.height,TextureFormat.RGB24,false);try{RenderTexture.active=rt;pixels.ReadPixels(new Rect(0,0,rt.width,rt.height),0,0);pixels.Apply();if(SystemInfo.graphicsUVStartsAtTop){var data=pixels.GetPixels();var flipped=new Color[data.Length];for(int y=0;y<rt.height;y++)Array.Copy(data,y*rt.width,flipped,(rt.height-1-y)*rt.width,rt.width);pixels.SetPixels(flipped);pixels.Apply();}File.WriteAllBytes(Root+name+".png",pixels.EncodeToPNG());}finally{RenderTexture.active=old;UnityEngine.Object.Destroy(pixels);}}
 public static System.Collections.IEnumerator Run(){
 foreach(var size in new[]{new Vector2Int(800,600),new Vector2Int(1024,768),new Vector2Int(1280,720),new Vector2Int(1920,1080),new Vector2Int(2560,1080),new Vector2Int(3840,1080),new Vector2Int(3840,2160)}){
  Resolution(size.x,size.y);yield return null;yield return null;yield return null;
  var s=UnityEngine.Object.FindFirstObjectByType<OpenWorldSandbox>();s.Persistence.Automatic=false;s.Clock.Paused=true;s.Persistence.ContinueSaved();yield return null;yield return null;yield return null;
  var check=VerifyIntegratedPresentation.Play();while(check.MoveNext())yield return check.Current;
  s=UnityEngine.Object.FindFirstObjectByType<OpenWorldSandbox>();s.RailwayHud.Execute("open");s.RailwayHud.Execute("row:0");yield return null;yield return null;Capture("responsive-railway-"+size.x+"x"+size.y);
  var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();h.GetComponent<GameplayHudWorkspace>().Construction();yield return null;yield return null;h.CatalogLayout.GetComponentInParent<ScrollRect>().horizontalNormalizedPosition=1;yield return null;Capture("responsive-construction-"+size.x+"x"+size.y);h.Input.Cancel();
  File.AppendAllText(Root+"responsive-matrix-progress.txt","PASS "+size.x+"x"+size.y+"\n");
 }
 File.WriteAllText(Root+"responsive-matrix-status.txt","PASS all 7 resolutions; construction, selection, route detail/draft, popups, viewport, input and animated consist");}
}
