using System;using System.IO;using System.Linq;using System.Collections;using UnityEngine;using EternalSteam;using EternalSteam.OpenWorld;using EternalSteam.Railway;using Newtonsoft.Json.Linq;
public sealed class Hud06CProbe:MonoBehaviour{
const string Root="Docs/Measurements/2026-10-02-hud-06c/";RailwayOverview v;RailwayEditorPanel e;
void Check(bool ok,string why){if(!ok)throw new Exception(why);}
void Click(string cmd){v.Apply();var b=e.Bindings.Single(b=>b.Command==cmd).Button;Check(b.gameObject.activeInHierarchy&&b.interactable,"Visible enabled "+cmd);b.onClick.Invoke();v.Apply();}
void Match(){e.Refresh();foreach(var b in e.Bindings.Where(b=>b.Button.gameObject.activeInHierarchy))Check(b.Button.interactable==v.Railway.CanExecute(b.Command,out _),"Command parity "+b.Command);}
IEnumerator Start(){File.WriteAllText(Root+"play-status.txt","RUNNING");var it=Verify();while(true){bool next;try{next=it.MoveNext();}catch(Exception ex){File.WriteAllText(Root+"play-status.txt","FAIL "+ex);break;}if(!next)break;yield return it.Current;}Destroy(gameObject);}
IEnumerator Verify(){var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();v=h.Sandbox.RailwayHud.GetComponent<RailwayOverview>();e=v.Editor;var rail=v.Railway;var c=h.Sandbox.Content;var n=c.Railway.Network;var input=h.Sandbox.GetComponent<OpenWorldInput>();h.Groups.Select(true);yield return new WaitForSecondsRealtime(.35f);var stations=n.Stations.OrderBy(b=>b.Cell.x).ToArray();var a=stations[0];var b=stations[1];var payer=c.Bases.SelectedBaseId;var bank=c.Inventories.Available(payer);double iron=bank.Amount("iron");int count=c.GroundWorld.Buildings.Count;
v.Execute("connect");Check(e.Current==RailwayEditorPanel.Screen.Connection&&v.Root.gameObject.activeInHierarchy&&!v.Legacy.blocksRaycasts,"New connection presentation");Check(input.ClickWorld(b.Position),"World destination click");Click("connection-preview");yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Root+"connection-quote.png");Check(e.Description.text.Contains("지불 기지")&&e.Description.text.Contains("신규"),"Path cost payer summary");Check(n.Connections.Count==0&&c.GroundWorld.Buildings.Count==count&&bank.Amount("iron")==iron,"Preview has no mutation");Match();Click("connection-cancel");Check(!rail.HasDraft&&bank.Amount("iron")==iron,"Cancel preview no cost");v.Execute("connect");input.ClickWorld(b.Position);Click("connection-preview");
bank.Withdraw("iron",iron);Match();Check(!rail.CanExecute("connection-confirm",out _),"Insufficient stock disables confirm");e.Execute("connection-confirm");Check(n.Connections.Count==0&&c.GroundWorld.Buildings.Count==count,"Rejected callback no construction");bank.Deposit("iron",iron);var other=c.Bases.Bases.Keys.First(id=>id!=payer);Check(c.Bases.Select(other),"Switch payer fixture");Match();Check(!rail.CanExecute("connection-confirm",out _),"Payer change invalidates quote");e.Execute("connection-confirm");Check(n.Connections.Count==0&&bank.Amount("iron")==iron,"Payer reject no charge");c.Bases.Select(payer);Click("connection-preview");int tracks=c.GroundWorld.Buildings.Count(x=>x.Module<RailFacility>()?.Kind==RailFacilityKind.Track);Click("connection-confirm");int added=c.GroundWorld.Buildings.Count(x=>x.Module<RailFacility>()?.Kind==RailFacilityKind.Track)-tracks;Check(n.Connections.Count==1&&bank.Amount("iron")==iron-added&&added>0,"Only new track charged");double paid=bank.Amount("iron");e.Execute("connection-confirm");Check(bank.Amount("iron")==paid&&n.Connections.Count==1,"No duplicate connection payment");
v.Execute("new");Check(input.ClickWorld(b.Position),"Add destination via map");Click("add");var selection=rail.SelectedDraftStationId;h.Groups.Select(false);yield return new WaitForSecondsRealtime(.35f);h.Groups.Select(true);yield return new WaitForSecondsRealtime(.35f);Check(rail.HasDraft&&rail.SelectedDraftStationId==selection&&e.Root.gameObject.activeInHierarchy,"Group retains route draft");Click("validate");Check(e.Current==RailwayEditorPanel.Screen.Confirm,"Confirm stage");yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Root+"new-route-confirm.png");Click("cancel");Check(e.Current==RailwayEditorPanel.Screen.Discard,"Discard confirmation");Click("keep");Check(e.Current==RailwayEditorPanel.Screen.Confirm,"Keep confirmation draft");Click("commit");Check(n.Routes.Count==1&&!rail.HasDraft,"Single stopped route created");e.Execute("commit");Check(n.Routes.Count==1,"No duplicate train");var r=n.Routes.Single();string train=r.trainId;var occupied=r.stops[r.train.stop].stationId;
v.Execute("edit");e.SelectPage(0);Click("draft-row:1");var chosen=rail.SelectedDraftStationId;Click("up");Check(rail.SelectedDraftStationId==chosen,"Order preserves selected identity");Click("down");Click("first");Click("validate");Click("commit");Check(r.trainId==train&&r.stops[r.train.stop].stationId==occupied&&r.stops[0].stationId==chosen,"Reorder preserves physical train station");
v.Execute("edit");e.SelectPage(0);Click("draft-row:"+r.train.stop);Check(!rail.CanExecute("remove",out _),"Occupied stop cannot be removed");Click("draft-row:"+(1-r.train.stop));Click("remove");Check(!rail.CanExecute("validate",out _),"One stop cannot validate");Click("cancel");Click("discard");Check(r.stops.Count==2,"Discard leaves actual route unchanged");
rail.Resource.SetTextWithoutNotify("iron");rail.Load.SetTextWithoutNotify("0");rail.Unload.SetTextWithoutNotify("0");rail.Execute("configure");v.Execute("fuel");v.Execute("start");for(int i=0;i<60&&!r.train.segmentPaid;i++)c.Railway.Tick(.25);Check(r.train.segmentPaid,"Moving paid leg");v.Execute("edit");e.SelectPage(0);Click("draft-row:0");Check(!rail.CanExecute("down",out _)&&!rail.CanExecute("remove",out _),"Pending first station protected");Click("validate");Click("commit");Check(n.HasPending(r),"Moving revision queued");double fuel=r.train.fuel;v.Execute("cancel-pending");Check(!n.HasPending(r)&&r.train.fuel==fuel&&r.train.segmentPaid,"Cancel preserves paid active leg");v.Execute("edit");Click("validate");Click("commit");var snapshot=n.Capture();File.WriteAllText(Root+"pending-snapshot.json",JsonUtility.ToJson(snapshot));n.Restore(JsonUtility.FromJson<RailwayNetwork.Snapshot>(JsonUtility.ToJson(snapshot)));r=n.Routes.Single();Check(n.HasPending(r),"Pending snapshot restored");int rev=r.revision;n.Stop(r);c.Railway.Tick(r.CurrentLeg.cells.Count-r.train.progress);Check(r.revision==rev+1&&!n.HasPending(r)&&r.trainId==train&&r.train.fuel==fuel,"Pending applies at original first station without repaying leg");v.Execute("open");v.Apply();v.Rows[0].onClick.Invoke();
File.WriteAllText(Root+"play-result.json",new JObject{{"result","PASS"},{"previewAndCancelNoMutation",true},{"payerAndInsufficientGuards",true},{"newTrackCostOnce",true},{"createConfirmKeepNoDuplicate",true},{"groupDraftPreserved",true},{"reorderAndDiscard",true},{"occupiedAndMovingAnchorProtected",true},{"pendingCancelAndSnapshotApply",true},{"researchExperiment",false}}.ToString());File.WriteAllText(Root+"play-status.txt","PASS");}
}
public static class VerifyHud06CPlay{public static string Main(){if(!Application.isPlaying||!(Environment.GetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT")??"").Contains("hud-06c"))throw new Exception("Isolated Play required");new GameObject("Railway editor verification",typeof(Hud06CProbe)).hideFlags=HideFlags.HideAndDontSave;return "Queued editor flow verification";}}
