using UnityEditor;using System.Reflection;using System;using System.IO;using System.Linq;using System.Collections;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public sealed class Hud07EditorMatrixProbe:MonoBehaviour{
const string Root="Docs/Measurements/2026-10-03-hud-08e/editor/";RailwayOverview v;RailwayEditorPanel e;JArray results=new JArray();void Check(bool ok,string why){if(!ok)throw new Exception(why);}
void Pointer(Selectable b){var caption=b.GetComponentInChildren<TMPro.TMP_Text>();if(caption!=null){caption.ForceMeshUpdate();Check(caption.textInfo.characterInfo.Take(caption.textInfo.characterCount).Any(c=>c.isVisible),"Button caption visible "+b.name);}var corners=new Vector3[4];((RectTransform)b.transform).GetWorldCorners(corners);foreach(var c in corners){var p=RectTransformUtility.WorldToScreenPoint(null,c);Check(p.x>=-1&&p.y>=-1&&p.x<=Screen.width+1&&p.y<=Screen.height+1,"Bounds "+b.name);}var data=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(null,(corners[0]+corners[2])*.5f)};var hits=new System.Collections.Generic.List<RaycastResult>();v.Hud.Raycaster.Raycast(data,hits);Check(hits.Count>0&&(hits[0].gameObject==b.gameObject||hits[0].gameObject.transform.IsChildOf(b.transform)),"Pointer "+b.name+" top="+(hits.Count>0?hits[0].gameObject.name:"none"));}
IEnumerator Start(){File.WriteAllText(Root+"resolution-status.txt","RUNNING");var stack=new System.Collections.Generic.Stack<IEnumerator>();stack.Push(Verify());while(stack.Count>0){bool next;object current=null;try{next=stack.Peek().MoveNext();if(next)current=stack.Peek().Current;}catch(Exception ex){File.WriteAllText(Root+"resolution-status.txt","FAIL "+ex);break;}if(!next){stack.Pop();continue;}if(current is IEnumerator nested)stack.Push(nested);else yield return current;}Destroy(gameObject);}
IEnumerator Capture(string mode,Vector2Int size){v.Apply();yield return null;yield return new WaitForEndOfFrame();Canvas.ForceUpdateCanvases();var scroll=e.Scroll.GetComponent<ScrollRect>();scroll.verticalNormalizedPosition=1;yield return new WaitForEndOfFrame();Pointer(v.Close);foreach(var text in e.Root.GetComponentsInChildren<TMPro.TMP_Text>(true))Check(Mathf.Abs(text.fontSize*text.transform.lossyScale.x-18)<.1f,"Effective font "+text.name);var corners=new Vector3[4];v.Root.GetWorldCorners(corners);Check(corners[0].x>=Screen.width*.35f,"Map space retained");var hits=new System.Collections.Generic.List<RaycastResult>();v.Hud.Raycaster.Raycast(new PointerEventData(EventSystem.current){position=new Vector2(100,Screen.height*.5f)},hits);Check(hits.Count==0,"Map input left clear: "+string.Join(",",hits.Select(h=>h.gameObject.name)));ScreenCapture.CaptureScreenshot(Root+$"editor-{size.x}x{size.y}-{mode}-top.png");foreach(var b in e.Bindings.Where(b=>b.Button.gameObject.activeInHierarchy)){if(!b.Footer){var rt=(RectTransform)b.Button.transform;float center=-scroll.content.InverseTransformPoint(rt.TransformPoint(rt.rect.center)).y;float range=scroll.content.rect.height-scroll.viewport.rect.height;scroll.verticalNormalizedPosition=range<=0?1:1-Mathf.Clamp01((center-scroll.viewport.rect.height*.5f)/range);yield return null;yield return new WaitForEndOfFrame();}Pointer(b.Button);}if(e.Tabs.gameObject.activeInHierarchy){Pointer(e.Stations);Pointer(e.Diagnostics);}scroll.verticalNormalizedPosition=0;yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Root+$"editor-{size.x}x{size.y}-{mode}-bottom.png");results.Add(new JObject{{"width",size.x},{"height",size.y},{"mode",mode},{"allVisibleCommandsReachable",true},{"mapInputClear",true},{"fontPixels",18}});}
IEnumerator Verify(){v=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>().Sandbox.RailwayHud.GetComponent<RailwayOverview>();e=v.Editor;v.Hud.Groups.Select(true);foreach(var size in new[]{new Vector2Int(800,600),new Vector2Int(1024,768),new Vector2Int(1280,720),new Vector2Int(1920,1080),new Vector2Int(2560,1080),new Vector2Int(3840,1080),new Vector2Int(3840,2160)}){SetHudReviewResolution.Main(size.x,size.y);yield return new WaitForSecondsRealtime(.4f);e.SelectPage(0);yield return Capture("stations",size);e.SelectPage(1);yield return Capture("issues",size);e.Execute("map-arrival");v.Railway.Execute("port:0");e.Execute("validate");Check(e.Current==RailwayEditorPanel.Screen.Confirm,"Confirmed valid legacy route");yield return Capture("confirm",size);e.Execute("cancel");Check(e.Current==RailwayEditorPanel.Screen.Discard,"Discard prompt");yield return Capture("discard",size);e.Execute("discard");v.Execute("connect");e.Execute("connection-preview");yield return Capture("connection",size);e.Execute("connection-cancel");v.Execute("open");v.Apply();v.Rows[0].onClick.Invoke();v.Execute("edit");e.SelectPage(1);e.Execute("map-arrival");v.Railway.Execute("port:1");}
SetHudReviewResolution.Main(2560,1440);File.WriteAllText(Root+"resolutions.json",results.ToString());File.WriteAllText(Root+"resolution-status.txt","PASS");}}
public static class VerifyHud08EEditorResolutions{public static string Main(){if(!Application.isPlaying||!(Environment.GetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT")??"").Contains("hud-08e"))throw new Exception("Isolated Play required");new GameObject("Railway editor resolution verification",typeof(Hud07EditorMatrixProbe)).hideFlags=HideFlags.HideAndDontSave;return "Queued five-state resolution checks";}}

public static class SetHudReviewResolution
{
 public static string Main(int width=1920,int height=1080)
 {
  var assembly=typeof(EditorWindow).Assembly;var sizesType=assembly.GetType("UnityEditor.GameViewSizes");var singleton=typeof(ScriptableSingleton<>).MakeGenericType(sizesType);var sizes=singleton.GetProperty("instance").GetValue(null);
  var group=sizesType.GetMethod("GetGroup").Invoke(sizes,new object[]{0});var gt=group.GetType();int count=(int)gt.GetMethod("GetTotalCount").Invoke(group,null),index=-1;
  for(int i=0;i<count;i++){var size=gt.GetMethod("GetGameViewSize").Invoke(group,new object[]{i});var t=size.GetType();if((int)t.GetProperty("width").GetValue(size)==width&&(int)t.GetProperty("height").GetValue(size)==height){index=i;break;}}
  if(index<0){var type=assembly.GetType("UnityEditor.GameViewSize");var kind=assembly.GetType("UnityEditor.GameViewSizeType");var size=Activator.CreateInstance(type,new object[]{Enum.ToObject(kind,1),width,height,"HUD review "+width+"x"+height});gt.GetMethod("AddCustomSize").Invoke(group,new[]{size});index=count;}
  var viewType=assembly.GetType("UnityEditor.GameView");var view=EditorWindow.GetWindow(viewType);if(!SessionState.GetBool("HudReview.HasOriginal",false)){SessionState.SetInt("HudReview.SizeIndex",(int)viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).GetValue(view));SessionState.SetBool("HudReview.HasOriginal",true);}
  viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).SetValue(view,index);view.Show();view.Focus();view.Repaint();return width+"x"+height;
 }
}
