using System;using System.IO;using System.Linq;using System.Collections;using UnityEngine;using EternalSteam;using EternalSteam.OpenWorld;using EternalSteam.Railway;using Newtonsoft.Json.Linq;
public sealed class Hud06BProbe:MonoBehaviour{
const string Root="Docs/Measurements/2026-10-02-hud-06b/";RailwayOverview v;RailwayServicePanel s;
void Check(bool ok,string why){if(!ok)throw new Exception(why);}
UnityEngine.UI.Button B(string cmd)=>s.Actions.Single(a=>a.Command==cmd).Button;
void Click(string cmd){s.Refresh();Check(B(cmd).interactable,"Enabled "+cmd);B(cmd).onClick.Invoke();v.Apply();}
void Match(){s.Refresh();foreach(var a in s.Actions)Check(a.Button.interactable==v.Railway.CanExecute(a.Command,out _),"Command parity "+a.Command);}
IEnumerator Start(){File.WriteAllText(Root+"play-status.txt","RUNNING");var it=Verify();while(true){bool next;try{next=it.MoveNext();}catch(Exception e){File.WriteAllText(Root+"play-status.txt","FAIL "+e);break;}if(!next)break;yield return it.Current;}Destroy(gameObject);}
IEnumerator Verify(){var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();v=h.Sandbox.RailwayHud.GetComponent<RailwayOverview>();s=v.Services;var rail=v.Railway;var c=h.Sandbox.Content;var n=c.Railway.Network;var r=n.Routes.Single();h.Groups.Select(true);yield return new WaitForSecondsRealtime(.35f);v.Apply();v.Rows[0].onClick.Invoke();v.Execute("cargo");yield return null;Check(s.Cargo.gameObject.activeInHierarchy&&!rail.Resource.readOnly,"First resource editable");
rail.Resource.SetTextWithoutNotify("iron");foreach(var invalid in new[]{"-1","1001","NaN","bad"}){rail.Load.SetTextWithoutNotify(invalid);Match();Check(!B("configure").interactable,"Invalid quantity "+invalid);}rail.Load.SetTextWithoutNotify("30");rail.Unload.SetTextWithoutNotify("0");Click("configure");yield return null;Check(r.train.resource=="iron"&&r.stops[0].load==30&&rail.Resource.readOnly,"First cargo assigned and locked");
rail.Load.SetTextWithoutNotify("7");h.Groups.Select(false);yield return new WaitForSecondsRealtime(.35f);h.Groups.Select(true);yield return new WaitForSecondsRealtime(.35f);Check(v.ShowingCargo&&rail.Load.text=="7","Group retains draft");s.Return.onClick.Invoke();v.Execute("defense");yield return null;s.Return.onClick.Invoke();v.Execute("cargo");Check(rail.Load.text=="7","Overview and defense return retain draft");Click("configure");Click("next-stop");rail.Load.SetTextWithoutNotify("0");rail.Unload.SetTextWithoutNotify("12");Click("configure");Check(r.stops[0].load==7&&r.stops[1].unload==12,"Selected station only apply");
s.Return.onClick.Invoke();v.Execute("defense");yield return null;Match();Check(s.Defense.gameObject.activeInHierarchy&&rail.ShowingArmament,"Defense entry");Check(c.MainBase.Module<IUpgradeControl>().TryUpgrade(out var upgradeReason),upgradeReason);for(int i=0;i<3&&!c.Railway.Defense.Choices(r).Any();i++)Click("weapon-shape");Check(c.Railway.Defense.Choices(r).Any(),"Unlocked defense candidate");var station=n.Station(r.stops[r.train.stop].stationId);var bank=c.Inventories.Available(station.OwnerBaseId);Check(!bank.InfiniteResources,"Real cost fixture");var before=bank.Amount("iron");Click("weapon-install");Check(bank.Amount("iron")==before-TrainArmament.InstallIron&&!string.IsNullOrEmpty(r.train.armament.definition),"Install charged once");s.Execute("weapon-install");Check(bank.Amount("iron")==before-TrainArmament.InstallIron,"Repeat install cannot charge twice");var level=c.Railway.Defense.Mounted.Single().Building.Module<IUpgradeControl>().Level;var ironBeforeUpgrade=bank.Amount("iron");Click("weapon-upgrade");Check(bank.Amount("iron")==ironBeforeUpgrade-TrainArmament.UpgradeIronPerLevel*level,"Upgrade exact cost");Check(!B("weapon-upgrade").interactable,"Main level cap respected");var power=c.Bases.Bases[station.OwnerBaseId].Nexus.Module<PowerModule>();var powerState=SavedState.Capture(power);powerState.values.Single(x=>x.name=="Stored").text="30";powerState.Restore(power);Click("weapon-charge");Check(r.train.armament.battery==30&&power.Stored==0,"Charging conserves station energy");before-=TrainArmament.UpgradeIronPerLevel*level;Match();Check(!B("weapon-shape").interactable&&!B("weapon-install").interactable,"Installed restrictions");Click("weapon-remove");Check(bank.Amount("iron")==before-TrainArmament.InstallIron&&string.IsNullOrEmpty(r.train.armament.definition),"Remove no refund");Check(r.train.armament.battery==30,"Removal keeps battery");Click("weapon-install");
s.Return.onClick.Invoke();v.Execute("fuel");v.Execute("start");for(int i=0;i<60&&r.train.status!=TrainStatus.Moving;i++)c.Railway.Tick(.25);Check(r.train.status==TrainStatus.Moving,"Real train moving");v.Execute("cargo");yield return null;Match();Check(!B("configure").interactable&&rail.Load.readOnly,"Moving cargo readonly");s.Return.onClick.Invoke();v.Execute("defense");Match();Check(new[]{"weapon-install","weapon-remove","weapon-charge","weapon-shape","weapon-upgrade"}.All(cmd=>!B(cmd).interactable),"Moving defense gates");s.Return.onClick.Invoke();v.Execute("stop");c.Railway.Tick(r.CurrentLeg.cells.Count-r.train.progress);Check(r.train.status==TrainStatus.Stopped,"Actual next station stop");
c.Railway.Defense.Capture();var saved=n.Capture();var json=JsonUtility.ToJson(saved);File.WriteAllText(Root+"railway-save-fixture.json",json);n.Restore(JsonUtility.FromJson<RailwayNetwork.Snapshot>(json));c.Railway.Defense.Sync();var restored=n.Routes.Single();Check(restored.train.resource=="iron"&&restored.stops[0].load==7&&restored.stops[1].unload==12&&!string.IsNullOrEmpty(restored.train.armament.definition),"Cargo and installed defense snapshot restore");v.Execute("list");v.Apply();v.Rows[0].onClick.Invoke();v.Execute("cargo");yield return null;File.WriteAllText(Root+"play-result.json",new JObject{{"result","PASS"},{"initialCargoLock",true},{"invalidQuantities",true},{"selectedStationApply",true},{"groupAndReturnInputPreserved",true},{"defenseInstallOnceNoRefund",true},{"upgradeExactCostAndLevelCap",true},{"batteryConservationAndRemovalRetention",true},{"movingRestrictions",true},{"snapshotRestore",true},{"researchExperiment",false}}.ToString());File.WriteAllText(Root+"play-status.txt","PASS");}
}
public static class VerifyHud06BPlay{public static string Main(){if(!Application.isPlaying||!(Environment.GetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT")??"").Contains("hud-06b"))throw new Exception("Isolated Play required");new GameObject("Railway service verification",typeof(Hud06BProbe)).hideFlags=HideFlags.HideAndDontSave;return "Queued service verification";}}
