using System;using System.IO;using System.Linq;using System.Reflection;using System.Collections;using UnityEngine;using EternalSteam;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public sealed class Hud08EThrowingStore:ISaveStore {public SaveRead Read()=>new SaveRead();public void Write(string id,string data)=>throw new IOException("HUD08E simulated write failure");public void MarkFailed(string id){}public bool IsFailed(string id)=>false;public void Archive(){}}
public sealed class Hud08EResilienceProbe:MonoBehaviour{
const string Root="Docs/Measurements/2026-10-03-hud-08e/";void Check(bool b,string s){if(!b)throw new Exception(s);}
IEnumerator Start(){File.WriteAllText(Root+"resilience-status.txt","RUNNING");var it=Run();try{while(true){bool more;try{more=it.MoveNext();}catch(Exception e){File.WriteAllText(Root+"resilience-status.txt","FAIL "+e);break;}if(!more)break;yield return it.Current;}}finally{(it as IDisposable)?.Dispose();Destroy(gameObject);}}
IEnumerator Run(){var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();var s=h.Sandbox;var m=s.PauseMenu;s.Clock.Paused=true;s.Persistence.Automatic=false;h.Input.Cancel();h.GetComponent<GameplayHudWorkspace>().Construction();yield return new WaitForSecondsRealtime(.4f);var field=typeof(SingleMapPersistence).GetField("store",BindingFlags.Instance|BindingFlags.NonPublic);var original=field.GetValue(s.Persistence);string stamp=s.Persistence.LastSavedUtc;
try{field.SetValue(s.Persistence,new Hud08EThrowingStore());m.SetOpen(true);yield return new WaitForSecondsRealtime(.25f);h.Execute("save");Check(m.IsOpen&&s.SimulationPaused&&s.Persistence.LastSavedUtc==stamp&&s.Persistence.Status.Contains("저장 실패"),"Save error preserves modal/pause and timestamp");}finally{field.SetValue(s.Persistence,original);m.SetOpen(false);}
yield return new WaitForSecondsRealtime(.25f);s.Clock.SetPhase(DayPhase.Night);m.SetOpen(true);yield return new WaitForSecondsRealtime(.25f);Check(!s.Persistence.CanSave(out var reason)&&reason.Contains("낮"),"Night guard survives Esc");m.SetOpen(false);s.Clock.SetPhase(DayPhase.Day);yield return new WaitForSecondsRealtime(.25f);
h.Groups.Select(false);yield return new WaitForSecondsRealtime(.04f);m.SetOpen(true);Check(m.BlocksInput,"Transition modal blocks immediately");yield return new WaitForSecondsRealtime(.5f);Check(!h.Groups.Transitioning&&m.IsOpen,"Group transition finishes under menu");m.SetOpen(false);yield return new WaitForSecondsRealtime(.25f);
Check(s.Enemies.Alive==0,"Empty enemy fixture");var focus=s.CameraRig.Focus;int texture=h.Minimap.mainTexture.GetInstanceID();var update=(Action)Delegate.CreateDelegate(typeof(Action),h.Minimap,typeof(CanvasWorldMinimap).GetMethod("Update",BindingFlags.NonPublic|BindingFlags.Instance));var view=typeof(CanvasWorldMinimap).GetField("nextView",BindingFlags.NonPublic|BindingFlags.Instance);var objects=typeof(CanvasWorldMinimap).GetField("nextObjects",BindingFlags.NonPublic|BindingFlags.Instance);var samples=new double[120];
try{for(int i=0;i<1000;i++)Check(s.Enemies.TrySpawn(focus+new Vector3((i%32)-16,0,(i/32)-16),focus,0,20),"Dense fixture capacity");Check(!s.Persistence.CanSave(out reason),"Enemy combat blocks save");for(int i=-8;i<samples.Length;i++){view.SetValue(h.Minimap,0d);objects.SetValue(h.Minimap,0d);var timer=System.Diagnostics.Stopwatch.StartNew();update();timer.Stop();if(i>=0)samples[i]=timer.Elapsed.TotalMilliseconds;}Array.Sort(samples);yield return new WaitForEndOfFrame();Check(h.Minimap.mainTexture.GetInstanceID()==texture,"Dense markers reuse terrain texture");ScreenCapture.CaptureScreenshot(Root+"dense-minimap.png");yield return new WaitForEndOfFrame();}finally{s.Enemies.DespawnAll();}
File.WriteAllText(Root+"resilience-result.json",new JObject{{"result","PASS"},{"saveWriteFailurePreservesModal",true},{"nightAndEnemySaveGuards",true},{"menuDuringGroupTransition",true},{"denseEnemies",1000},{"forcedUpdateSamples",samples.Length},{"updateMedianMs",samples[60]},{"updateP95Ms",samples[114]},{"updateMaxMs",samples.Last()},{"scope","Editor forced minimap Update only; excludes mesh submission and full frame. No target-device performance acceptance."},{"textureReused",true},{"researchExperiment",false}}.ToString());File.WriteAllText(Root+"resilience-status.txt","PASS");}}
public static class VerifyHud08EFailureAndDensity {public static string Main(){if(!Application.isPlaying||!(Environment.GetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT")??"").Contains("hud-08e"))throw new Exception("Isolated Play required");new GameObject("HUD resilience probe",typeof(Hud08EResilienceProbe)).hideFlags=HideFlags.HideAndDontSave;return "Queued failure and density acceptance";}}
