using System;using System.IO;using System.Linq;using System.Collections.Generic;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using UnityEditor;using UnityEditor.SceneManagement;using EternalSteam;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public sealed class IntegratedPresentationFrameProbe:MonoBehaviour{
 System.Collections.IEnumerator Start(){var routine=VerifyIntegratedPresentation.Play();while(true){bool next;try{next=routine.MoveNext();}catch(Exception e){File.WriteAllText("Docs/Measurements/2026-10-02-train-hud-integration/play-frame-last.txt","FAIL "+e);break;}if(!next)break;yield return routine.Current;}Destroy(gameObject);}
}
public static class VerifyIntegratedPresentation{
 public static string QueuePlay(){var go=new GameObject("Product presentation verification");go.hideFlags=HideFlags.HideAndDontSave;go.AddComponent<IntegratedPresentationFrameProbe>();return "Queued actual Game frame input verification";}

 const string Root="Docs/Measurements/2026-10-02-train-hud-integration/";
 static void Check(bool ok,string why){if(!ok)throw new Exception(why);}
 public static string Saved(){Check(!EditorApplication.isPlaying,"Edit mode required");string original=EditorSceneManager.GetActiveScene().path;var report=new JArray();
 try{foreach(string n in new[]{"StartRegionSandbox","OpenWorldSandbox"}){var scene=EditorSceneManager.OpenScene("Assets/EternalSteam/Scene/Tests/"+n+".unity");var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();var w=h.GetComponent<GameplayHudWorkspace>();Check(w!=null&&w.Hud==h&&w.Railway==h.Sandbox.RailwayHud&&w.RailwayWorkspace!=null,"Saved workspace references");
 Check(w.ConstructionTab.onClick.GetPersistentTarget(0)==w&&w.ConstructionTab.onClick.GetPersistentMethodName(0)=="Construction","Construction persistent callback");Check(w.RailwayTab.onClick.GetPersistentTarget(0)==w&&w.RailwayTab.onClick.GetPersistentMethodName(0)=="Railways","Railway persistent callback");
 Check(h.Buttons.All(b=>b.View!=null&&b.View.onClick.GetPersistentEventCount()==1),"Saved existing HUD callbacks");Check(w.Railway.Commands.All(b=>b.Button!=null&&b.Button.onClick.GetPersistentEventCount()==1),"Saved railway callbacks");
 Check(!h.ShowDevelopmentControls&&h.Sections.Where(s=>s.Id is "developer" or "test-shortcuts").All(s=>!s.Body.activeSelf),"Development UI hidden");Check(h.GetComponentsInChildren<MonoBehaviour>(true).All(c=>c!=null),"No missing UI scripts");
 var train=h.Sandbox.RailwayView.TrainPrefab.GetComponent<TrainConsistView>();Check(train!=null&&train.Model!=null&&train.LinkedMotion!=null&&train.TurretMount!=null,"Both scenes reference applied consist");
 Check(h.Layout.CategoryStrip.parent==h.Layout.InventoryBody,"Categories belong to construction");foreach(var def in new[]{w.Railway.Station,w.Railway.Track,w.Railway.CoalProducer}){var e=h.Catalog.Single(c=>c.Definition==def);Check(e.Icon.sprite!=null&&e.View.onClick.GetPersistentTarget(0)==h,"Integrated railway card");}Check(w.Railway.Panel.transform.parent==w.RailwayWorkspace,"Authored railway workspace");
 foreach(var scroll in h.GetComponentsInChildren<ScrollRect>(true))Check(scroll.content!=null&&scroll.viewport!=null&&scroll.content.IsChildOf(scroll.viewport),"Saved scroll content/viewport "+scroll.name);
 report.Add(new JObject{{"scene",n},{"hudCallbacks",h.Buttons.Length},{"railCallbacks",w.Railway.Commands.Length},{"trainClip",train.LinkedMotion.name},{"result","PASS"}});
 }}finally{EditorSceneManager.OpenScene(original);}File.WriteAllText(Root+"saved-references.json",report.ToString());return report.ToString();}
 static void Inside(CanvasWorldHud h,RectTransform t){var root=ScreenRect(h.Layout.Root);var r=ScreenRect(t);Check(r.xMin>=root.xMin-.5f&&r.yMin>=root.yMin-.5f&&r.xMax<=root.xMax+.5f&&r.yMax<=root.yMax+.5f,"Outside canvas: "+t.name+" "+r+" / "+root);}
 static Rect ScreenRect(RectTransform t){var c=new Vector3[4];t.GetWorldCorners(c);return Rect.MinMaxRect(c[0].x,c[0].y,c[2].x,c[2].y);}
 static void Click(CanvasWorldHud h,Button b){Check(b.interactable&&b.gameObject.activeInHierarchy,"Visible interactive "+b.name);Canvas.ForceUpdateCanvases();var pos=ScreenRect((RectTransform)b.transform).center;var hits=new List<RaycastResult>();var data=new PointerEventData(EventSystem.current){position=pos,button=PointerEventData.InputButton.Left};h.Raycaster.Raycast(data,hits);Check(hits.Any(r=>r.gameObject==b.gameObject),"UI raycast "+b.name+" screen="+Screen.width+"x"+Screen.height+" point="+pos+" hits="+string.Join(",",hits.Select(x=>x.gameObject.name)));ExecuteEvents.Execute(b.gameObject,data,ExecuteEvents.pointerClickHandler);}
 public static System.Collections.IEnumerator Play(){Check(Application.isPlaying,"Play required");Check(Environment.GetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT")==Path.GetFullPath(Root+"play-save"),"Project-isolated product save");var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();var w=h.GetComponent<GameplayHudWorkspace>();var s=h.Sandbox;s.Clock.Paused=true;s.Persistence.Automatic=false;h.Input.Cancel();if(w.Railway.Panel.activeSelf)w.Railway.Execute("close");w.Apply();yield return null;int hierarchy=h.GetComponentsInChildren<Transform>(true).Count(t=>t.GetComponent<TMPro.TMP_SubMeshUI>()==null);
 Click(h,w.ConstructionTab);w.Apply();yield return null;Check(h.Input.IsEditing&&h.Layout.InventoryBody.gameObject.activeSelf&&!w.Railway.Panel.activeSelf,"Construction entry");var scroll=h.CatalogLayout.GetComponentInParent<ScrollRect>();scroll.horizontalNormalizedPosition=1;yield return null;
 foreach(var def in new[]{w.Railway.Station,w.Railway.Track,w.Railway.CoalProducer}){var e=h.Catalog.Single(c=>c.Definition==def);Click(h,e.View);Check(h.Input.SelectedDefinition==def,"Railway catalogue selection "+def.Id);}h.Input.Cancel();Click(h,w.RailwayTab);w.Apply();yield return null;Check(!h.Input.IsEditing&&w.Railway.Panel.activeSelf&&!h.Layout.InventoryBody.gameObject.activeSelf,"Railway entry owns workspace");
 w.Railway.Execute("connect");Check(w.Railway.HasDraft,"Connection draft");h.Execute("edit");Check(!h.Input.IsEditing,"Draft blocks concurrent building");w.Railway.Execute("connection-cancel");w.Railway.Execute("close");w.Apply();
 var station=s.Content.Railway.Network.Stations.First();Check(h.Input.ClickWorld(station.Position),"Select station in world");h.Refresh();yield return null;var stationButton=h.Buttons.Single(b=>b.Id=="station-railway").View;Click(h,stationButton);w.Apply();yield return null;Check(w.Railway.ContextStationId==station.PersistentId&&h.Layout.SelectionPanel.gameObject.activeSelf,"Selected station opens contextual railway with selection info");
 Check(!h.Texts.Single(t=>t.Id=="selection-title").View.text.Contains("검증비")&&h.SelectionPortrait.sprite!=null,"Player-facing station title and portrait");Canvas.ForceUpdateCanvases();var rail=ScreenRect((RectTransform)w.Railway.Panel.transform);var selected=ScreenRect(h.Layout.SelectionPanel);var resource=ScreenRect(h.Layout.ResourcePanel);var bar=ScreenRect(h.Layout.ConstructionBar);Check(!rail.Overlaps(selected)&&!rail.Overlaps(resource)&&!rail.Overlaps(bar),"Railway/selection/resources/construction must not overlap");
 foreach(var panel in new[]{h.Layout.ClockPanel,h.Layout.ResourcePanel,h.Layout.MapPanel,h.Layout.SelectionPanel,h.Layout.ConstructionBar,h.Layout.Notifications,(RectTransform)w.Railway.Panel.transform})Inside(h,panel);
 foreach(var popup in h.Layout.FloatingPanels){bool active=popup.gameObject.activeSelf;popup.gameObject.SetActive(true);h.Layout.Apply(true);yield return null;Inside(h,popup);Check(!ScreenRect(popup).Overlaps(ScreenRect(h.Layout.ConstructionBar)),"Popup clears dock");popup.gameObject.SetActive(active);}Check(hierarchy==h.GetComponentsInChildren<Transform>(true).Count(t=>t.GetComponent<TMPro.TMP_SubMeshUI>()==null),"No runtime HUD construction");
 w.Railway.Execute("row:0");yield return null;w.Apply();Canvas.ForceUpdateCanvases();
 Check(w.Railway.StationContextPanel.activeSelf,"Route station panel");Check(!ScreenRect((RectTransform)w.Railway.StationContextPanel.transform).Overlaps(selected),"Route detail clears selected info");
 w.Railway.Execute("edit");yield return null;w.Apply();Canvas.ForceUpdateCanvases();Check(w.Railway.DraftStopsPanel.activeSelf,"Route editor");Inside(h,(RectTransform)w.Railway.DraftStopsPanel.transform);
 var objective=h.Texts.FirstOrDefault(t=>t.Id=="first-loop-objective").View;if(objective!=null)Check(!ScreenRect((RectTransform)w.Railway.DraftStopsPanel.transform).Overlaps(ScreenRect((RectTransform)objective.transform.parent)),"Draft panel clears objective");
 w.Railway.Execute("close");if(w.Railway.HasDraft)w.Railway.Execute("discard");w.Apply();yield return null;
 var n=s.Content.Railway.Network;Check(n.Routes.Count==1,"Saved running train fixture");s.Content.Railway.Tick(0);var view=s.RailwayView.Defense(n.Routes[0].trainId);Check(view!=null,"Route spawned saved prefab");var model=view.GetComponent<TrainConsistView>();var phase=model.Phase;for(int i=0;i<5;i++)s.Content.Railway.Tick(.1);Check(!Mathf.Approximately(phase,model.Phase),"Route movement drives animation");Check(Vector3.Distance(view.Turret.position,s.RailwayView.CombatPosition(n.Routes[0],s.Content))<.001f,"Combat origin follows platform turret");
 var camera=s.CameraRig.View;var result=new JObject{{"result","PASS"},{"resolution",camera.pixelWidth+"x"+camera.pixelHeight},{"hierarchyObjects",hierarchy},{"workspaceRaycastAndPointerEvents",true},{"constructionAndRailwayExclusive",true},{"selectedStationContext",true},{"draftGuard",true},{"railwayCatalogCards",3},{"detailAndDraftBounds",true},{"panelBoundsDisjoint",true},{"animationPhase",model.Phase},{"combatMountMatches",true},{"researchExperiment",false}};File.WriteAllText(Root+"play-ui-"+camera.pixelWidth+"x"+camera.pixelHeight+".json",result.ToString());File.WriteAllText(Root+"play-frame-last.txt",result.ToString());yield break;}
}
