using UnityEditor;using System.Reflection;using System;using System.IO;using System.Linq;using System.Collections;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public sealed class Hud07MatrixProbe:MonoBehaviour{
 const string Root="Docs/Measurements/2026-10-02-hud-07/";
 void Check(bool ok,string why){if(!ok)throw new Exception(why);}
 void Inspect(CanvasWorldHud h,string key,string mode){
var test=h.Layout.TestShortcuts;var panel=mode=="combat"?h.Layout.MapPanel:h.Layout.ResourcePanel;
Rect Bounds(RectTransform r){var c=new Vector3[4];r.GetWorldCorners(c);return Rect.MinMaxRect(c[0].x,c[0].y,c[2].x,c[2].y);}
Check(!Bounds(test).Overlaps(Bounds(panel)),"Test shortcuts clear side panel");
var report=new JArray();var list=h.Buttons.Where(b=>new[]{"pause","menu-fold","infinite-resources","quick-day","quick-night"}.Contains(b.Id)).Select(b=>b.View).ToList();list.Add(h.Groups.ModeLabel.GetComponentInParent<Button>());foreach(var button in list.Where(b=>b.gameObject.activeInHierarchy)){var t=button.GetComponentInChildren<TMPro.TMP_Text>();t.ForceMeshUpdate();float pixels=t.fontSize*t.transform.lossyScale.x;Check(pixels>=11.9f,"Common caption minimum: "+button.name);Check(t.textInfo.characterInfo.Take(t.textInfo.characterCount).Any(c=>c.isVisible),"Caption visible: "+button.name);report.Add(new JObject{{"button",button.name},{"fontPixels",pixels},{"captionVisible",t.textInfo.characterInfo.Take(t.textInfo.characterCount).Any(c=>c.isVisible)}});}File.WriteAllText(Root+key+"-"+mode+"-readability.json",report.ToString());}
 IEnumerator Start(){var routine=Matrix();while(true){bool next;try{next=routine.MoveNext();}catch(Exception e){File.WriteAllText(Root+"play-status.txt","FAIL "+e);break;}if(!next)break;yield return routine.Current;}Destroy(gameObject);}
 void CheckBounds(RectTransform r){var c=new Vector3[4];r.GetWorldCorners(c);foreach(var v in c){var p=RectTransformUtility.WorldToScreenPoint(null,v);Check(p.x>=-1&&p.y>=-1&&p.x<=Screen.width+1&&p.y<=Screen.height+1,"Screen bounds: "+r.name);}}
 IEnumerator Matrix(){foreach(var size in new[]{new Vector2Int(800,600),new Vector2Int(1024,768),new Vector2Int(1280,720),new Vector2Int(1920,1080),new Vector2Int(2560,1080),new Vector2Int(3840,1080),new Vector2Int(3840,2160)}){SetHudReviewResolution.Main(size.x,size.y);yield return null;yield return null;var steps=Verify();while(steps.MoveNext())yield return steps.Current;}SetHudReviewResolution.Main(2560,1440);File.WriteAllText(Root+"matrix-"+UnityEngine.SceneManagement.SceneManager.GetActiveScene().name+".txt","PASS 7 resolutions");}
 IEnumerator Verify(){var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();var g=h.Groups;var s=h.Sandbox;h.GetComponent<GameplayHudWorkspace>().Construction();var key=UnityEngine.SceneManagement.SceneManager.GetActiveScene().name+"-"+s.CameraRig.View.pixelWidth+"x"+s.CameraRig.View.pixelHeight;if(s.Persistence!=null)s.Persistence.Automatic=false;s.Clock.Paused=true;yield return null;yield return new WaitForEndOfFrame();
 g.Select(false);yield return new WaitForSecondsRealtime(.3f);Check(!g.ConstructionSelected&&g.Combat.gameObject.activeInHierarchy,"Combat default");Check(h.Layout.MapPanel.gameObject.activeInHierarchy,"Combat map visible");CheckBounds(h.Layout.ClockPanel);CheckBounds(h.Layout.MapPanel);Check(h.Layout.MapBody.rect.height>=180,"Combat minimap readable size");Check(!h.Layout.ResourcePanel.gameObject.activeInHierarchy,"Resources in construction only");Inspect(h,key,"combat");ScreenCapture.CaptureScreenshot(Root+key+"-combat.png");yield return null;
 var rect=h.Minimap.VisibleWorldBounds;Check(Mathf.Approximately(rect.width,150)&&Mathf.Approximately(rect.height,150),"Local minimap range");var before=rect.center;var focus=s.CameraRig.Focus;s.CameraRig.MoveFocus(focus+Vector3.right*20);yield return null;yield return new WaitForSecondsRealtime(.12f);Check(Vector2.Distance(before,h.Minimap.VisibleWorldBounds.center)>1,"Minimap follows view");s.CameraRig.MoveFocus(focus);
 var toggle=g.ModeLabel.GetComponentInParent<Button>();var corners=new Vector3[4];((RectTransform)toggle.transform).GetWorldCorners(corners);var pos=RectTransformUtility.WorldToScreenPoint(null,(corners[0]+corners[2])*.5f);var e=new PointerEventData(EventSystem.current){position=pos,button=PointerEventData.InputButton.Left};var hits=new System.Collections.Generic.List<RaycastResult>();h.Raycaster.Raycast(e,hits);Check(hits.Any(hit=>hit.gameObject==toggle.gameObject||hit.gameObject.transform.IsChildOf(toggle.transform)),"Toggle raycast");ExecuteEvents.Execute(toggle.gameObject,e,ExecuteEvents.pointerClickHandler);Check(g.Transitioning&&!g.Construction.interactable,"Transition gates input");yield return new WaitForSecondsRealtime(.32f);Check(g.CanUseConstruction&&!g.Combat.gameObject.activeInHierarchy,"Construction completes while paused");Check(h.Layout.ResourcePanel.gameObject.activeInHierarchy,"Construction resources visible");Check(!h.Input.IsEditing,"Group alone does not begin editing");CheckBounds(h.Layout.ResourcePanel);CheckBounds(h.Layout.ConstructionBar);yield return new WaitForEndOfFrame();Inspect(h,key,"construction");ScreenCapture.CaptureScreenshot(Root+key+"-construction.png");
 h.Input.BeginEditing();var tool=h.Input.Tool;g.Select(false);yield return new WaitForSecondsRealtime(.32f);Check(h.Input.Tool==tool,"Editing state retained");g.Select(true);yield return new WaitForSecondsRealtime(.08f);g.Select(false);yield return new WaitForSecondsRealtime(.08f);g.Select(true);yield return new WaitForSecondsRealtime(.32f);Check(g.CanUseConstruction&&h.Input.Tool==tool,"Rapid reversal retains editing");h.Input.Cancel();
 foreach(var id in new[]{"infinite-resources","quick-day","quick-night"})Check(h.Buttons.Single(b=>b.Id==id).View.gameObject.activeInHierarchy,"Common test control "+id);
 g.Select(false);yield return new WaitForSecondsRealtime(.32f);var result=new JObject{{"result","PASS"},{"defaultCombat",true},{"toggleRaycast",true},{"pausedTransition",true},{"rapidReversal",true},{"editingPreserved",true},{"minimapSide",150},{"minimapTracksView",true},{"testControlsVisible",true},{"researchExperiment",false}};File.WriteAllText(Root+key+"-play-result.json",result.ToString());File.WriteAllText(Root+"play-status.txt","PASS");}
}
public static class VerifyHud07Matrix{public static string Main(){if(!Application.isPlaying||!(Environment.GetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT")??"").Contains("2026-10-02-hud-07"))throw new Exception("Project-local isolated play required");new GameObject("HUD groups verification",typeof(Hud07MatrixProbe)).hideFlags=HideFlags.HideAndDontSave;return "Queued product UI validation";}}

public static class SetHudReviewResolution
{
 public static string Main(int width=1920,int height=1080)
 {
  var assembly=typeof(EditorWindow).Assembly;var sizesType=assembly.GetType("UnityEditor.GameViewSizes");var singleton=typeof(ScriptableSingleton<>).MakeGenericType(sizesType);var sizes=singleton.GetProperty("instance").GetValue(null);
  var group=sizesType.GetMethod("GetGroup").Invoke(sizes,new object[]{0});var gt=group.GetType();int count=(int)gt.GetMethod("GetTotalCount").Invoke(group,null),index=-1;
  for(int i=0;i<count;i++){var size=gt.GetMethod("GetGameViewSize").Invoke(group,new object[]{i});var t=size.GetType();if((int)t.GetProperty("width").GetValue(size)==width&&(int)t.GetProperty("height").GetValue(size)==height){index=i;break;}}
  if(index<0){var type=assembly.GetType("UnityEditor.GameViewSize");var kind=assembly.GetType("UnityEditor.GameViewSizeType");var size=Activator.CreateInstance(type,new object[]{Enum.ToObject(kind,1),width,height,"HUD review "+width+"x"+height});gt.GetMethod("AddCustomSize").Invoke(group,new[]{size});index=count;}
  var viewType=assembly.GetType("UnityEditor.GameView");var view=EditorWindow.GetWindow(viewType);if(!SessionState.GetBool("HudReview.HasOriginal",false)){SessionState.SetInt("HudReview.SizeIndex",(int)viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).GetValue(view));SessionState.SetBool("HudReview.HasOriginal",true);}
  viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).SetValue(view,index);view.Show();view.Focus();view.Repaint();return width+"x"+height;
 }
}
