using UnityEditor;using System.Reflection;
using System;using System.IO;using System.Linq;using System.Collections;using UnityEngine;using UnityEngine.EventSystems;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public sealed class MinimapCornerProbe:MonoBehaviour{
const string Root="Docs/Measurements/2026-10-03-minimap-top-right/";CanvasWorldHud h;int errors;void Log(string s,string stack,LogType t){if(t==LogType.Exception||t==LogType.Error)errors++;}
void Check(bool b,string s){if(!b)throw new Exception(s);}Vector2 Point(Vector2 uv){var r=h.Minimap.rectTransform;return RectTransformUtility.WorldToScreenPoint(null,r.TransformPoint(new Vector2(r.rect.xMin+uv.x*r.rect.width,r.rect.yMin+uv.y*r.rect.height)));}
PointerEventData Event(Vector2 uv)=>new PointerEventData(EventSystem.current){position=Point(uv),pointerId=71,button=PointerEventData.InputButton.Left};
bool Hit(Vector2 uv){var hits=new System.Collections.Generic.List<RaycastResult>();h.Raycaster.Raycast(Event(uv),hits);return hits.Any(x=>x.gameObject==h.Minimap.gameObject);}
IEnumerator Start(){Application.logMessageReceived+=Log;string scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene().name;File.WriteAllText(Root+scene+"-status.txt","RUNNING");var it=Verify();while(true){bool more;try{more=it.MoveNext();}catch(Exception e){File.WriteAllText(Root+scene+"-status.txt","FAIL "+e);break;}if(!more)break;yield return it.Current;}Application.logMessageReceived-=Log;Destroy(gameObject);}
IEnumerator Verify(){h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();var m=h.Minimap;var s=h.Sandbox;s.Clock.Paused=true;if(s.Persistence!=null)s.Persistence.Automatic=false;s.CameraRig.MoveFocus(MinimapProjection.ForTerrain(s.Ground).ToWorld(Vector2.one*.5f));yield return new WaitForSecondsRealtime(.2f);var original=s.CameraRig.Focus;int texture=m.mainTexture.GetInstanceID();var result=new JArray();var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene().name;
foreach(var size in new[]{new Vector2Int(800,600),new Vector2Int(1024,768),new Vector2Int(1280,720),new Vector2Int(1920,1080),new Vector2Int(2560,1080),new Vector2Int(3840,1080),new Vector2Int(3840,2160)}){
SetHudReviewResolution.Main(size.x,size.y);yield return new WaitForSecondsRealtime(.35f);Canvas.ForceUpdateCanvases();yield return new WaitForEndOfFrame();h.Layout.Apply(true);Canvas.ForceUpdateCanvases();yield return new WaitForEndOfFrame();
var corners=new Vector3[4];h.Layout.MapPanel.GetWorldCorners(corners);Check(corners.All(p=>p.x>=-.1f&&p.y>=-.1f&&p.x<=Screen.width+.1f&&p.y<=Screen.height+.1f),"Frame bounds");var hint=new Vector3[4];h.Layout.EscapeHint.GetWorldCorners(hint);Check(Mathf.Abs(corners[2].x-Screen.width)<.1f&&Mathf.Abs(corners[2].y-Screen.height)<.1f,"Top/right edge alignment");Check(hint[2].y<corners[0].y,"Esc hint below minimap");float diameter=Vector2.Distance(Point(new Vector2(0,.5f)),Point(new Vector2(1,.5f)));Check(Mathf.Abs(diameter-Mathf.Clamp(size.y*.24f,144,256))<.1f,"Physical diameter "+size+" actual="+diameter+" scale="+h.Layout.Canvas.scaleFactor);Check(Mathf.Abs(diameter-Vector2.Distance(Point(new Vector2(.5f,0)),Point(new Vector2(.5f,1))))<.1f,"Circle aspect");Check(m.VisibleWorldBounds.size==Vector2.one*150,"150 world units");
Check(Hit(new Vector2(.5f,.5f))&&Hit(new Vector2(.999f,.5f)),"Circle accepts center and near boundary");Check(!Hit(new Vector2(.02f,.02f))&&!Hit(new Vector2(.98f,.98f)),"Transparent corners pass through");
var focus=s.CameraRig.Focus;m.OnPointerDown(Event(new Vector2(.98f,.98f)));Check(!m.Interacting&&s.CameraRig.Focus==focus,"Outside press ignored");
var projection=new MinimapProjection(m.VisibleWorldBounds);var valid=new System.Collections.Generic.List<Vector2>();var tiles=s.Ground.GetComponent<TileWorldGround>();for(int yy=2;yy<=8;yy++)for(int xx=2;xx<=8;xx++){var uv=new Vector2(xx/10f,yy/10f);var wp=projection.ToWorld(new Vector2(uv.x,1-uv.y));if(CanvasWorldMinimap.ContainsNormalized(uv)&&(tiles==null||tiles.IsPlayable(wp)))valid.Add(uv);}Check(valid.Count>=2,"Two playable navigation samples");var uvA=valid[0];var uvB=valid[1];m.OnPointerDown(Event(uvA));Check(m.Interacting,"Inside capture");var expected=projection.ToWorld(new Vector2(uvA.x,1-uvA.y));Check(Vector2.Distance(new Vector2(s.CameraRig.Focus.x,s.CameraRig.Focus.z),new Vector2(expected.x,expected.z))<.1f,"Inside navigation");focus=s.CameraRig.Focus;m.OnDrag(Event(new Vector2(.95f,.95f)));Check(m.Interacting&&s.CameraRig.Focus==focus,"Outside drag pauses without releasing capture");yield return new WaitForSecondsRealtime(.1f);
m.OnDrag(Event(uvB));expected=projection.ToWorld(new Vector2(uvB.x,1-uvB.y));Check(Vector2.Distance(new Vector2(s.CameraRig.Focus.x,s.CameraRig.Focus.z),new Vector2(expected.x,expected.z))<.1f,"Reentry uses original projection");m.OnPointerUp(Event(new Vector2(.95f,.95f)));Check(!m.Interacting,"Outside release");
m.OnPointerDown(Event(Vector2.one*.5f));h.Groups.Select(true);Check(!m.Interacting,"Tab cancels capture immediately");h.Groups.Advance(1);h.Groups.Select(false);h.Groups.Advance(1);yield return null;
m.OnPointerDown(Event(Vector2.one*.5f));s.PauseMenu.SetOpen(true);Check(!m.Interacting,"Esc cancels capture");s.PauseMenu.SetOpen(false);yield return new WaitForSecondsRealtime(.25f);
s.CameraRig.MoveFocus(original);yield return new WaitForSecondsRealtime(.15f);Check(m.mainTexture.GetInstanceID()==texture,"Terrain texture reused");ScreenCapture.CaptureScreenshot(Root+$"{scene}-{size.x}x{size.y}-circle.png");yield return new WaitForEndOfFrame();result.Add(new JObject{{"width",size.x},{"height",size.y},{"mapDiameterPixels",diameter},{"worldDiameter",150},{"circleRaycast",true},{"outsideDragCapture",true},{"reentryProjection",true},{"tabEscCancel",true},{"textureReused",true}});
m.OnPointerDown(Event(Vector2.one*.5f));h.Layout.MapBody.sizeDelta+=Vector2.one;Canvas.ForceUpdateCanvases();Check(!m.Interacting,"Resize cancels capture");h.Layout.Apply(true);
}
Check(errors==0,"Runtime errors: "+errors);SetHudReviewResolution.Main(2560,1440);File.WriteAllText(Root+scene+"-results.json",new JObject{{"result","PASS"},{"runtimeErrors",errors},{"cases",result}}.ToString());File.WriteAllText(Root+scene+"-status.txt","PASS 7 resolutions");}}
public static class VerifyMinimapCorner {public static string Main(){if(!Application.isPlaying||!(Environment.GetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT")??"").Contains("minimap-top-right"))throw new Exception("Isolated Play required");new GameObject("Circular minimap verification",typeof(MinimapCornerProbe)).hideFlags=HideFlags.HideAndDontSave;return "Queued circular minimap checks";}}
public static class SetHudReviewResolution
{
 public static string Main(int width=1920,int height=1080)
 {
  var assembly=typeof(EditorWindow).Assembly;var sizesType=assembly.GetType("UnityEditor.GameViewSizes");var singleton=typeof(ScriptableSingleton<>).MakeGenericType(sizesType);var sizes=singleton.GetProperty("instance").GetValue(null);
  var group=sizesType.GetMethod("GetGroup").Invoke(sizes,new object[]{0});var gt=group.GetType();int count=(int)gt.GetMethod("GetTotalCount").Invoke(group,null),index=-1;
  for(int i=0;i<count;i++){var size=gt.GetMethod("GetGameViewSize").Invoke(group,new object[]{i});var t=size.GetType();if((int)t.GetProperty("width").GetValue(size)==width&&(int)t.GetProperty("height").GetValue(size)==height){index=i;break;}}
  if(index<0){var type=assembly.GetType("UnityEditor.GameViewSize");var kind=assembly.GetType("UnityEditor.GameViewSizeType");var size=Activator.CreateInstance(type,new object[]{Enum.ToObject(kind,1),width,height,"HUD review "+width+"x"+height});gt.GetMethod("AddCustomSize").Invoke(group,new[]{size});index=count;}
  var viewType=assembly.GetType("UnityEditor.GameView");var view=EditorWindow.GetWindow(viewType);if(!SessionState.GetBool("HudReview.HasOriginal",false)){SessionState.SetInt("HudReview.SizeIndex",(int)viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).GetValue(view));SessionState.SetBool("HudReview.HasOriginal",true);}
  viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).SetValue(view,index);view.Show();view.Focus();view.Repaint();return width+"x"+height;
 }
}
