using System;using System.Collections;using System.IO;using System.Linq;using UnityEngine;using UnityEngine.EventSystems;using UnityEngine.UI;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;using UnityEditor;using System.Reflection;
public sealed class Hud08DockDetailProbe:MonoBehaviour{
const string Root="Docs/Measurements/2026-10-03-hud-08d/";CanvasWorldHud h;void Check(bool ok,string why){if(!ok)throw new Exception(why);}IEnumerator Start(){var it=Verify();while(true){bool more;try{more=it.MoveNext();}catch(Exception e){File.WriteAllText(Root+"details-status.txt","FAIL "+e);if(h!=null){h.enabled=true;h.Layout.CompactDock.enabled=true;}break;}if(!more)break;yield return it.Current;}Destroy(gameObject);}
IEnumerator Verify(){File.WriteAllText(Root+"details-status.txt","RUNNING");h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();var d=h.Layout.CompactDock;h.Input.Cancel();d.CloseDetails();h.Groups.Select(true);SetHudReviewResolution.Main(800,600);yield return new WaitForSecondsRealtime(.5f);h.BaseResources.Refresh();Check(h.BaseResources.BaseCount>0,"Campaign base fixture");h.BaseResources.Toggle(0);yield return new WaitForSecondsRealtime(.2f);string expanded=h.BaseResources.ExpandedBaseId;h.BaseResources.Scroll.verticalNormalizedPosition=.35f;yield return new WaitForEndOfFrame();float scroll=h.BaseResources.Scroll.verticalNormalizedPosition;ScreenCapture.CaptureScreenshot(Root+"resource-expanded-800.png");h.Groups.Select(false);yield return new WaitForSecondsRealtime(.35f);h.Groups.Select(true);yield return new WaitForSecondsRealtime(.35f);Check(h.BaseResources.ExpandedBaseId==expanded&&Mathf.Abs(scroll-h.BaseResources.Scroll.verticalNormalizedPosition)<.01,"Resource expansion and scroll return");
h.Input.ClickWorld(h.Sandbox.Content.MainBase.Position);h.Refresh();yield return new WaitForSecondsRealtime(.4f);Check(d.NarrowSelection&&!d.Browse.gameObject.activeSelf,"Selected building replaces narrow catalog");ScreenCapture.CaptureScreenshot(Root+"selection-800.png");h.Execute("selection-close");yield return new WaitForSecondsRealtime(.4f);Check(!d.NarrowSelection&&d.Browse.gameObject.activeSelf,"Close selection returns catalog");
h.Catalog.First(c=>c.Definition?.Id=="railway.track").View.onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);d.Execute("cost");yield return new WaitForEndOfFrame();h.enabled=false;d.enabled=false;var summary=h.Texts.Single(t=>t.Id=="construction-summary").View;string oldSummary=summary.text,oldTitle=d.PlacementTitle.text;d.PlacementTitle.text=string.Concat(Enumerable.Repeat("긴 건물 이름 ",30));summary.text=string.Join("\n",Enumerable.Range(1,40).Select(i=>$"비용 항목 {i}: 999,999,999 / 보유 123,456,789"));d.PlacementTitle.ForceMeshUpdate();Canvas.ForceUpdateCanvases();yield return new WaitForEndOfFrame();var costs=h.Layout.ConstructionSummary.GetComponent<ScrollRect>();Check(costs.content.rect.height>costs.viewport.rect.height,"Long costs scroll rather than grow dock");Check(d.PlacementTitle.isTextTruncated,"Long name ellipsis preserves 18px");Check(h.Layout.ConstructionBar.rect.height<=80.1f,"Long text does not expand dock");costs.verticalNormalizedPosition=0;yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Root+"long-name-costs-800.png");summary.text=oldSummary;d.PlacementTitle.text=oldTitle;h.enabled=true;d.enabled=true;h.Input.Cancel();d.CloseDetails();File.WriteAllText(Root+"details-result.json",new JObject{{"result","PASS"},{"resourceExpansionAndScrollPreserved",true},{"narrowSelectionReplacesCatalog",true},{"longNamesEllipsizedAt18px",true},{"longCostsScrollable",true}}.ToString());File.WriteAllText(Root+"details-status.txt","PASS");}}
public static class VerifyHud08DockDetails {public static string Main(){if(!Application.isPlaying)throw new Exception("Play required");new GameObject("Compact details verification",typeof(Hud08DockDetailProbe)).hideFlags=HideFlags.HideAndDontSave;return "Queued resource selection and long-content probes";}}
public static class SetHudReviewResolution
{
 public static string Main(int width=1920,int height=1080)
 {
  var assembly=typeof(EditorWindow).Assembly;var sizesType=assembly.GetType("UnityEditor.GameViewSizes");var singleton=typeof(ScriptableSingleton<>).MakeGenericType(sizesType);var sizes=singleton.GetProperty("instance").GetValue(null);
  var group=sizesType.GetMethod("GetGroup").Invoke(sizes,new object[]{0});var gt=group.GetType();int count=(int)gt.GetMethod("GetTotalCount").Invoke(group,null),index=-1;
  for(int i=0;i<count;i++){var size=gt.GetMethod("GetGameViewSize").Invoke(group,new object[]{i});var t=size.GetType();if((int)t.GetProperty("width").GetValue(size)==width&&(int)t.GetProperty("height").GetValue(size)==height){index=i;break;}}
  if(index<0){var type=assembly.GetType("UnityEditor.GameViewSize");var kind=assembly.GetType("UnityEditor.GameViewSizeType");var size=Activator.CreateInstance(type,new object[]{Enum.ToObject(kind,1),width,height,"HUD review "+width+"x"+height});gt.GetMethod("AddCustomSize").Invoke(group,new[]{size});index=count;}
  var viewType=assembly.GetType("UnityEditor.GameView");var view=EditorWindow.GetWindow(viewType);if(!SessionState.GetBool("HudReview.HasOriginal",false)){SessionState.SetInt("HudReview.SizeIndex",(int)viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).GetValue(view));SessionState.SetBool("HudReview.HasOriginal",true);}
  viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).SetValue(view,index);view.Show();view.Focus();view.Repaint();return width+"x"+height;
 }
}
