using UnityEditor;using System.Reflection;using System;using System.IO;using System.Linq;using System.Collections;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public sealed class Hud08MenuMatrix:MonoBehaviour{
const string Root="Docs/Measurements/2026-10-03-hud-08ab/";CanvasWorldHud h;void Check(bool ok,string why){if(!ok)throw new Exception(why);}
void Pointer(Button b){var r=(RectTransform)b.transform;var c=new Vector3[4];r.GetWorldCorners(c);Check(c.All(p=>p.x>=-1&&p.y>=-1&&p.x<=Screen.width+1&&p.y<=Screen.height+1),"Button bounds "+b.name);var hits=new System.Collections.Generic.List<RaycastResult>();h.Raycaster.Raycast(new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(null,r.TransformPoint(r.rect.center))},hits);Check(hits.Count>0&&(hits[0].gameObject==b.gameObject||hits[0].gameObject.transform.IsChildOf(b.transform)),"Pointer "+b.name+" top="+(hits.Count>0?hits[0].gameObject.name:"none"));}
IEnumerator Start(){var name=UnityEngine.SceneManagement.SceneManager.GetActiveScene().name;File.WriteAllText(Root+name+"-resolution-status.txt","RUNNING");var it=Verify();while(true){bool more;try{more=it.MoveNext();}catch(Exception e){File.WriteAllText(Root+name+"-resolution-status.txt","FAIL "+e);break;}if(!more)break;yield return it.Current;}Destroy(gameObject);}
IEnumerator Verify(){h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();var m=h.Sandbox.PauseMenu;if(h.Sandbox.Persistence!=null)h.Sandbox.Persistence.Automatic=false;h.Sandbox.Clock.Paused=true;var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene().name;var result=new JArray();foreach(var size in new[]{new Vector2Int(800,600),new Vector2Int(1024,768),new Vector2Int(1280,720),new Vector2Int(1920,1080),new Vector2Int(2560,1080),new Vector2Int(3840,1080),new Vector2Int(3840,2160)}){SetHudReviewResolution.Main(size.x,size.y);m.SetOpen(true);yield return new WaitForSecondsRealtime(.35f);Canvas.ForceUpdateCanvases();var scroll=m.Panel.GetComponentInChildren<ScrollRect>(true);scroll.verticalNormalizedPosition=1;yield return new WaitForEndOfFrame();var corners=new Vector3[4];m.Panel.GetWorldCorners(corners);Check(corners.All(p=>p.x>=16&&p.y>=23&&p.x<=Screen.width-15&&p.y<=Screen.height-23),"Menu bounds");Pointer(h.Buttons.Single(b=>b.Id=="pause").View);Pointer(h.Buttons.Single(b=>b.Id=="menu-close").View);foreach(var t in m.Panel.GetComponentsInChildren<TMPro.TMP_Text>(true))Check(Mathf.Abs(t.fontSize*t.transform.lossyScale.x-18)<.1f,"18px modal text "+t.name);ScreenCapture.CaptureScreenshot(Root+$"{scene}-{size.x}x{size.y}-menu-top.png");
foreach(var b in scroll.content.GetComponentsInChildren<Button>().Where(b=>b.gameObject.activeInHierarchy)){var rt=(RectTransform)b.transform;float center=-scroll.content.InverseTransformPoint(rt.TransformPoint(rt.rect.center)).y;float range=scroll.content.rect.height-scroll.viewport.rect.height;scroll.verticalNormalizedPosition=range<=0?1:1-Mathf.Clamp01((center-scroll.viewport.rect.height*.5f)/range);yield return new WaitForEndOfFrame();Pointer(b);}scroll.verticalNormalizedPosition=0;yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Root+$"{scene}-{size.x}x{size.y}-menu-bottom.png");
var background=h.Buttons.Single(b=>b.Id=="infinite-resources").View;var br=(RectTransform)background.transform;var hits=new System.Collections.Generic.List<RaycastResult>();h.Raycaster.Raycast(new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(null,br.TransformPoint(br.rect.center))},hits);Check(hits.Count>0&&hits[0].gameObject.transform.IsChildOf(m.Overlay.transform),"Underlying test UI blocked by modal");m.LoadConfirmation.SetActive(true);yield return new WaitForEndOfFrame();foreach(var b in m.LoadConfirmation.GetComponentsInChildren<Button>())Pointer(b);ScreenCapture.CaptureScreenshot(Root+$"{scene}-{size.x}x{size.y}-discard.png");m.LoadConfirmation.SetActive(false);h.Execute("fold:developer-body");yield return new WaitForEndOfFrame();Check(m.Developer.activeInHierarchy,"Developer tools entry remains available");Pointer(h.Buttons.Single(b=>b.Id=="developer-close").View);ScreenCapture.CaptureScreenshot(Root+$"{scene}-{size.x}x{size.y}-developer.png");m.Escape();Check(m.IsOpen&&!m.Developer.activeSelf,"Esc closes developer panel before menu");m.SetOpen(false);yield return new WaitForSecondsRealtime(.25f);Check(!h.Buttons.Single(b=>b.Id=="pause").View.gameObject.activeInHierarchy&&!h.Buttons.Single(b=>b.Id=="menu-fold").View.gameObject.activeInHierarchy,"Pause/save only in Esc menu");Check(background.gameObject.activeInHierarchy,"Test shortcuts remain on");result.Add(new JObject{{"width",size.x},{"height",size.y},{"fontPixels",18},{"allMenuButtonsReachable",true},{"backgroundInputBlocked",true},{"confirmationReachable",true}});}
SetHudReviewResolution.Main(2560,1440);File.WriteAllText(Root+scene+"-resolutions.json",result.ToString());File.WriteAllText(Root+scene+"-resolution-status.txt","PASS 7 resolutions");}}
public static class VerifyHud08MenuResolutions{public static string Main(){if(!Application.isPlaying||!(Environment.GetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT")??"").Contains("hud-08ab"))throw new Exception("Isolated Play required");new GameObject("Menu resolution verification",typeof(Hud08MenuMatrix)).hideFlags=HideFlags.HideAndDontSave;return "Queued menu resolution validation";}}
public static class SetHudReviewResolution
{
 public static string Main(int width=1920,int height=1080)
 {
  var assembly=typeof(EditorWindow).Assembly;var sizesType=assembly.GetType("UnityEditor.GameViewSizes");var singleton=typeof(ScriptableSingleton<>).MakeGenericType(sizesType);var sizes=singleton.GetProperty("instance").GetValue(null);
  var group=sizesType.GetMethod("GetGroup").Invoke(sizes,new object[]{0});var gt=group.GetType();int count=(int)gt.GetMethod("GetTotalCount").Invoke(group,null),index=-1;
  for(int i=0;i<count;i++){var size=gt.GetMethod("GetGameViewSize").Invoke(group,new object[]{i});var t=size.GetType();if((int)t.GetProperty("width").GetValue(size)==width&&(int)t.GetProperty("height").GetValue(size)==height){index=i;break;}}
  if(index<0){var type=assembly.GetType("UnityEditor.GameViewSize");var kind=assembly.GetType("UnityEditor.GameViewSizeType");var size=Activator.CreateInstance(type,new object[]{Enum.ToObject(kind,1),width,height,"HUD review "+width+"x"+height});gt.GetMethod("AddCustomSize").Invoke(group,new[]{size});index=count;}
  var viewType=assembly.GetType("UnityEditor.GameView");var view=EditorWindow.GetWindow(viewType);if(!SessionState.GetBool("HudReview.HasOriginal",false)){SessionState.SetInt("HudReview.SizeIndex",(int)viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).GetValue(view));SessionState.SetBool("HudReview.HasOriginal",true);}
  viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).SetValue(view,index);view.Show();view.Focus();view.Repaint();return width+"x"+height;
 }
}
