using UnityEditor;using System.Reflection;using System;using System.IO;using System.Linq;using System.Collections;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public sealed class Hud07PopupProbe:MonoBehaviour{
const string Root="Docs/Measurements/2026-10-02-hud-07/";void Check(bool ok,string why){if(!ok)throw new Exception(why);}
IEnumerator Start(){File.WriteAllText(Root+"popup-status.txt","RUNNING");var it=Verify();while(true){bool more;try{more=it.MoveNext();}catch(Exception e){File.WriteAllText(Root+"popup-status.txt","FAIL "+e);break;}if(!more)break;yield return it.Current;}Destroy(gameObject);}
IEnumerator Verify(){var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();h.GetComponent<GameplayHudWorkspace>().Construction();h.Groups.Select(true);var result=new JArray();foreach(var size in new[]{new Vector2Int(800,600),new Vector2Int(1024,768),new Vector2Int(1280,720),new Vector2Int(1920,1080),new Vector2Int(2560,1080),new Vector2Int(3840,1080),new Vector2Int(3840,2160)}){SetHudReviewResolution.Main(size.x,size.y);yield return new WaitForSecondsRealtime(.35f);foreach(var id in new[]{"menu-fold","power-fold"}){var button=h.Buttons.Single(b=>b.Id==id).View;button.onClick.Invoke();yield return null;h.Layout.Apply(true);Canvas.ForceUpdateCanvases();yield return new WaitForEndOfFrame();var panel=h.Layout.FloatingPanels.Single(p=>p.name==(id=="menu-fold"?"ProgressAndSave":"PowerDetails"));Check(panel.gameObject.activeInHierarchy,"Popup opened "+id);var corners=new Vector3[4];panel.GetWorldCorners(corners);Check(corners.All(p=>p.x>=-1&&p.y>=-1&&p.x<=Screen.width+1&&p.y<=Screen.height+1),"Popup bounds");foreach(var t in panel.GetComponentsInChildren<TMPro.TMP_Text>(true))Check(t.fontSize*t.transform.lossyScale.x>=17.9f,"Popup readable "+t.name);var scroll=panel.GetComponentInChildren<ScrollRect>(true);scroll.verticalNormalizedPosition=1;yield return new WaitForEndOfFrame();scroll.viewport.GetWorldCorners(corners);var pc=new Vector3[4];panel.GetWorldCorners(pc);Check(corners.All(p=>p.x>=pc[0].x&&p.y>=pc[0].y&&p.x<=pc[2].x&&p.y<=pc[2].y),"Viewport inside popup");
ScreenCapture.CaptureScreenshot(Root+$"popup-{size.x}x{size.y}-{id}.png");result.Add(new JObject{{"size",size.ToString()},{"panel",panel.name},{"fontPixelsMinimum",18},{"bounds",true}});foreach(var target in scroll.content.GetComponentsInChildren<Button>().Where(b=>b.gameObject.activeInHierarchy)){var rt=(RectTransform)target.transform;float center=-scroll.content.InverseTransformPoint(rt.TransformPoint(rt.rect.center)).y;float range=scroll.content.rect.height-scroll.viewport.rect.height;scroll.verticalNormalizedPosition=range<=0?1:1-Mathf.Clamp01((center-scroll.viewport.rect.height*.5f)/range);yield return new WaitForEndOfFrame();var hits=new System.Collections.Generic.List<RaycastResult>();h.Raycaster.Raycast(new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(null,rt.TransformPoint(rt.rect.center))},hits);Check(hits.Count>0&&(hits[0].gameObject==target.gameObject||hits[0].gameObject.transform.IsChildOf(target.transform)),"Popup button reachable "+target.name);}
scroll.verticalNormalizedPosition=0;yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Root+$"popup-{size.x}x{size.y}-{id}-bottom.png");button.onClick.Invoke();yield return null;}}SetHudReviewResolution.Main(2560,1440);File.WriteAllText(Root+"popups.json",result.ToString());File.WriteAllText(Root+"popup-status.txt","PASS");}}
public static class VerifyHud07Popups{public static string Main(){if(!Application.isPlaying||!(Environment.GetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT")??"").Contains("hud-07"))throw new Exception("Isolated Play required");new GameObject("Popup acceptance",typeof(Hud07PopupProbe)).hideFlags=HideFlags.HideAndDontSave;return "Queued popup acceptance";}}

public static class SetHudReviewResolution
{
 public static string Main(int width=1920,int height=1080)
 {
  var assembly=typeof(EditorWindow).Assembly;var sizesType=assembly.GetType("UnityEditor.GameViewSizes");var singleton=typeof(ScriptableSingleton<>).MakeGenericType(sizesType);var sizes=singleton.GetProperty("instance").GetValue(null);
  var group=sizesType.GetMethod("GetGroup").Invoke(sizes,new object[]{0});var gt=group.GetType();int count=(int)gt.GetMethod("GetTotalCount").Invoke(group,null),index=-1;
  for(int i=0;i<count;i++){var size=gt.GetMethod("GetGameViewSize").Invoke(group,new object[]{i});var t=size.GetType();if((int)t.GetProperty("width").GetValue(size)==width&&(int)t.GetProperty("height").GetValue(size)==height){index=i;break;}}
  if(index<0){var type=assembly.GetType("UnityEditor.GameViewSize");var kind=assembly.GetType("UnityEditor.GameViewSizeType");var size=Activator.CreateInstance(type,new object[]{Enum.ToObject(kind,1),width,height,"HUD review "+width+"x"+height});gt.GetMethod("AddCustomSize").Invoke(group,new[]{size});index=count;}
  var viewType=assembly.GetType("UnityEditor.GameView");var view=EditorWindow.GetWindow(viewType);if(!SessionState.GetBool("HudReview.HasOriginal",false)){SessionState.SetInt("HudReview.SizeIndex",(int)viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).GetValue(view));SessionState.SetBool("HudReview.HasOriginal",true);}
  viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).SetValue(view,index);view.Show();view.Focus();view.Repaint();return width+"x"+height;
 }
}
