using System;using System.IO;using System.Linq;using System.Collections;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using EternalSteam.OpenWorld;using EternalSteam.Railway;using Newtonsoft.Json.Linq;
public sealed class Hud06AProbe:MonoBehaviour{
const string Root="Docs/Measurements/2026-10-02-hud-06a/";RailwayOverview v;
void Check(bool ok,string why){if(!ok)throw new Exception(why);}
Button B(string command)=>v.Actions.Single(a=>a.Command==command).Button;
void Click(string command){v.Apply();Check(B(command).interactable,"Enabled "+command);B(command).onClick.Invoke();v.Apply();}
void Match(){foreach(var a in v.Actions.Where(a=>a.Command!="cargo"))Check(a.Button.interactable==v.Railway.CanExecute(a.Command,out _),"Core command agreement "+a.Command);}
void Pointer(Button b){var c=new Vector3[4];((RectTransform)b.transform).GetWorldCorners(c);var e=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(null,(c[0]+c[2])*.5f),button=PointerEventData.InputButton.Left};var hits=new System.Collections.Generic.List<RaycastResult>();v.Hud.Raycaster.Raycast(e,hits);Check(hits.Count>0&&(hits[0].gameObject==b.gameObject||hits[0].gameObject.transform.IsChildOf(b.transform)),"Unobscured "+b.name+" top="+(hits.Count>0?hits[0].gameObject.name:"none"));}
IEnumerator Start(){File.WriteAllText(Root+"play-status.txt","RUNNING");File.Delete(Root+"play-result.json");var it=Verify();while(true){bool next;try{next=it.MoveNext();}catch(Exception e){File.WriteAllText(Root+"play-status.txt","FAIL "+e);break;}if(!next)break;yield return it.Current;}Destroy(gameObject);}
IEnumerator Verify(){var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();v=h.Sandbox.RailwayHud.GetComponent<RailwayOverview>();var c=h.Sandbox.Content;var n=c.Railway.Network;var r=n.Routes.Single();h.Groups.Select(true);yield return new WaitForSecondsRealtime(.35f);v.Railway.Execute("open");v.Apply();Check(v.Rows[0].gameObject.activeSelf,"Actual route visible");v.Rows[0].onClick.Invoke();v.Apply();yield return null;Check(v.Railway.SelectedRoute==r&&v.IsOverview,"Row callback selects route");Match();yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Root+"overview-before.png");yield return null;Pointer(B("fuel"));
Click("fuel");Check(r.train.fuel>0,"Actual refuel");Click("start");Check(r.train.status==TrainStatus.Dwelling,"Actual start dwelling");Match();c.Railway.Tick(RailwayNetwork.DwellSeconds+.25);v.Apply();Check(r.train.status==TrainStatus.Moving,"Actual moving");Match();double fuel=r.train.fuel;Click("stop");Check(r.train.status==TrainStatus.StopRequested,"Stop requested");Match();c.Railway.Tick(r.CurrentLeg.cells.Count-r.train.progress);v.Apply();Check(r.train.status==TrainStatus.Stopped&&r.train.fuel==fuel,"Next-station stop without charging paid segment again");Match();
r.train.fuel=n.FuelCost(r.CurrentLeg);Click("start");c.Railway.Tick(2*RailwayNetwork.DwellSeconds+r.CurrentLeg.cells.Count+.1);v.Apply();Check(r.train.status==TrainStatus.FuelWait,"Actual fuel wait after one funded leg");Match();Check(v.DetailText.text.Contains("연료 부족 대기"),"Fuel wait presentation");r.train.waitingForStation=true;v.Apply();Check(v.DetailText.text.Contains("역 진입 대기")&&!B("fuel").interactable,"Station-entry wait presentation and gate");r.train.waitingForStation=false;r.train.status=TrainStatus.RouteError;r.error="UI 상태 fixture: 선로 오류";v.Apply();Check(v.DetailText.text.Contains(r.error),"Route error displayed");Match();r.error=null;r.train.status=TrainStatus.FuelWait;
Click("fuel");Click("start");for(int i=0;i<50&&r.train.status!=TrainStatus.Moving;i++)c.Railway.Tick(.25);Check(r.train.status==TrainStatus.Moving&&r.train.segmentPaid,"Moving paid segment for pending fixture");v.Apply();Click("edit");Check(v.Railway.HasDraft&&!v.IsOverview&&v.Legacy.blocksRaycasts,"Draft remains accessible in existing editor");v.Railway.Execute("validate");v.Railway.Execute("commit");v.Apply();Check(n.HasPending(r)&&v.IsOverview,"Pending edit returns to overview");fuel=r.train.fuel;Click("cancel-pending");Check(!n.HasPending(r)&&r.train.fuel==fuel&&r.train.segmentPaid,"Cancel pending does not change active paid segment");
Click("cargo");Check(!v.IsOverview&&v.Legacy.interactable,"Cargo details remains accessible");v.Railway.Load.SetTextWithoutNotify("7");h.Groups.Select(false);yield return new WaitForSecondsRealtime(.35f);h.Groups.Select(true);yield return new WaitForSecondsRealtime(.35f);Check(v.Railway.Load.text=="7"&&!v.IsOverview,"Group return preserves legacy input");v.LegacyBack.onClick.Invoke();v.Apply();Check(v.IsOverview&&v.Railway.SelectedRoute==r,"Return preserves selected route");
h.Groups.Select(false);yield return new WaitForSecondsRealtime(.35f);Check(v.QuietPanels.All(p=>p.alpha==1)&&v.ResourcePanel.alpha==1,"Common presentation restored in combat");h.Groups.Select(true);yield return new WaitForSecondsRealtime(.35f);Check(v.IsOverview&&v.Root.gameObject.activeInHierarchy,"Overview restored after group return");
File.WriteAllText(Root+"play-result.json",new JObject{{"result","PASS"},{"realRoute",true},{"refuelStartStop",true},{"fuelWait",true},{"waitingAndErrorPresentationFixture",true},{"pendingCancelKeepsPaidSegment",true},{"legacyInputSurvivesGroup",true},{"commandAgreement",true},{"researchExperiment",false}}.ToString());File.WriteAllText(Root+"play-status.txt","PASS");}
}
public static class VerifyHud06APlay{public static string Main(){if(!Application.isPlaying||!(Environment.GetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT")??"").Contains("hud-06a"))throw new Exception("Isolated Play required");new GameObject("Railway overview verification",typeof(Hud06AProbe)).hideFlags=HideFlags.HideAndDontSave;return "Queued actual railway command checks";}}
