using System;using System.IO;using System.Linq;using System.Collections;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using EternalSteam;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public sealed class Hud08EProbe:MonoBehaviour{
const string Root="Docs/Measurements/2026-10-03-hud-08e/";CanvasWorldHud h;
void Check(bool ok,string why){if(!ok)throw new Exception(why);}
Button B(string id)=>h.Buttons.Single(b=>b.Id==id).View;
void Click(Button b){Check(b.interactable,"Interactable "+b.name);b.onClick.Invoke();h.Refresh();}
IEnumerator Start(){File.WriteAllText(Root+"play-status.txt","RUNNING");File.Delete(Root+"play-result.json");var routine=Verify();while(true){bool next;try{next=routine.MoveNext();}catch(Exception e){File.WriteAllText(Root+"play-status.txt","FAIL "+e);break;}if(!next)break;yield return routine.Current;}Destroy(gameObject);}
IEnumerator Verify(){h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();h.Input.Cancel();h.Layout.CompactDock.CloseDetails();yield return new WaitForSecondsRealtime(.4f);var s=h.Sandbox;var input=h.Input;var c=s.Content;var workspace=h.GetComponent<GameplayHudWorkspace>();s.Persistence.Automatic=false;s.Clock.Paused=true;s.Running=false;c.InfiniteResources=false;var bank=c.Inventories.Available(c.Bases.SelectedBaseId);double stock=bank.Amount("iron");h.Groups.Select(true);yield return new WaitForSecondsRealtime(.35f);workspace.Construction();yield return new WaitForSecondsRealtime(.4f);Check(!input.IsEditing&&input.Edits.Count==0&&bank.Amount("iron")==stock,"Workspace open has no edit/payment side effect");Click(B("category-4"));Check(h.Catalog.Where(e=>e.View.gameObject.activeSelf).All(e=>e.Definition?.Id.StartsWith("railway.")==true),"Railway category uses shared catalog");var entry=h.Catalog.Single(e=>e.Definition?.Id=="railway.track");Click(entry.View);Check(input.IsEditing&&input.SelectedDefinition==entry.Definition,"Catalog click begins selected placement");Check(h.Texts.Single(t=>t.Id=="construction-summary").View.text.Contains("다음 1개 추가 후"),"Candidate cost is shown");
Vector3 point=default;bool found=false;var origin=c.MainBase.Cell;c.InfiniteResources=true;for(int z=-25;z<=25&&!found;z++)for(int x=-25;x<=25&&!found;x++){point=c.GroundWorld.Grid.Center(origin+new Vector2Int(x,z),entry.Definition.Footprint);found=input.Edits.PreviewContent(entry.Definition,point,out _,out _,out _,out _);}Check(found,"Valid track preview fixture");c.InfiniteResources=false;bank.Withdraw("iron",bank.Amount("iron"));Check(!input.Edits.PreviewContent(entry.Definition,point,out _,out _,out _,out _),"Finite stock shortage blocks preview");
Click(B("infinite-resources"));Check(c.InfiniteResources,"Infinite ON via saved UI");Check(input.ClickWorld(point)&&input.Edits.Count==1,"World click reserves selected card");h.Refresh();int reservations=c.GroundWorld.Grid.ReservationCount;string payer=c.Bases.SelectedBaseId;workspace.Railways();Check(input.Edits.Count==1&&!s.RailwayHud.Panel.activeSelf&&input.SelectedDefinition==entry.Definition,"Rail switch rejects without discarding construction draft");h.Execute("edit");Check(input.Edits.Count==1,"Edit end cannot silently cancel pending work");h.Groups.Select(false);yield return new WaitForSecondsRealtime(.35f);h.Groups.Select(true);yield return new WaitForSecondsRealtime(.35f);Check(input.Edits.Count==1&&c.GroundWorld.Grid.ReservationCount==reservations&&c.Bases.SelectedBaseId==payer,"Combat return preserves draft reservation and payer");
Click(B("infinite-resources"));Check(!c.InfiniteResources&&!B("confirm").interactable,"Infinite OFF rechecks affordability");h.Execute("confirm");Check(input.Edits.Count==1,"Failed confirmation preserves draft");bank.Deposit("iron",10);h.Refresh();Check(B("confirm").interactable,"Deposit enables affordable confirmation");yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Root+"workflow-construction.png");yield return null;
var b=B("confirm");var corners=new Vector3[4];((RectTransform)b.transform).GetWorldCorners(corners);var pointer=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(null,(corners[0]+corners[2])*.5f),button=PointerEventData.InputButton.Left};var hits=new System.Collections.Generic.List<RaycastResult>();h.Raycaster.Raycast(pointer,hits);Check(hits.Count>0&&(hits[0].gameObject==b.gameObject||hits[0].gameObject.transform.IsChildOf(b.transform)),"Confirmation is not obscured");double before=bank.Amount("iron");ExecuteEvents.Execute(b.gameObject,pointer,ExecuteEvents.pointerClickHandler);Check(!input.IsEditing&&input.Edits.Count==0&&Math.Abs(bank.Amount("iron")-(before-1))<.001,"Confirmation commits once at actual price");
Click(entry.View);found=false;for(int z=-25;z<=25&&!found;z++)for(int x=-25;x<=25&&!found;x++){point=c.GroundWorld.Grid.Center(origin+new Vector2Int(x,z),entry.Definition.Footprint);found=input.Edits.PreviewContent(entry.Definition,point,out _,out _,out _,out _);}Check(found&&input.ClickWorld(point),"Second reservation for cancellation");before=bank.Amount("iron");h.Refresh();Click(B("cancel"));Check(!input.IsEditing&&input.Edits.Count==0&&c.GroundWorld.Grid.ReservationCount==0&&bank.Amount("iron")==before,"Cancel releases reservations without payment");workspace.Railways();Check(s.RailwayHud.Panel.activeSelf,"Rail workspace opens after resolution");workspace.Construction();Check(!s.RailwayHud.Panel.activeSelf&&!input.IsEditing,"Return to catalogue has no new edit");
File.WriteAllText(Root+"play-result.json",new JObject{{"result","PASS"},{"catalogToWorldPlacement",true},{"candidateAndPendingCost",true},{"finiteShortage",true},{"infiniteToggleRevalidation",true},{"confirmationPaidOnce",true},{"cancelWithoutPayment",true},{"combatReturnPreservesDraft",true},{"railSwitchProtectsDraft",true},{"confirmPointerUnobscured",true},{"researchExperiment",false}}.ToString());File.WriteAllText(Root+"play-status.txt","PASS");}
}
public static class VerifyHud08EPlay{public static string Main(){if(!Application.isPlaying||!(Environment.GetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT")??"").Contains("hud-08e"))throw new Exception("Isolated product fixture required");new GameObject("Construction workflow verification",typeof(Hud08EProbe)).hideFlags=HideFlags.HideAndDontSave;return "Queued construction workflow checks";}}
