using System;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using EternalSteam;
using EternalSteam.OpenWorld;
using EternalSteam.Demo;
public static class VerifyNexusGroundDefense
{
 sealed class Receiver:IDamageReceiver{public bool Alive=>true;public int Hits;public void ApplyDamage(float value){Hits++;}}
 static void Check(bool v,string msg){if(!v)throw new Exception(msg);}
 public static async System.Threading.Tasks.Task<string> Main(){Check(Application.isPlaying,"Play required");var s=UnityEngine.Object.FindFirstObjectByType<OpenWorldSandbox>();var root=new GameObject("Nexus isolated regression");var data=new TerrainData{heightmapResolution=33,size=new Vector3(256,10,256)};var go=Terrain.CreateTerrainGameObject(data);go.transform.position=new Vector3(2000,0,2000);var terrain=go.GetComponent<Terrain>();var towers=new List<HordeTower>();var targets=new TargetRegistry();var receiver=new Receiver();var content=new OpenWorldContent(terrain,root.transform,s.LineMaterial,targets,8);var placement=new FoundationPlacement(terrain,root.transform,towers,s.FoundationMaterial,s.BarrelMaterial,s.LineMaterial,s.ValidMaterial,new Material[4],new Material[4],s.FoundationPrefab,s.TowerPrefabs,content);content.Attach(placement);placement.AttachGround();var edit=new WorldEditSession(placement,s.LineMaterial,content){legacyGroundTowers=towers};
 try{
 var catalog=AssetDatabase.LoadAssetAtPath<BuildingCatalog>("Assets/EternalSteam/Content/Buildings/DocumentContent/DocumentBuildings.asset");var nexusDef=catalog.Buildings.Single(d=>d.Id=="installation.nexus");var defenses=catalog.Buildings.Where(d=>d.Category==BuildingCategory.Defense).ToArray();Check(defenses.Length==9&&defenses.All(d=>d.Placement.Surface==BuildingSurface.GroundOrFoundation),"Nine defense profiles");var point=new Vector3(2100,0,2100);Check(!edit.AddContent(defenses[0],point,Vector3.forward,out _),"No nexus rejects defense");Check(edit.AddContent(nexusDef,point,Vector3.forward,out var reason),reason);Check(root.GetComponentsInChildren<NexusGridView>().Length==0,"No pending grid");Check(edit.Confirm().Success,"Nexus commit");var nexus=content.GroundWorld.Buildings.Single();Check(root.GetComponentsInChildren<NexusGridView>().Length==1,"Confirmed nexus generates one grid mesh");var gridView=root.GetComponentInChildren<NexusGridView>();Check(gridView.GetComponent<MeshFilter>().sharedMesh.vertexCount>1000&&gridView.GetComponent<Collider>()==null,"Grid geometry without collider");var near=nexus.Position+WorldGridGeometry.ToWorld(new Vector3(12,0,0));
 Check(!edit.AddContent(defenses[0],nexus.Position+Vector3.right*50,Vector3.forward,out _),"Outside defense rejected");
 foreach(var d in defenses){Check(edit.AddContent(d,near,Vector3.forward,out reason),d.Id+reason);Check(content.GroundWorld.Grid.ReservationCount==d.Footprint.x*d.Footprint.y,"Correct ground reservation");Check(!edit.AddContent(d,near,Vector3.forward,out _),"Duplicate ground reservation rejected");Check(edit.Confirm().Success,"Ground defense commit "+d.Id);var b=content.GroundWorld.Buildings.Single(x=>x.Module<WeaponRuntime>()!=null);Check(b.RequiresBuildArea,"Ground defense participates in recovery guard");if(d.Id=="defense.tesla"){targets.Register(1,b.Position+Vector3.forward*5,TargetKind.Ground,receiver);content.TickProduction(1);Check(receiver.Hits==0,"No ground combat during preparation");content.Tick(.1f);Check(receiver.Hits>0,"Ground weapon fires during combat");}Check(edit.ToggleGroundRecovery(nexus,out reason),reason);Check(!edit.Confirm().Success,"Nexus recovery blocked by ground defense");edit.Cancel();Check(edit.ToggleGroundRecovery(b,out reason)&&edit.Confirm().Success,"Ground defense recovery");}
 foreach(HordeTowerKind kind in Enum.GetValues(typeof(HordeTowerKind))){Check(edit.AddTower(near,Vector3.forward,kind,out reason),"Legacy ground ghost "+reason);edit.Cancel();Check(content.GroundWorld.Grid.ReservationCount==0,"Legacy cancel releases cells");Check(edit.AddTower(near,Vector3.forward,kind,out reason)&&edit.Confirm().Success,"Legacy ground commit "+kind+reason);Check(towers.Count==1&&placement.Platforms.Count==0,"Legacy ground registered without fake foundation");var b=towers[0].building;Check(b.RequiresBuildArea,"Legacy ground dependency");Check(edit.ToggleGroundRecovery(b,out reason)&&edit.Confirm().Success&&towers.Count==0,"Legacy ground recovery cleanup");}
 var fpoint=nexus.Position+WorldGridGeometry.ToWorld(new Vector3(16,0,16));Check(edit.AddFoundation(fpoint,out reason)&&edit.Confirm().Success,"Optional foundation");var platform=placement.Platforms.Single();var anchor=platform.World.Grid.Center(Vector2Int.zero,Vector2Int.one);var large=defenses.First(d=>d.Footprint.x==3);Check(edit.AddContent(large,anchor,Vector3.forward,out reason)&&edit.Confirm().Success,"Large tower still installs on foundation");Check(platform.World.Buildings.Count==1,"Uses foundation occupancy");Check(edit.ToggleFoundationRecovery(platform,towers,out reason)&&edit.Confirm().Success,"Foundation with content recovers");
 Check(edit.AddContent(large,near,Vector3.forward,out reason),reason);Check(!edit.AddFoundation(near,out _),"Pending ground tower blocks foundation");edit.Cancel();Check(edit.AddFoundation(near,out reason),reason);Check(!edit.AddContent(large,near,Vector3.forward,out _),"Pending foundation blocks ground tower");edit.Cancel();
 // Keep one sample of each footprint for the visual check.
 for(int i=0;i<3;i++){var d=defenses.First(x=>x.Footprint.x==i+1);var p=nexus.Position+WorldGridGeometry.ToWorld(new Vector3(-16+i*14,0,14));Check(edit.AddContent(d,p,Vector3.forward,out reason)&&edit.Confirm().Success,"Preview sample");}
 await System.Threading.Tasks.Task.Delay(100);
 var preview=new PreviewRenderUtility();try{preview.AddSingleGO(UnityEngine.Object.Instantiate(root));preview.camera.backgroundColor=new Color(.055f,.08f,.1f);preview.camera.clearFlags=CameraClearFlags.SolidColor;preview.camera.nearClipPlane=.1f;preview.camera.farClipPlane=200;preview.camera.fieldOfView=50;preview.camera.transform.position=nexus.Position+new Vector3(0,68,-58);preview.camera.transform.LookAt(nexus.Position);preview.lights[0].intensity=1.4f;preview.lights[0].transform.rotation=Quaternion.Euler(50,30,0);preview.BeginStaticPreview(new Rect(0,0,1000,800));preview.Render(true);var image=preview.EndStaticPreview();System.IO.File.WriteAllBytes("/tmp/nexus-ground-grid.png",image.EncodeToPNG());UnityEngine.Object.DestroyImmediate(image);}finally{preview.Cleanup();}
 return "PASS: confirmed-only grid, 9 new and 4 legacy ground towers, 1/4/9-cell occupancy, range/duplicate checks, prepare silence/combat damage, deferred recovery, nexus dependency, optional foundation compatibility, cross-surface pending collision and cleanup.";
 }finally{edit.Dispose();placement.Dispose();content.Dispose();placement.GroundPlatform.Factory.Dispose();UnityEngine.Object.Destroy(root);UnityEngine.Object.Destroy(go);UnityEngine.Object.Destroy(data);}
 }
}
