using System;using System.IO;using System.Linq;using System.Collections;using System.Reflection;using UnityEditor;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public sealed class Hud08DockProbe:MonoBehaviour{
const string Root="Docs/Measurements/2026-10-03-performance/dock/";CanvasWorldHud h;CompactConstructionDock d;int errors;
void Log(string s,string stack,LogType type){if(type==LogType.Error||type==LogType.Exception)errors++;}void Check(bool b,string why){if(!b)throw new Exception(why);}
Rect Bounds(RectTransform r){var p=new Vector3[4];r.GetWorldCorners(p);return Rect.MinMaxRect(p[0].x,p[0].y,p[2].x,p[2].y);}Button B(string id)=>h.Buttons.Single(x=>x.Id==id).View;
void Pointer(Button b){Check(b.gameObject.activeInHierarchy,"Active "+b.name);var rect=Bounds((RectTransform)b.transform);Check(rect.xMin>=-1&&rect.yMin>=-1&&rect.xMax<=Screen.width+1&&rect.yMax<=Screen.height+1,"Screen bounds "+b.name);var hits=new System.Collections.Generic.List<RaycastResult>();h.Raycaster.Raycast(new PointerEventData(EventSystem.current){position=rect.center},hits);Check(hits.Count>0&&(hits[0].gameObject==b.gameObject||hits[0].gameObject.transform.IsChildOf(b.transform)),"Pointer "+b.name+" top="+(hits.Count>0?hits[0].gameObject.name:"none"));}
void ScrollTo(ScrollRect scroll,RectTransform target){Canvas.ForceUpdateCanvases();float x=scroll.content.InverseTransformPoint(target.TransformPoint(target.rect.center)).x-scroll.content.rect.xMin;float range=scroll.content.rect.width-scroll.viewport.rect.width;scroll.horizontalNormalizedPosition=range<=0?0:Mathf.Clamp01((x-scroll.viewport.rect.width*.5f)/range);}
IEnumerator Start(){string name=UnityEngine.SceneManagement.SceneManager.GetActiveScene().name;File.WriteAllText(Root+name+"-status.txt","RUNNING");Application.logMessageReceived+=Log;var it=Verify();while(true){bool more;try{more=it.MoveNext();}catch(Exception e){File.WriteAllText(Root+name+"-status.txt","FAIL "+e);break;}if(!more)break;yield return it.Current;}Application.logMessageReceived-=Log;Destroy(gameObject);}
IEnumerator Verify(){h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();d=h.Layout.CompactDock;var s=h.Sandbox;s.Clock.Paused=true;if(s.Persistence!=null)s.Persistence.Automatic=false;h.Input.Cancel();d.CloseDetails();h.Groups.Select(true);yield return new WaitForSecondsRealtime(.4f);var workspace=h.GetComponent<GameplayHudWorkspace>();workspace.Construction();var scene=UnityEngine.SceneManagement.SceneManager.GetActiveScene().name;var rows=new JArray();
foreach(var size in new[]{new Vector2Int(800,600),new Vector2Int(1024,768),new Vector2Int(1280,720),new Vector2Int(1920,1080),new Vector2Int(2560,1080),new Vector2Int(3840,1080),new Vector2Int(3840,2160)}){
SetHudReviewResolution.Main(size.x,size.y);yield return new WaitForSecondsRealtime(.4f);h.Layout.Apply(true);yield return new WaitForEndOfFrame();yield return new WaitForEndOfFrame();
var bar=Bounds(h.Layout.ConstructionBar);float browseTop=bar.yMax;Check(Bounds(h.Layout.ResourcePanel).yMax<=Bounds(d.PowerSummary).yMin-7.9f,"Resource list clears power summary");Check(bar.yMax<=size.y*.3f+.1f&&bar.width<=1280.1f,"Browse footprint");Check(bar.xMin>=15&&bar.xMax<=size.x-15,"Dock horizontal margins");Pointer(workspace.ConstructionTab);Pointer(workspace.RailwayTab);Pointer(B("edit"));Pointer(B("power-fold"));
var category=d.CategoryScroll.GetComponent<ScrollRect>();foreach(int c in new[]{-1,0,1,2,3,4,-1}){var button=B("category-"+c);ScrollTo(category,(RectTransform)button.transform);yield return new WaitForEndOfFrame();Pointer(button);button.onClick.Invoke();yield return null;}
foreach(var e in h.Catalog.Where(e=>e.View.gameObject.activeSelf)){ScrollTo(d.CatalogScroll,(RectTransform)e.View.transform);yield return new WaitForEndOfFrame();Pointer(e.View);}
var entry=h.Catalog.First(c=>c.Definition?.Id=="railway.track");ScrollTo(d.CatalogScroll,(RectTransform)entry.View.transform);yield return new WaitForEndOfFrame();float savedScroll=d.CatalogScroll.horizontalNormalizedPosition;ScreenCapture.CaptureScreenshot(Root+$"{scene}-{size.x}x{size.y}-browse.png");entry.View.onClick.Invoke();d.Apply(.06f);Check(d.Transitioning&&d.Browse.gameObject.activeSelf&&!d.Browse.blocksRaycasts&&!d.DockInput.interactable,"Outgoing content eases with input locked");yield return new WaitForSecondsRealtime(.4f);yield return new WaitForEndOfFrame();Canvas.ForceUpdateCanvases();bar=Bounds(h.Layout.ConstructionBar);Check(d.Placing&&bar.yMax<=96.1f&&bar.yMax<=size.y*.18f+.1f,"Placement footprint placing="+d.Placing+" top="+bar.yMax+" transition="+d.Transitioning);var center=new Rect(size.x*.3f,size.y*.3f,size.x*.4f,size.y*.4f);foreach(var r in new[]{h.Layout.ConstructionBar,h.Layout.ResourcePanel,d.GoalStrip})if(r.gameObject.activeInHierarchy)Check(!Bounds(r).Overlaps(center),"Central placement area "+r.name);
foreach(var b in new[]{B("confirm"),B("cancel"),d.ListButton,d.CostButton})Pointer(b);
Check(Mathf.Abs(d.PlacementTitle.fontSize*d.PlacementTitle.transform.lossyScale.x-18)<.1f&&Mathf.Abs(d.CostBrief.fontSize*d.CostBrief.transform.lossyScale.x-14)<.1f,"Readable physical fonts");Check(d.PlacementTitle.GetPreferredValues().y<=d.PlacementTitle.rectTransform.rect.height+.1f,"Title vertical fit");Check(d.CostBrief.GetPreferredValues().y<=d.CostBrief.rectTransform.rect.height+.1f,"Cost vertical fit");ScreenCapture.CaptureScreenshot(Root+$"{scene}-{size.x}x{size.y}-placement.png");
d.Execute("cost");yield return new WaitForEndOfFrame();Pointer(d.CostPanel.GetComponentInChildren<Button>());Pointer(B("confirm"));Check(!d.GoalPanel.gameObject.activeSelf,"One detail at a time");ScreenCapture.CaptureScreenshot(Root+$"{scene}-{size.x}x{size.y}-cost.png");d.Execute("close-cost");
d.Execute("list");yield return new WaitForSecondsRealtime(.4f);yield return new WaitForEndOfFrame();Check(h.Input.IsEditing&&!d.Placing&&Mathf.Abs(d.CatalogScroll.horizontalNormalizedPosition-savedScroll)<.01,"List preserves editing and scroll");Pointer(d.ResumeButton);d.Execute("resume");yield return new WaitForSecondsRealtime(.4f);yield return new WaitForEndOfFrame();Check(d.Placing,"Resume placement");
h.Groups.Select(false);yield return new WaitForSecondsRealtime(.4f);yield return new WaitForEndOfFrame();h.Groups.Select(true);yield return new WaitForSecondsRealtime(.4f);yield return new WaitForEndOfFrame();Check(d.Placing&&h.Input.SelectedDefinition==entry.Definition,"Tab preserves selection");h.Execute("cancel");yield return new WaitForSecondsRealtime(.4f);yield return new WaitForEndOfFrame();Check(!h.Input.IsEditing&&!d.Placing,"Cancel returns to browse");
if(s.Assault!=null){d.Execute("goal");yield return new WaitForEndOfFrame();Pointer(d.GoalPanel.GetComponentInChildren<Button>());ScreenCapture.CaptureScreenshot(Root+$"{scene}-{size.x}x{size.y}-goal.png");d.Execute("close-goal");}
workspace.Railways();yield return new WaitForSecondsRealtime(.4f);yield return new WaitForEndOfFrame();if(s.Content.BaseRules){Check(s.RailwayHud.Panel.activeSelf&&!d.Browse.gameObject.activeSelf,"Rail hides construction catalog");Check(Bounds(h.Layout.ConstructionBar).yMax<=68.1f,"Compact rail toolbar");}else Check(!s.RailwayHud.Panel.activeSelf&&d.Browse.gameObject.activeSelf&&s.Message.Contains("StartRegionSandbox"),"Unsupported rail preserves catalog and explains availability");Pointer(workspace.ConstructionTab);workspace.Construction();yield return new WaitForSecondsRealtime(.4f);yield return new WaitForEndOfFrame();Check(d.Browse.gameObject.activeInHierarchy,"Construction return");
rows.Add(new JObject{{"width",size.x},{"height",size.y},{"browseHeightWithMargin",browseTop},{"placementHeightWithMargin",bar.yMax},{"centralAreaClear",true},{"catalogAndCategoryReachable",true},{"detailsAndActionsReachable",true},{"scrollAndSelectionPreserved",true}});
}
Check(errors==0,"Runtime errors "+errors);SetHudReviewResolution.Main(2560,1440);File.WriteAllText(Root+scene+"-results.json",new JObject{{"result","PASS"},{"runtimeErrors",errors},{"cases",rows}}.ToString());File.WriteAllText(Root+scene+"-status.txt","PASS 7 resolutions");}}
public static class VerifyHud08EDock{public static string Main(){if(!Application.isPlaying||!(Environment.GetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT")??"").Contains("performance"))throw new Exception("Isolated Play required");new GameObject("Compact construction verification",typeof(Hud08DockProbe)).hideFlags=HideFlags.HideAndDontSave;return "Queued dock matrix";}}
public static class SetHudReviewResolution
{
 public static string Main(int width=1920,int height=1080)
 {
  var assembly=typeof(EditorWindow).Assembly;var sizesType=assembly.GetType("UnityEditor.GameViewSizes");var singleton=typeof(ScriptableSingleton<>).MakeGenericType(sizesType);var sizes=singleton.GetProperty("instance").GetValue(null);
  var group=sizesType.GetMethod("GetGroup").Invoke(sizes,new object[]{0});var gt=group.GetType();int count=(int)gt.GetMethod("GetTotalCount").Invoke(group,null),index=-1;
  for(int i=0;i<count;i++){var size=gt.GetMethod("GetGameViewSize").Invoke(group,new object[]{i});var t=size.GetType();if((int)t.GetProperty("width").GetValue(size)==width&&(int)t.GetProperty("height").GetValue(size)==height){index=i;break;}}
  if(index<0){var type=assembly.GetType("UnityEditor.GameViewSize");var kind=assembly.GetType("UnityEditor.GameViewSizeType");var size=Activator.CreateInstance(type,new object[]{Enum.ToObject(kind,1),width,height,"HUD review "+width+"x"+height});gt.GetMethod("AddCustomSize").Invoke(group,new[]{size});index=count;}
  var viewType=assembly.GetType("UnityEditor.GameView");var view=EditorWindow.GetWindow(viewType);if(!SessionState.GetBool("HudReview.HasOriginal",false)){SessionState.SetInt("HudReview.SizeIndex",(int)viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).GetValue(view));SessionState.SetBool("HudReview.HasOriginal",true);}
  viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).SetValue(view,index);view.Show();view.Focus();view.Repaint();return width+"x"+height;
 }
}
