using System;using System.IO;using System.Linq;using System.Collections;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public sealed class HudGroupsProbe:MonoBehaviour{
 const string Root="Docs/Measurements/2026-10-02-hud-groups/";
 void Check(bool ok,string why){if(!ok)throw new Exception(why);}
 IEnumerator Start(){var routine=Verify();while(true){bool next;try{next=routine.MoveNext();}catch(Exception e){File.WriteAllText(Root+"play-status.txt","FAIL "+e);break;}if(!next)break;yield return routine.Current;}Destroy(gameObject);}
 IEnumerator Verify(){var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();var g=h.Groups;var s=h.Sandbox;if(s.Persistence!=null)s.Persistence.Automatic=false;s.Clock.Paused=true;yield return null;yield return new WaitForEndOfFrame();
 Check(!g.ConstructionSelected&&g.Combat.gameObject.activeInHierarchy,"Combat default");Check(h.Layout.MapPanel.gameObject.activeInHierarchy,"Combat map visible");Check(!h.Layout.ResourcePanel.gameObject.activeInHierarchy,"Resources in construction only");ScreenCapture.CaptureScreenshot(Root+"combat.png");yield return null;
 var rect=h.Minimap.VisibleWorldBounds;Check(Mathf.Approximately(rect.width,150)&&Mathf.Approximately(rect.height,150),"Local minimap range");var before=rect.center;var focus=s.CameraRig.Focus;s.CameraRig.MoveFocus(focus+Vector3.right*20);yield return null;yield return new WaitForSecondsRealtime(.12f);Check(Vector2.Distance(before,h.Minimap.VisibleWorldBounds.center)>1,"Minimap follows view");s.CameraRig.MoveFocus(focus);
 var toggle=g.ModeLabel.GetComponentInParent<Button>();var corners=new Vector3[4];((RectTransform)toggle.transform).GetWorldCorners(corners);var pos=RectTransformUtility.WorldToScreenPoint(null,(corners[0]+corners[2])*.5f);var e=new PointerEventData(EventSystem.current){position=pos,button=PointerEventData.InputButton.Left};var hits=new System.Collections.Generic.List<RaycastResult>();h.Raycaster.Raycast(e,hits);Check(hits.Any(hit=>hit.gameObject==toggle.gameObject||hit.gameObject.transform.IsChildOf(toggle.transform)),"Toggle raycast");ExecuteEvents.Execute(toggle.gameObject,e,ExecuteEvents.pointerClickHandler);Check(g.Transitioning&&!g.Construction.interactable,"Transition gates input");yield return new WaitForSecondsRealtime(.32f);Check(g.CanUseConstruction&&!g.Combat.gameObject.activeInHierarchy,"Construction completes while paused");Check(h.Layout.ResourcePanel.gameObject.activeInHierarchy,"Construction resources visible");Check(!h.Input.IsEditing,"Group alone does not begin editing");yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Root+"construction.png");
 h.Input.BeginEditing();var tool=h.Input.Tool;g.Select(false);yield return new WaitForSecondsRealtime(.32f);Check(h.Input.Tool==tool,"Editing state retained");g.Select(true);yield return new WaitForSecondsRealtime(.08f);g.Select(false);yield return new WaitForSecondsRealtime(.08f);g.Select(true);yield return new WaitForSecondsRealtime(.32f);Check(g.CanUseConstruction&&h.Input.Tool==tool,"Rapid reversal retains editing");h.Input.Cancel();
 foreach(var id in new[]{"infinite-resources","quick-day","quick-night"})Check(h.Buttons.Single(b=>b.Id==id).View.gameObject.activeInHierarchy,"Common test control "+id);
 g.Select(false);yield return new WaitForSecondsRealtime(.32f);var result=new JObject{{"result","PASS"},{"defaultCombat",true},{"toggleRaycast",true},{"pausedTransition",true},{"rapidReversal",true},{"editingPreserved",true},{"minimapSide",150},{"minimapTracksView",true},{"testControlsVisible",true},{"researchExperiment",false}};File.WriteAllText(Root+"play-result.json",result.ToString());File.WriteAllText(Root+"play-status.txt","PASS");}
}
public static class VerifyHudGroupsPlay{public static string Main(){if(!Application.isPlaying||!(Environment.GetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT")??"").Contains("2026-10-02-hud-groups"))throw new Exception("Project-local isolated play required");new GameObject("HUD groups verification",typeof(HudGroupsProbe)).hideFlags=HideFlags.HideAndDontSave;return "Queued product UI validation";}}
