using UnityEditor;using System.Reflection;using System;using System.IO;using System.Linq;using System.Collections;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public sealed class Hud05ResolutionProbe:MonoBehaviour{
const string Root="Docs/Measurements/2026-10-02-hud-05/";void Check(bool ok,string why){if(!ok)throw new Exception(why);}
void Bounds(RectTransform t){var corners=new Vector3[4];t.GetWorldCorners(corners);foreach(var c in corners){var p=RectTransformUtility.WorldToScreenPoint(null,c);Check(p.x>=-1&&p.y>=-1&&p.x<=Screen.width+1&&p.y<=Screen.height+1,"Bounds "+t.name);}}
IEnumerator Start(){var it=Verify();while(true){bool next;try{next=it.MoveNext();}catch(Exception e){File.WriteAllText(Root+"resolution-status.txt","FAIL "+e);break;}if(!next)break;yield return it.Current;}Destroy(gameObject);}
IEnumerator Verify(){var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();h.Groups.Select(true);h.Execute("category:4");h.Input.BeginEditing();h.Input.SelectContent(h.Catalog.Single(e=>e.Definition?.Id=="railway.track").Definition);var results=new JArray();foreach(var size in new[]{new Vector2Int(800,600),new Vector2Int(1280,720),new Vector2Int(1920,1080),new Vector2Int(3840,1080)}){SetHudReviewResolution.Main(size.x,size.y);yield return null;yield return null;h.Layout.Apply(true);yield return new WaitForSecondsRealtime(.4f);Canvas.ForceUpdateCanvases();Bounds(h.Layout.ConstructionBar);Bounds(h.Layout.ConstructionSummary);Bounds(h.Layout.ResourcePanel);var catalog=h.CatalogLayout.GetComponentInParent<ScrollRect>();Check(catalog.viewport.rect.height+.1f>=h.CatalogLayout.cellSize.y,"Entire catalog card height");foreach(var id in new[]{"confirm","cancel"}){var button=h.Buttons.Single(b=>b.Id==id).View;Bounds((RectTransform)button.transform);var corners=new Vector3[4];((RectTransform)button.transform).GetWorldCorners(corners);var pointer=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(null,(corners[0]+corners[2])*.5f)};var hits=new System.Collections.Generic.List<RaycastResult>();h.Raycaster.Raycast(pointer,hits);Check(hits.Count>0&&(hits[0].gameObject==button.gameObject||hits[0].gameObject.transform.IsChildOf(button.transform)),"Unobscured "+id);}
yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Root+$"construction-{size.x}x{size.y}.png");results.Add(new JObject{{"width",size.x},{"height",size.y},{"bounds",true},{"cardHeight",true},{"actionsUnobscured",true}});}
SetHudReviewResolution.Main(2560,1440);File.WriteAllText(Root+"resolutions.json",results.ToString());File.WriteAllText(Root+"resolution-status.txt","PASS");}
}
public static class VerifyHud05Resolutions{public static string Main(){if(!Application.isPlaying||!(Environment.GetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT")??"").Contains("hud-05"))throw new Exception("Isolated Play required");new GameObject("Construction resolution verification",typeof(Hud05ResolutionProbe)).hideFlags=HideFlags.HideAndDontSave;return "Queued four resolution checks";}}

public static class SetHudReviewResolution
{
 public static string Main(int width=1920,int height=1080)
 {
  var assembly=typeof(EditorWindow).Assembly;var sizesType=assembly.GetType("UnityEditor.GameViewSizes");var singleton=typeof(ScriptableSingleton<>).MakeGenericType(sizesType);var sizes=singleton.GetProperty("instance").GetValue(null);
  var group=sizesType.GetMethod("GetGroup").Invoke(sizes,new object[]{0});var gt=group.GetType();int count=(int)gt.GetMethod("GetTotalCount").Invoke(group,null),index=-1;
  for(int i=0;i<count;i++){var size=gt.GetMethod("GetGameViewSize").Invoke(group,new object[]{i});var t=size.GetType();if((int)t.GetProperty("width").GetValue(size)==width&&(int)t.GetProperty("height").GetValue(size)==height){index=i;break;}}
  if(index<0){var type=assembly.GetType("UnityEditor.GameViewSize");var kind=assembly.GetType("UnityEditor.GameViewSizeType");var size=Activator.CreateInstance(type,new object[]{Enum.ToObject(kind,1),width,height,"HUD review "+width+"x"+height});gt.GetMethod("AddCustomSize").Invoke(group,new[]{size});index=count;}
  var viewType=assembly.GetType("UnityEditor.GameView");var view=EditorWindow.GetWindow(viewType);if(!SessionState.GetBool("HudReview.HasOriginal",false)){SessionState.SetInt("HudReview.SizeIndex",(int)viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).GetValue(view));SessionState.SetBool("HudReview.HasOriginal",true);}
  viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).SetValue(view,index);view.Show();view.Focus();view.Repaint();return width+"x"+height;
 }
}
