using UnityEditor;using System.Reflection;using System;using System.IO;using System.Linq;using System.Collections;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public sealed class Hud07ServiceMatrixProbe:MonoBehaviour{
const string Root="Docs/Measurements/2026-10-03-hud-08e/services/";void Check(bool ok,string why){if(!ok)throw new Exception(why);}
void Pointer(RailwayOverview v,Selectable b){var corners=new Vector3[4];((RectTransform)b.transform).GetWorldCorners(corners);foreach(var c in corners){var p=RectTransformUtility.WorldToScreenPoint(null,c);Check(p.x>=-1&&p.y>=-1&&p.x<=Screen.width+1&&p.y<=Screen.height+1,"Bounds "+b.name);}var e=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(null,(corners[0]+corners[2])*.5f)};var hits=new System.Collections.Generic.List<RaycastResult>();v.Hud.Raycaster.Raycast(e,hits);Check(hits.Count>0&&(hits[0].gameObject==b.gameObject||hits[0].gameObject.transform.IsChildOf(b.transform)),"Pointer "+b.name+" top="+(hits.Count>0?hits[0].gameObject.name:"none"));}
IEnumerator Start(){File.WriteAllText(Root+"resolution-status.txt","RUNNING");var it=Verify();while(true){bool next;try{next=it.MoveNext();}catch(Exception e){File.WriteAllText(Root+"resolution-status.txt","FAIL "+e);break;}if(!next)break;yield return it.Current;}Destroy(gameObject);}
IEnumerator Verify(){var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();var v=h.Sandbox.RailwayHud.GetComponent<RailwayOverview>();var s=v.Services;h.Groups.Select(true);var results=new JArray();foreach(var size in new[]{new Vector2Int(800,600),new Vector2Int(1024,768),new Vector2Int(1280,720),new Vector2Int(1920,1080),new Vector2Int(2560,1080),new Vector2Int(3840,1080),new Vector2Int(3840,2160)}){SetHudReviewResolution.Main(size.x,size.y);yield return new WaitForSecondsRealtime(.4f);foreach(var mode in new[]{"cargo","defense"}){v.Execute("overview");v.Execute(mode);yield return null;yield return new WaitForEndOfFrame();v.Apply();Canvas.ForceUpdateCanvases();var scroll=s.Scroll.GetComponent<ScrollRect>();scroll.verticalNormalizedPosition=1;yield return new WaitForEndOfFrame();Pointer(v,s.Return);Pointer(v,v.Close);foreach(var t in s.Root.GetComponentsInChildren<TMPro.TMP_Text>(true))Check(Mathf.Abs(t.fontSize*t.transform.lossyScale.x-18)<.1f,"Uniform effective font "+t.name);ScreenCapture.CaptureScreenshot(Root+$"service-{size.x}x{size.y}-{mode}-top.png");var parent=mode=="cargo"?s.Cargo:s.Defense;var targets=s.Actions.Where(a=>a.Button.transform.IsChildOf(parent)).Select(a=>(Selectable)a.Button).ToList();if(mode=="cargo")targets.AddRange(new Selectable[]{v.Railway.Resource,v.Railway.Load,v.Railway.Unload});foreach(var target in targets){Canvas.ForceUpdateCanvases();var rt=(RectTransform)target.transform;var world=rt.TransformPoint(rt.rect.center);float center=-scroll.content.InverseTransformPoint(world).y;float range=scroll.content.rect.height-scroll.viewport.rect.height;scroll.verticalNormalizedPosition=range<=0?1:1-Mathf.Clamp01((center-scroll.viewport.rect.height*.5f)/range);yield return null;yield return new WaitForEndOfFrame();Pointer(v,target);}scroll.verticalNormalizedPosition=0;yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Root+$"service-{size.x}x{size.y}-{mode}-bottom.png");results.Add(new JObject{{"width",size.x},{"height",size.y},{"mode",mode},{"scrollTargetsAccessible",true},{"fontPixels",18}});}}
SetHudReviewResolution.Main(2560,1440);File.WriteAllText(Root+"resolutions.json",results.ToString());File.WriteAllText(Root+"resolution-status.txt","PASS");}}
public static class VerifyHud08EServiceResolutions{public static string Main(){if(!Application.isPlaying||!(Environment.GetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT")??"").Contains("hud-08e"))throw new Exception("Isolated Play required");new GameObject("Railway service resolution verification",typeof(Hud07ServiceMatrixProbe)).hideFlags=HideFlags.HideAndDontSave;return "Queued service resolution checks";}}

public static class SetHudReviewResolution
{
 public static string Main(int width=1920,int height=1080)
 {
  var assembly=typeof(EditorWindow).Assembly;var sizesType=assembly.GetType("UnityEditor.GameViewSizes");var singleton=typeof(ScriptableSingleton<>).MakeGenericType(sizesType);var sizes=singleton.GetProperty("instance").GetValue(null);
  var group=sizesType.GetMethod("GetGroup").Invoke(sizes,new object[]{0});var gt=group.GetType();int count=(int)gt.GetMethod("GetTotalCount").Invoke(group,null),index=-1;
  for(int i=0;i<count;i++){var size=gt.GetMethod("GetGameViewSize").Invoke(group,new object[]{i});var t=size.GetType();if((int)t.GetProperty("width").GetValue(size)==width&&(int)t.GetProperty("height").GetValue(size)==height){index=i;break;}}
  if(index<0){var type=assembly.GetType("UnityEditor.GameViewSize");var kind=assembly.GetType("UnityEditor.GameViewSizeType");var size=Activator.CreateInstance(type,new object[]{Enum.ToObject(kind,1),width,height,"HUD review "+width+"x"+height});gt.GetMethod("AddCustomSize").Invoke(group,new[]{size});index=count;}
  var viewType=assembly.GetType("UnityEditor.GameView");var view=EditorWindow.GetWindow(viewType);if(!SessionState.GetBool("HudReview.HasOriginal",false)){SessionState.SetInt("HudReview.SizeIndex",(int)viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).GetValue(view));SessionState.SetBool("HudReview.HasOriginal",true);}
  viewType.GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).SetValue(view,index);view.Show();view.Focus();view.Repaint();return width+"x"+height;
 }
}
