using System;using System.IO;using System.Linq;using System.Collections;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using EternalSteam;using EternalSteam.OpenWorld;using Newtonsoft.Json.Linq;
public sealed class BaseResourceProbe:MonoBehaviour{
 const string Root="Docs/Measurements/2026-10-02-hud-04/";
 void Check(bool ok,string why){if(!ok)throw new Exception(why);}
 IEnumerator Start(){var run=Verify();while(true){bool next;try{next=run.MoveNext();}catch(Exception e){File.WriteAllText(Root+"play-status.txt","FAIL "+e);break;}if(!next)break;yield return run.Current;}Destroy(gameObject);}
 IEnumerator Verify(){File.Delete(Root+"play-result.json");File.WriteAllText(Root+"play-status.txt","RUNNING");var h=UnityEngine.Object.FindFirstObjectByType<CanvasWorldHud>();var s=h.Sandbox;var c=s.Content;var a=h.BaseResources;s.Persistence.Automatic=false;s.Clock.Paused=true;h.Groups.Select(true);yield return new WaitForSecondsRealtime(.3f);
 string payer=c.MainBase.Module<IBaseIdentity>().BaseId;var def=s.ContentCatalog.Buildings.Single(d=>d.Id=="installation.nexus");var origin=c.MainBase.Cell;int placed=0;
 for(int z=-80;z<=80&&placed<5;z+=4)for(int x=-80;x<=80&&placed<5;x+=4){if(!c.GroundPlacement.Add(def,origin+new Vector2Int(x,z),out _).Success)continue;var result=c.GroundPlacement.Confirm();if(result.Success)placed++;else c.GroundPlacement.Cancel();}
 Check(placed==5,"Six-base pagination fixture");c.Bases.Refresh();c.Bases.Select(payer);var bases=c.Bases.Bases.Values.Where(b=>b.Active).OrderBy(b=>b.Id,StringComparer.Ordinal).ToArray();for(int i=0;i<bases.Length;i++)c.Inventories.Available(bases[i].Id).Deposit("iron",(i+1)*101);
 var reserveDefinition=s.ContentCatalog.Buildings.Single(d=>d.Id=="resource.iron");bool reserved=false;for(int z=-80;z<=80&&!reserved;z+=4)for(int x=-80;x<=80&&!reserved;x+=4)reserved=c.GroundPlacement.Add(reserveDefinition,origin+new Vector2Int(x,z),out _).Success;Check(reserved,"Nonempty ground reservation fixture");int reservationCount=c.GroundWorld.Grid.ReservationCount;Check(reservationCount>0,"Reservation exists");
 a.Refresh();yield return null;Canvas.ForceUpdateCanvases();int objects=h.GetComponentsInChildren<Transform>(true).Count(t=>t.GetComponent<TMPro.TMP_SubMeshUI>()==null);var b=a.Rows[0].Header;var corners=new Vector3[4];((RectTransform)b.transform).GetWorldCorners(corners);var e=new PointerEventData(EventSystem.current){position=RectTransformUtility.WorldToScreenPoint(null,(corners[0]+corners[2])*.5f),button=PointerEventData.InputButton.Left};var hits=new System.Collections.Generic.List<RaycastResult>();h.Raycaster.Raycast(e,hits);Check(hits.Any(hit=>hit.gameObject==b.gameObject||hit.gameObject.transform.IsChildOf(b.transform)),"Header receives pointer");ExecuteEvents.Execute(b.gameObject,e,ExecuteEvents.pointerClickHandler);yield return null;
 Check(a.ExpandedBaseId==bases[0].Id&&a.Rows[0].Body.activeSelf,"First base expands below its header");Check(a.Rows[0].Resources.Single(r=>r.Id=="iron").Value.text=="101","First base stock");Check(c.Bases.SelectedBaseId==payer,"Lookup does not select payer");
 a.Rows[1].Header.onClick.Invoke();yield return null;Check(!a.Rows[0].Body.activeSelf&&a.Rows[1].Body.activeSelf,"Single expansion");Check(a.Title.text.Contains(bases[1].Nexus.DisplayName)&&a.Title.text.EndsWith(" · 2"),"Sticky caption identifies scrolled inventory");Check(a.Rows[1].Resources.Single(r=>r.Id=="iron").Value.text=="202","Second base has separate stock");a.Scroll.verticalNormalizedPosition=.3f;float scroll=a.Scroll.verticalNormalizedPosition;c.Inventories.Available(bases[1].Id).Deposit("iron",7);a.Refresh();yield return null;Check(a.Rows[1].Resources.Single(r=>r.Id=="iron").Value.text=="209","Live stock update");Check(Mathf.Abs(a.Scroll.verticalNormalizedPosition-scroll)<.03f,"Stock update keeps scrolling");
 string expanded=a.ExpandedBaseId;h.Groups.Select(false);yield return new WaitForSecondsRealtime(.3f);h.Groups.Select(true);yield return new WaitForSecondsRealtime(.3f);Check(a.ExpandedBaseId==expanded,"Group return retains expanded base");
 a.Next.onClick.Invoke();yield return null;Check(a.Page==1&&a.Rows.Count(r=>r.Root.activeSelf)==2,"Second page reaches all bases");Check(a.ExpandedBaseId==expanded,"Paging preserves stable expanded ID");a.Previous.onClick.Invoke();yield return null;Check(a.Rows[1].Body.activeSelf,"Return to expanded row");Check(c.Bases.SelectedBaseId==payer,"Paging does not change payer");
 Check(c.GroundWorld.Grid.ReservationCount==reservationCount&&c.GroundPlacement.Pending.Count==1,"Inventory browsing preserves pending placement and reservation");c.GroundPlacement.Cancel();
 // Capture the new list at an actual readable desktop resolution before lifecycle checks.
 a.Scroll.verticalNormalizedPosition=.4f;yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Root+"accordion.png");yield return null;
 int lostIndex=Array.FindIndex(bases,b=>b.Id!=payer);var lost=bases[lostIndex];a.Rows[lostIndex].Header.onClick.Invoke();if(a.ExpandedBaseId!=lost.Id)a.Rows[lostIndex].Header.onClick.Invoke();Check(lost.Id!=payer,"Fixture removal must not remove main payer");c.GroundWorld.Remove(lost.Nexus.Id);c.Bases.Refresh();a.Refresh();Check(a.ExpandedBaseId==null,"Lost base clears expansion");Check(a.Rows.All(r=>r.BaseId!=lost.Id),"Lost row no longer displays stock");Check(h.GetComponentsInChildren<Transform>(true).Count(t=>t.GetComponent<TMPro.TMP_SubMeshUI>()==null)<=objects,"No UI controls created at runtime");
 a.Rows[0].Header.onClick.Invoke();a.Rows[0].Header.onClick.Invoke();Check(a.ExpandedBaseId==null,"Same row collapses");
 File.WriteAllText(Root+"play-result.json",new JObject{{"result","PASS"},{"bases",6},{"independentStocks",true},{"payerUnchanged",true},{"pagination",true},{"groundReservationUnchanged",true},{"stickyBaseCaption",true},{"liveRefreshPreservesScroll",true},{"groupReturnPreservesExpanded",true},{"baseLossClearsExpansion",true},{"savedPointerCallback",true},{"runtimeUICreation",false},{"researchExperiment",false}}.ToString());File.WriteAllText(Root+"play-status.txt","PASS");}
}
public static class VerifyBaseResourceAccordion{public static string Main(){if(!Application.isPlaying||!(Environment.GetEnvironmentVariable("ETERNAL_STEAM_SAVE_TEST_ROOT")??"").Contains("2026-10-02-hud-04"))throw new Exception("Isolated product fixture required");new GameObject("Base inventory verification",typeof(BaseResourceProbe)).hideFlags=HideFlags.HideAndDontSave;return "Queued six-base UI verification";}}
