using System;using System.Linq;using System.IO;using UnityEngine;using UnityEditor;using EternalSteam.OpenWorld;using Newtonsoft.Json;
public static class VerifyTrainConsist{
 const string Root="Docs/Measurements/2026-10-02-train-hud-integration/";
 static void Check(bool b,string m){if(!b)throw new Exception(m);}
 public static string Main(){
 var prefab=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/EternalSteam/Content/Buildings/Railway/Train.prefab");var preview=new PreviewRenderUtility();var go=UnityEngine.Object.Instantiate(prefab);preview.AddSingleGO(go);
 try{var v=go.GetComponent<TrainConsistView>();var d=go.GetComponent<TrainDefenseView>();Check(v!=null&&v.LinkedMotion!=null&&v.Model!=null,"Saved model/clip references");
 var transforms=v.Model.GetComponentsInChildren<Transform>();v.LinkedMotion.SampleAnimation(v.Model,0);var start=transforms.Select(t=>t.localToWorldMatrix).ToArray();v.LinkedMotion.SampleAnimation(v.Model,.5f);float difference=transforms.Select((t,i)=>Mathf.Abs(t.localToWorldMatrix.m00-start[i].m00)+Mathf.Abs(t.localToWorldMatrix.m13-start[i].m13)).Max();Check(difference>.01f,"Linkage must animate");
 v.LinkedMotion.SampleAnimation(v.Model,2);float loop=transforms.Select((t,i)=>Enumerable.Range(0,16).Max(k=>Mathf.Abs(t.localToWorldMatrix[k]-start[i][k]))).Max();Check(loop<.001f,"Loop closure");
 v.Present(false);go.transform.position+=Vector3.forward*.2f;v.Present(true);float forward=v.Phase;Check(forward>0,"Forward phase");v.Present(false);Check(v.Phase==forward,"Stopped phase");go.transform.position-=Vector3.forward*.1f;v.Present(true);Check(v.Phase<forward,"Reverse phase");go.transform.position=Vector3.zero;v.LinkedMotion.SampleAnimation(v.Model,0);
 Check(Vector3.Distance(v.LocomotiveRear.position,v.CargoFront.position)<.001f&&Vector3.Distance(v.CargoRear.position,v.FoundationFront.position)<.001f,"Couplers");Check(go.GetComponentsInChildren<Collider>(true).Length==0,"No unexpected gameplay colliders");
 var renderers=v.Model.GetComponentsInChildren<MeshRenderer>();Check(renderers.All(r=>r.sharedMaterials.All(m=>m!=null&&m.shader.name=="Universal Render Pipeline/Lit")),"URP materials");
 var bounds=renderers[0].bounds;foreach(var r in renderers)bounds.Encapsulate(r.bounds);
 preview.BeginPreview(new Rect(0,0,1600,700),GUIStyle.none);preview.camera.orthographic=true;preview.camera.orthographicSize=4.4f;preview.camera.nearClipPlane=.01f;preview.camera.farClipPlane=100;preview.camera.transform.position=bounds.center+new Vector3(12,10,10);preview.camera.transform.LookAt(bounds.center);preview.camera.aspect=1600f/700;preview.camera.clearFlags=CameraClearFlags.SolidColor;preview.camera.backgroundColor=new Color(.09f,.12f,.14f);preview.lights[0].intensity=2.2f;preview.lights[0].transform.rotation=Quaternion.Euler(40,30,0);preview.lights[1].intensity=1.4f;preview.ambientColor=new Color(.45f,.5f,.55f);preview.Render(true,false);var rt=(RenderTexture)preview.EndPreview();var prior=RenderTexture.active;RenderTexture.active=rt;var tex=new Texture2D(rt.width,rt.height,TextureFormat.RGBA32,false);tex.ReadPixels(new Rect(0,0,rt.width,rt.height),0,0);tex.Apply();File.WriteAllBytes(Root+"train-unity-preview.png",tex.EncodeToPNG());RenderTexture.active=prior;UnityEngine.Object.DestroyImmediate(tex);
 var result=JsonConvert.SerializeObject(new{status="PASS",renderers=renderers.Length,triangles=v.Model.GetComponentsInChildren<MeshFilter>().Sum(m=>m.sharedMesh.triangles.Length/3),animatedDifference=difference,loopError=loop,forwardPhase=forward,reversePhase=v.Phase,bounds=bounds.size.ToString(),savedClip=v.LinkedMotion.name},Formatting.Indented);File.WriteAllText(Root+"train-validation.json",result);return result;
 }finally{preview.Cleanup();}}
}
